### ISSUE TITLE
Code just disappeared.

### ISSUE THREAD

**Issue by CaudilloFranco** [loup99/WtWSMS#104]
So I was making a new event for the Visigoths, and I saved it and all, it took an hour or more. Then I opened up Github, the application, and I wanted to commit this new event to the master branch, but nothing appears. Then, I check my files again and the event I made just disappeared and I am super pissed now. Help?

**Comment by loup99** [comment]
I guess you edited it in another branch and then switched to the master?

**Comment by CaudilloFranco** [comment]
I may have. I'll go check that out.
