### ISSUE TITLE
Missing titles for eastern expansion in develop

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#108]
In develop branch there are some titles with flag and title history, but who don't exist in landed_titles folder:
- k_turfan
- d_tiele
- k_gaochang
- k_jimasa
- k_kashgar
- k_kucha
- k_shanshan
- k_tuyuhun

**Comment by loup99** [comment]
I don't know what Enlil had in mind when he shared the files, but those might planned to be titular (?)
