### ISSUE TITLE
New duchy d_numidiamilitiana 

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#110]
d_numidiamilitiana was introduced by IratePirate in commit d3d6e90.

The de jure changes to attach provinces were:
- c_tmenya (from d_jemsa)
- c_tivzenna (from d_tripolitania)
- c_taggara (from d_great_swarty) 
- c_manzakine, c_mmey, c_fses and c_ssiy (from d_numidia)

It's probably missing title history (?), and color on the map may need to be reviewed as well (red vs green)

**Comment by loup99** [comment]
Going to mention it in the colour project thread. As for history, not sure if necessary given that the territory is controlled by a tribe at start.

**Comment by loup99** [comment]
No need for history at the moment, and the colour project is finished.
