### ISSUE TITLE
Religious Situation

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#111]
A discussion for the religious setup of the mod, that was discussed in the Holy Sites issue:

@Arcvalons 

> Honestly, are some of those super-obscure religions even necessary ?

@loup99

> Yes, we are not removing any religions as far as I know.

@Arcvalons 

> Okay, looked about some of these religions, and I believe Cybelian and Hypsistarian could probably be Hellenic heresies (with mostly the same Holy Sites, maybe one moved to Israel for Hypsistarians) , and Hellenic itself could become its own religious group. Some other existing religions, like Promethean, would also fit nicely within an Hellenic group.

@rquinio 

> Well, it's not really a problem to have multiple mainstream religions (with multiple heresies) in the same religion group (pagan group). I think the idea is that polytheistic religions were much more tolerant to other religions than the monotheistic ones.
> What would be the benefit of creating a separate religion group for Hellenic ?

@Arcvalons 

> Organization, pretty much. I think it could help in the long run to differantiate hellenic religion/civilization separately from, say, arab or finnic paganism, in the code. Plus, hellenic is much bigger and important in 479 than in 769, with several more spin-offs, cults/heresies, etc. branching from it still alive, and they did see themselves as more civilized than others such as the germanics.

@loup99

> Hellenic is not especially significant at start, compared to other faiths. Germanic deserves a separated group if anything in that case. I don't think there is an advantage.

@Arcvalons 

> Yeah, I was going to say the same argument could be used for Germanic. Anyway, right now Cybelian is its own separate Pagan faith and Hypsistarian has a group for itself; Cybele was incorporated into the Hellenic pantheon in 400 BCE so it'd fit as a Hellenic heresy with mostly the same holy sites, and the Hypsistarians... were strange, we only have greek sources talking about them, they are releated to hellenistic judaism, which is why I think theycould work either as Hellenic heresy or Judaism heresy.

@CaudilloFranco 

> Is there Hellenic Judaism in-game? That would be a perfect parent religion to branch off of, according to Wikipedia, hell, I think it should be made as its own new group or at least under the same religious group as Judaism, since Hellenic Judaism was a blend of both IRL. If not they should be Jewish in my opinion.

@loup99

> I don't see why we should split to split, while adding virtually no content. Vanilla has it in a way for a reason. Splitting off the Germanic religion doesn't give us much except for organization, but we loose all of the effects of the pagan group as far as I understood it (no?). If we don't loose anything, I'm all in for splitting though.
> 
>  Hellenic is a minority religion in the mod, not the faith it was before (although I would like to argue that Hellenism on its own has never been significant due to its nature). With the timeframe we have, and even the planned one, I don't see much need for adding Helleno-Judaism, as it would represent no provinces ingame.
> 
>  But what I do think is that, in parallel with the wiki article, we should make a tree that lists all religions and branches, so that we can look at changes or splits more easily and get different sources together, concerning Gnosticism, Manicheanism, Hypsistarian and etc. That way we could uniformise the whole tree and look at what features we want and which we do not, as well as what changes make he most sense. (this would also help with church councils)

**Comment by CaudilloFranco** [comment]
Can Hellenism's Moral Authority, or any "obscure" religions in the timeframe, have a MA penalty for being an Ancient religion? Many that persisted in the Dark Ages were then wiped off the map completely, plus, it would be unrealistic to have Hellenism with an MA of 100 by ~700AD.

**Comment by loup99** [comment]
No need to have such a hardcore penalty, but I think we should seriously consider diminishing the religion ingame. Less provinces.

**Comment by CaudilloFranco** [comment]
Sounds good.

**Comment by Arcvalons** [comment]
>But what I do think is that, in parallel with the wiki article, we should make a tree that lists all religions >and branches, so that we can look at changes or splits more easily and get different sources together, >concerning Gnosticism, Manicheanism, Hypsistarian and etc. That way we could uniformise the whole >tree and look at what features we want and which we do not, as well as what changes make he most >sense. (this would also help with church councils)

Do you think map guides likes the one in Lux Invicta could help, for example, like this:

![Example](http://s26.postimg.org/5tm205d95/Holy_Sites_2014_09_Persian.png)

**Comment by loup99** [comment]
Numarhr is really good at listing religions, but we would need to do our own. But yes, if someone wanted to make that kind of maps it would be great!

**Comment by Arcvalons** [comment]
I made a religion chart with all the religions currently coded in the mod. The "bosporan_faith" one is Hypsistarian, and among other things, therearereferences to currently non existing religions in localisation files, such as a "roman_pagan".

![wtwsms religion chart](https://cloud.githubusercontent.com/assets/16158324/11764829/008b5348-a105-11e5-8f26-92def1fcf2fa.png)

Heresies for Muslim religions should probably use a review. Maybe we could have a Gnostic group to put Manicheaism and a few of the Nicene heresies, too.

**Comment by loup99** [comment]
Gnostic I have asked to Enlil, with no answer so far.

The Muslim heresies are not ingame, so we can ignore those for now

**Comment by Elfangor567** [comment]
I was wondering if perhaps some of these religions should start reformed, such as Ashurian, Hellenic, and Kemetic. These religions were not really in a good place and needed a reform. Most prominently was Hellenic which had a couple of attempts at reformation under some later roman emperors, but the attempts failed.

**Comment by TurtleShroom** [comment]
Why are some pagan religions unreformed if they cannot be reformed? I know of at least one that cannot be Reformed and is thus stuck as a weak, unreformed religion.

**Comment by TurtleShroom** [comment]
#134 

We could also look into incorporating a specific Mod called "Heretic Pride". The creator has pretty much fleshed out every base game's heresy in every possible manner.
