### ISSUE TITLE
Basiliskos becomes nomad after losing war

### ISSUE THREAD

**Issue by OverlordCW** [loup99/WtWSMS#112]
After Zenon wins his war and usurps the ERE Basiliskos gets the nomad government form instead of feudal. This is in the first bookmark.

**Comment by Arcvalons** [comment]
I believe this is an issue with the government type. Does it happen everytime?

**Comment by loup99** [comment]
Might be related to the culture of Zenon (?) as an Isaurian or him at start not being of that government type (?)

**Comment by Arcvalons** [comment]
Originally, Zenon, as an Isaurian, was not in the Byzatnine Culture Group so he could not have the Bureucratic government type. But now a scripted trigger is used and the only condition is that he has to have e_byzantium, so it shouldn't be that.

**Comment by rquinio** [comment]
Should be fixed by https://github.com/loup99/WtWSMS/pull/120, I've noticed similar defaulting to nomad in an other situation.

**Comment by rquinio** [comment]
Fix is merged on master, feel free to re-open if it still occurs.
