### ISSUE TITLE
Italy cannot be reconquered by WRE

### ISSUE THREAD

**Issue by OverlordCW** [loup99/WtWSMS#115]
In the second bookmark Italy cannot be reconquered by the WRE due to it being a titular title, the only cbs available are rivalry and tributary.

**Comment by loup99** [comment]
Are you sure? Well in that case my bugfix did not work. I don't understand, I disabled the attack against titular titles as it caused a lot of bugs, but I don't know how I make it so that the CB covers dejure kingdoms of which the one controlling the land has a titular title.

**Comment by OverlordCW** [comment]
Just start in the 2nd bookmark as Julius Nepos and try to attack Odoacer, it doesn't work for me.

**Comment by OverlordCW** [comment]
Even if I switch to Odoacer and create the two non-titular Italian kingdoms I can't attack him, I have to make one of those his primary title. So having a titular title as your primary will protect you from the WRE and presumably the ERE too.

**Comment by OverlordCW** [comment]
I changed the cb by removing
````
primary_title = {
	is_titular = no
}
````
from the can_use block and adding
````
is_titular = no
````
to the can_use_title, and so far it seems to work.

**Comment by loup99** [comment]
And no ruler has acess to a CB covering a titular title?

**Comment by OverlordCW** [comment]
I don't really understand your question. The way it is set up now in git is that the reconquest cb cannot be used against someone whose primary title is titular, e.g. Odoacer.

**Comment by loup99** [comment]
No, ignore it.
