### ISSUE TITLE
WRE, ERE and successor states cannot use holy war

### ISSUE THREAD

**Issue by OverlordCW** [loup99/WtWSMS#117]
I don't know if this is WAD, but in case it isn't here is how to fix it:
Remove the following from the can_use block of the religious cb
````
NOR = { 
	has_romance_culture_trigger = yes 
	has_landed_title = e_byzantium
	has_landed_title = e_wre
}
````
and add the following to the start of the can_use_title block:
````
NAND = {
	ROOT = { has_landed_title = e_byzantium }
	region = custom_pars_orientalis
}
NAND = {
	ROOT = { has_landed_title = e_wre }
	region = custom_pars_occidentalis
}
NAND = {
	ROOT = {
		NOT = { bureaucratic_government_trigger = yes }
		has_romance_culture_trigger = yes
	}
	region = custom_imperium_romanum
}
````
this ensures that the holy war cb cannot be used in regions the reconquest cb can be used.
Maybe this code can be more optimized, I don't know.

**Comment by loup99** [comment]
WAD.
