### ISSUE TITLE
Loup's Scandinavian Overhaul

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#12]
The aformentioned Scandinavian Overhaul. Link to discussion: http://forum.paradoxplaza.com/forum/group.php?discussionid=1013&do=discuss. I will work on this slowly but surely.

**Comment by loup99** [comment]
A question, @rquinio probably knows this the best, but in order to avoid breaking saves and etc while doing this, should I create a branch?

**Comment by rquinio** [comment]
I don't have much experience on save breaking, but a separate branch seems like a good idea.

**Comment by loup99** [comment]
Ok, will do that then. I was mostly asking for the branch.

**Comment by loup99** [comment]
I made a branch entitled "dev", will use it for Scandinavia

**Comment by loup99** [comment]
It has been reworked as of the end of this part of the Operation.
