### ISSUE TITLE
PROV1452 c_dunkheger display bug

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#126]
Linked to https://github.com/loup99/WtWSMS/issues/92:

- PROV1452 province name doesn't show on the map.
- d_altay title name doesn't show on the map.
- Other entities that the county is part display badly on the map (e_rouran, k_mongolia, xianbei culture)

**Comment by loup99** [comment]
The best way of solving this is probably to ask in the Quick Questions Thread if it hasn't been done already.

**Comment by rquinio** [comment]
Indeed ! Issue solved :)
