### ISSUE TITLE
Accurate Hebrew Culture Naming Conventions Flavor

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#127]
Good evening.

Anyone who has read the Torah/Old Testament, the sacred text of Judaism, will notice these same naming conventions again and again.

"X was the father of Y, son of X."

What I propose is that Hebrew sons get this name convention. If the son's name is Dooley, and the father's name is Bubba, the resulting convention in the title would be "Dooley, Son of Bubba".

It'd be a good flavor addition due to its use in Jewish Scripture.

-TURTLESHROOM

**Comment by loup99** [comment]
I don't know if this is possible (although I think it is), so we can look into that.

**Comment by CaudilloFranco** [comment]
Wouldn't it be the same as Viking names? Like Bjornsdottir or Haraldsson?

**Comment by loup99** [comment]
No.

**Comment by TurtleShroom** [comment]
I thought that all cultures could be given naming conventions.

For example: a Russian, male child named Bubba, birthed to a Russian man named Bubba, is "Bubba Bubbavich". Most cultural groups have their own conventions. Creating or editing one for Hebrews would be simple matter of editing the naming conventions' file(s), right?

**Comment by rquinio** [comment]
Yes, there's some patronymic configuration (cf http://www.ckiiwiki.com/Culture_modding#Patronyms)
Currently for Hebrew culture:
````
male_patronym = "Ben-"
female_patronym = "Bat-"
prefix = yes
````

You want to change it to 
````
male_patronym = ", son of "
female_patronym = ", daughter of "
prefix = yes
````
?

**Comment by TurtleShroom** [comment]
Yes for the sons, not for the daughters.

The Bible consistently says "SON son of FATHER", but I've only seen "DAUGHTER was the daughter of FATHER" or "and FATHER bore two daughters, NAME and NAME". As a _title_, only "X, son of FATHER" would be Biblically accurate.

(As a Christian, I only have access to the Old Testament, the Torah, and not the rest of Judaism's canon. All I can say is in reference to the sons.)

**Comment by nsinger998** [comment]
*tone: Pleasant, Helpful

Not sure if I'm allowed to post but felt I had to add:

"Ben-" is the Hebrew word for 'Son of'

"Bat-" is the Hebrew word for 'Daughter of'

Using English translations of the bible can be problematic as you lose the intricacies of the Hebrew language. For example: the sample verses listed above by Turtle Shroom, would have used forms of the words 'Ben' and 'Bat' in hebrew and are still used by us(Jews) as Patronyms till this day. :)

**Comment by ElfDecker** [comment]
I am Jew, and, in my mind, "ben-" and "bat-" are the most preferable forms for this.
