### ISSUE TITLE
Can Mastimanis Sacrifice In-Game?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#131]
Good evening.

The text for Mastimani pagans explicitly says that they commit human sacrifice, but I have yet to encounter a Mastimani actually sacrificing a prisoner. Am I overlooking something, or are Mastimanis not able to commit human sacrifice in this Mod?

-TURTLESHROOM

**Comment by loup99** [comment]
From what I see in the mod files, there is nothing for them currently in terms of events.

**Comment by TurtleShroom** [comment]
Really, all you need to do is add a Human Sacrifice decision like the Norse and Aztec have. Absent any specific information on how Mastimatis commit human sacrifice, just make a placeholder Event that says something along the lines  of "X Y of Z has been brought before our PRIEST_TITLE and has been put to death. The gods are pleased by our gift to them, as we were so commanded".

If you'd like, I can do the research myself and come up with Localization code.

**Comment by TurtleShroom** [comment]
https://github.com/loup99/WtWSMS/pull/164/commits/298a0a46e6fbf0b24583835ed80464ab38480b35

After months of waiting, I've decided to take the liberty of writing the sacrifice event myself.

**Comment by loup99** [comment]
It has already been added.
