### ISSUE TITLE
Information On Root West and the Tanguts

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#132]
Good evening.

I did a little digging on Root West paganism, [and found a very interesting source on the religion](http://kepping.net/pdfs/works/The_Black-headed_and_the_Red-faced.pdf).

It explained a lot about what Root West clergy looked like and some of their customs. I want to show you a few of them in order to reccomend graphics implementation of the clothing of Root West pagans.

> When examining the lists of features peculiar to each of the group, one gets
an impression that the blackheaded possessing blessing given by the Heaven,
served as mediators between the Heaven and the redfaced (the Heaven gave the
knowledge to the blackheaded and they transferred the knowledge to the red
faced). Such situation is characteristic for the relations between a priest and a
layman.

> The Tangut blackheaded wore felt hats. The colour of the hats is not specified, but one gets an impression that what was on the heads of the blackheaded, obviously was of black colour (if the
colour of the felt hats was not black, it should be pointed out). Mind that the
grass on the heads was black (see footnote 24).

>It is known that in preBuddhist times priests in Tibet were wearing black
caps. While depicting the performance of a mysteryplay at the Himis monastery
in Ladak (this performance is acted at the end of the year), L. A. Waddell states
that the first to come out after the commencement of the play is «a crowd of the
preLamaistic blackmitred priests (italics mine  К. К.), clad in rich robes of
China silk and brocade, and preceded by swingers of cencers» (Waddell 1985:
521522).

>Thus, we may state that the Tangut term «blackheaded» originally designated
some kind of Tangut preBuddhist priests. All the more the proportion is one to
ten: the same correlation for priests Aaymen was pointed out by L.A. Waddell for
Sikkim and Bhutan (Waddell 1985: 171).

>One more corroboration for the statement that the blackheaded were priests,
is found in the cited above example {26}, where it is stated that the redfaced
deferentially greet the blackheaded with folded hands. This is the way the
Buddhist priests are known to be greeted.

Notice that Root West clergymen were called "blackheaded". Perhaps a special Trait (similar to the Druid trait) could exist that automatically added the nickname "the Black Headed" to any Root West pagan holding a temple?

Also, it states that almost all Tangut/Root West holy scriptures were musical, in the form of Odes. The most important they showed was "The Great Ode", [as well as several other odes](https://books.google.com/books?id=-xk_CwAAQBAJ&pg=PT16&lpg=PT16&dq=tangut+%22great+ode%22&source=bl&ots=1NKpqphPj3&sig=CNJ-SzjX-GQPN3mPDXsCKqGrpfc&hl=en&sa=X&ved=0ahUKEwiGkMGgyqrLAhXG0iYKHfEvB-YQ6AEILDAD#v=onepage&q=tangut%20%22great%20ode%22&f=false).

[The_Black-headed_and_the_Red-faced.pdf](Here is the full file talking about Root West and the customs of "the blackheaded" and "red-faced".)

I hope this can be of help. I'd really like to see Root West become a pagan religion that can be Reformed!

-TURTLESHROOM

**Comment by TurtleShroom** [comment]
The same source of describing Tangut clergy and the like also has several other Tangut publications!

http://kepping.net/raboty.htm

These could be used for flavor Events and Decisions for Reformed and unreformed Root West Pagans!

Not only that, I found a Wikipedia summary of the Tangut people drawing from that source I mentioned earlier:

> The Tanguts divided themselves into two classes: the "Red Faced" and the "Black Headed". The Red Faced Tanguts comprised the commonality (rulers) while the Black Headed Tanguts were the elite priestly caste (clergy). 

> Although Buddhism was extremely popular among the Tangut people, many Tangut herdsmen continued to practice shamanism, known as Root West. 
>The black caps worn by Root West shamans gave the Black Headed caste its name. According to Tangut myth, the ancestor of the Black Headed Tanguts was a heavenly white crane, while the ancestor of the Red Faced Tanguts was a monkey. 

>Ancient sources describe Tanguts as being short, stocky, dark-skinned, and thick-lipped. They wore their hair in the Tufa style, shaved bald except for a long fringe of bangs that framed the face. 

> Tangut kings went by the title of Wuzu.

This is INVALUABLE information,

I made a crude sketch of how I'd imagine this to look.

http://i.imgur.com/cd89Fmj.png

**Comment by loup99** [comment]
Very interesting! But for any art/gfx, I'm not sure of we have someone in the team that is capable of doing it.

**Comment by TurtleShroom** [comment]
Perhaps you could post a Help Wanted notice on this Issue and see if you can recruit someone on the Forums that worked on "Game of Thrones"? They had several modifications of characters' appearences over there. Maybe someone could lend a hand?

**Comment by TurtleShroom** [comment]
I can't access the Mod sub-forums on the Paradox Forums. It's some sort of weird bug I'm experiencing. Otherwise, I'd advertise it myself.

**Comment by loup99** [comment]
Sync your account with Steam.

**Comment by TurtleShroom** [comment]
How do I do that?

**Comment by rquinio** [comment]
It's explained here: https://forum.paradoxplaza.com/forum/index.php?threads/connect-your-steam-account-to-sync-your-owned-items.894506/

**Comment by TurtleShroom** [comment]
Okay, I checked, and my account is synchronized with the Steam Console.

**Comment by loup99** [comment]
Screenshot?

**Comment by loup99** [comment]
Sceenshot? Otherwise, look into the forum support.

**Comment by loup99** [comment]
- I will see if there is anything we can do on the matter do get help
- Yes, do you want help with how to code it? Look into the wiki http://www.ckiiwiki.com/Modding for some helpful bases, and then I can probably help you out with the rest
- Yes, more or less, depending on their nature historically

**Comment by TurtleShroom** [comment]
I could help with any Localization (changing Tangut King to Wuzu). I understand how to do that.

**Comment by loup99** [comment]
I'll give you the rights to do it.

**Comment by TurtleShroom** [comment]
I meant that I understand how to WRITE localization and I can figure out how to FIND the needed localization file.

 I've never used Github in my life, and I don't feel comfortable messing with your files. When I write localization files, I always try and create a separate CSV file with my stuff in it, to avoid any damage to the rest of the stuff in a list.

I'm working on the Root West changes right now.

**Comment by TurtleShroom** [comment]
Ah'ight, here's what I've got.


[root_west_pagan.zip](https://github.com/loup99/WtWSMS/files/201047/root_west_pagan.zip)

**Comment by TurtleShroom** [comment]
@loup99 



Ah'ight, here's what I've got.

[root_west_pagan.zip](https://github.com/loup99/WtWSMS/files/201047/root_west_pagan.zip)

**Comment by rquinio** [comment]
@TurtleShroom Nice, I'll test the changes and put them on a github branch

**Comment by TurtleShroom** [comment]
@rquinio 

Thank you for understanding my limitations and testing them for me. I am actually on the board of directors for a Super Mario Mod, which would be a total overhaul of CK2 for the Mario series' universe, and all I've committed to doing is brainstorming, art (using video games sprites and such), and localization.

Unfortunately, because this is the first time I have EVER done any serious localization that wasn't assigned and described to me in detail, I got lost in the byzantine web of folders and files needed to implement a Reformed Root West religion, and even to create localization for the Root West stuff I committed to doing.

I've updated the entries for "root_west_pagan" in "RELIGIONS.TXT" and I've created titles for the clergy of the same. I also created an entry for "root_west_pagan_reformed" in "RELIGIONS.TXT", and I created a "WTSMS_PAGAN_RELIGION_TITLES.TXT" entry and history file for "d_root_west_pagan_reformed". 

After that, I will design a Coat of Arms for "d_root_west_pagan_reformed".

**Comment by rquinio** [comment]
I've integrated and tested the changes, please review.
- I had to cut a bit religion descriptions (too long) and remove duplicate features with the one added automatically by the game.
- Flag for d_root_west_pagan_reformed and coats_of_arms are placeholders.
- Maybe Norse religious clothes / 4th frame (black) would be better placeholder than the Buddhist ones (orange), based on descriptions ?

**Comment by TurtleShroom** [comment]
Okay, here's my design for "d_root_west_pagan".

![d_root_west_pagan](https://cloud.githubusercontent.com/assets/17663470/14391411/d28d5c7a-fd89-11e5-9918-d82c0bdb3012.png)

The symbolism is simple: the red bar represents the "red faced", the secular leaders who follow Root West Paganism. The black bar represents the "black headed", that is Root West clergymen. 
The crane is obvious: Root West Pagans worshipped the crane and saw it as the creator of the "black headed".

It's in PNG format. You can rename its extension to TGA, and it should work fine.

**Comment by TurtleShroom** [comment]
Here is the flag for "d_cranesmen", the Holy Order spawned by Reforming the Root West Pagan faith.

![d_cranesmen](https://cloud.githubusercontent.com/assets/17663470/14391567/c99e706c-fd8a-11e5-8623-2b7cdbdf797e.png)

**Comment by TurtleShroom** [comment]
Lastly, here's the localization for the Events that, respectively, announce the Root West Reformation and the spawning of the Cranesmen.

1. ROOT WEST REFORMATION:

rwreformspawn;Root West Pagan Reformation!;;;;;;;;;;;;;x

rw-reformspawnDESC;Centuries of encroachment by the foreign doctrines of Siddhartha Gautama have lead many great men astray. Faced with anniahaliton, one great Wuzu stood up for all worshippers. At long last, the black headed have coalesced under one Intercessor, who now protects and guides all Root West faithful! Our great songs have been encoded into one hymnal, and we have a standardized liturgy and holy texts, authenticiated by our greatest scholars, to ensure no Root West worshipper goes astray.;;;;;;;;;;;;;x

rw-reformspawnBUTTON;The old gods are strong and their warriors are mighty!;;;;;;;;;;;;;x

--------------------------------

2. ESTABLISHING THE HOLY ORDER OF ROOT WEST:

cranespawn;The Holy Red Order of the Cranesmen;;;;;;;;;;;;;x

cranespawnDESC;The Buddhists and foreigners are naturally vengeful at our revival and resurgence, but no matter! The Holy Cranesmen will protect everyone, Red Faced and peasant, wherever a Root West worshipper stands! These great warriors are the cutting edge horsemen, feared across the steppes and dreaded even in the Middle Kingdom. They will guard our sacred lands!;;;;;;;;;;;;;x

cranespawnBUTTON;* crane screech *;;;;;;;;;;;;;x

**Comment by rquinio** [comment]
Changes are now merged to the master branch.

@TurtleShroom Feel free to research/design some mechanics/localization/graphics in a similar way for other religions and if others agree, I'll implement them into the mod !
