### ISSUE TITLE
Cannot Migrant as Slavic Religion (Converted) Venedis?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#133]
Good evening.

I am addicted to your Mod with a fierly passion. I can't imagine CK2 without it.

In my most recent game (beginning at the earliest start), I was playing as the Vistula-Venedis (west of Apae and northwest of the Hunnic Empire, the one with the moon and grass for their duchy's flag) and wanted to Migrate. Since Baltic Pagans cannot Migrate, I converted my ruler to Slavic Pagan.

I discovered immediately that I was unable to Migrate to any nation in range! I could only subjugate them. Is there something wrong? I wanted to migrate to the east and take the valuable clay of a steppe nomad near the Hunnic Empire.

-TURTLESHROOM

**Comment by loup99** [comment]
Conditions: 
*You must be Slavic, Tengri, Germanic Pagan or Alan culture
*You cannot declare a migration war after 800
*You have not migrated in the last 10 years
*You are a duke or above
*You are independent
*You are not at war
*The target must be independent

**Comment by TurtleShroom** [comment]
Okay, for some reason, I reloaded the game and successfully Migrated with the exact same conditions present. Consider this Issue closed: I must have made a mistake earlier.

**Comment by rquinio** [comment]
Ok, don't hesitate to re-open this issue and add more info to it, if you reproduce.
