### ISSUE TITLE
Incorporating "Heretic Pride" Mod

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#134]
Good evening.

Have you considered implementing one of the best CK2 Mods in the game? It's called **[Heretic Pride](http://steamcommunity.com/sharedfiles/filedetails/?id=429345495)**, and it's AMAZING. It has huge features for every religion except the Monophysites, including new laws, new traits, and features unique to each one and found in no other. 

I'm just going to list a few of its features.

> Iconoclasts get Events about smashing icons dating back to the Ancient Church (these "holy eikons" were, in RL, deemed so sacred that only the most zealous Iconoclasts smashed them).
> 
> Druze get a trait where they hide their mysticism and gnostic operations and instead practice a rigid form of Islam that increases the opinion of other Muslims and boosts their intriuge. If the Druze become suffeciently powerful, they can "come out of the closet".
> 
> Messalians are expanded beyond incest and include their greatest and most shocking trait. Messalians, in RL, believed that every human had demons in them and that they must be prayed out. Once they are prayed out, a Messalian was allowed to sin without consequence. This was a hyper-exaggeration of the Cathar "perfects". Where Cathars did believe perfection could be reached, they believed that a Perfect was not to sin at all. Messalians didn't.
> 
> Yazidis can make pilgrimages to Mosul, carry statues of the seven angels in a festival much like the Hajj, and choose to venerate an angel of their choosing like the Hindus.
> 
> One Zoroastrian heresy was considered "proto-socialism" and they can pass unique laws that drastically decrease tax revenue in exchange for slashed revolt risks and Prestige, representing welfare for the peasantry.
> 
> Lollards can print Bibles of their own en masse.
> 
> Cathars can form their own Papacy with a twist, consisting of a Perfect that has won the approval of other Perfects. The Cathar Pope can be female!
> 
> Zikris can become the Mahdi (the Zikri Caliphate in the Vanilla game) if conditions are right and lead an Islamic doomsday cult to total domination of the map. Like the Zoroastrian Sayoshant, their kids get a "child of Mahdi" Trait.
> 
> Samaritans can build their own version of the Temple on their unique holy mountain. They can form their own High Priest.

Implementing this would greatly flesh out many religions that were outside the purview of this Mod, and could be used to expand other heresies, especially the Nicene ones.

-TURTLESHROOM

**Comment by loup99** [comment]
I'd love to inspire ourselves from the mod, but integrating this would require someone that is deeply invested in the religions of the period. I'd also like to look into the Tolerance system mentioned in the forums before.

**Comment by TurtleShroom** [comment]
Integrating the "Heretic Pride" Mod would need no research on your part. It would need coding and the original author's permission, and BOOM, instant flavor for every Vanilla heresy!!

That's an irresitable offer right there!

**Comment by Arcvalons** [comment]
Actually, I think we should be wary about feature creep during the beta, and rather than adding as many features as we can, focus on smoothing the ones we have and the ones right now and the ones that have been planned since the beginning (councils, islam, etc.)

**Comment by loup99** [comment]
I agree with Arcvalons.

**Comment by TurtleShroom** [comment]
It's not "feature-creep" to flesh out religions and heresies. That's a fundamental duty for all Mods.

Incorporating Heretic Pride would only flesh out the specific, _Vanilla heresies_ (such as Bogomolist, Messalian, Samaritan, etc. etc.). It would not affect your Mod's timeframe. It'd be effortless to incorporate such things and all research has already been done by the Mod creator.

**Comment by loup99** [comment]
But these "vanilla" heresies are either not relevant for the mod (so unnecessary) or were somewhat different during the mod timeframe. 

It would not be effortless, as it would still require updating the mod for 2.5.2, merge it with WtWSMS, adapt it for WtWSMS and then maintain it.

**Comment by TurtleShroom** [comment]
How would the heresies not be relevant? When the Schism happens, all the vanilla heresies come into effect, and when Islam breaks apart, those heresies happen as well.

**Comment by loup99** [comment]
I would prefer having the schism in place before adding more flavour to the heresies. Then we can look into this!

**Comment by TurtleShroom** [comment]
Well, that's really what I was hoping for. It's more a less of a guarentee that it will happen _down the road_.

Is there anything I can do to help you or help this Mod? I am an amateur theologian and have dedicated my life to the further study of my faith. I can help you with anything dealing with theology or the meanings of and behind Christianity. It's not much, but I can help you with what I can.

**Comment by loup99** [comment]
The best thing would be if you could discuss on the forums, either in our dev group if you want to look at code, or in the general mod forums.

**Comment by TurtleShroom** [comment]
Hold on, please do not close this yet. I am trying to contact the Mod's author.

**Comment by loup99** [comment]
For what? The decision is to look at flavour and sources while not integrating anything. Contacting the author is not needed as no code will be incorporated.

**Comment by TurtleShroom** [comment]
There s some really good flavor for the Yazidis and Maneichans, to start. The Yazidis were far more common before Islam than after. It wouod allow players seeking to play as Yazidis to really enjoy themselves.

You told me it would not be implemented because I lacked permission from the author.

The beauty of Heretic Pride is that it does not replace existing files (with one exception, which was optional for the Mod). Incorporating HP is almost entirely painless and easy enough that I can do it myself.

Remember, ALL heresies get flavor, which includrs the bare bones Zoroastrian heresies, the Muslim heresies, and more.

Obviously, the Christian ones are irrelevant for obvious reasons until the late game, but still, this wouod be of trenendous value to the Mod.

**Comment by loup99** [comment]
The Manicheans are getting overhauled. As for Yazidis, they are a Muslim heresy, so not relevant at the moment. 

I told you it would not be implemented without a permission, but previously I also said no unadapted content would get into the mod. Therefore we shouldn't integrate anything of it, and rather look at the code for flavour or ideas. 

All heresies are different in WtWSMS, as we treat Zoroastrianism, Christianity and Islam differently. The only heresy I could envision being relevant would be for Judaism, but then we still need to adapt it.

**Comment by TurtleShroom** [comment]
That makes sense. I misunderstood what you meant about no implementation: you mean no _straight_ incorporation of any Mod. 
I agree that we shouldn't flat-out implement them due to the differing time periods of this Mod. When I get permission from the Mod's author, I will start to adapt and incorporate the Mod with adaptations for this time period.

As for the Yazidis, them being listed as a Muslim heresy in this time period is wrong. In my Pull Request, I rightly placed them under the Zoroastrians.

I feel that there should be an Event or Decision in which the Yazidis are relegated to an Islamic heresy if a Muslim character conquers their ancestral land, or if enough Kurds become Muslim, etc. . Yazidis existed in this time period in abundance in the Kurdistan area. Moving them to the Zoroastrian Group as a Zoroastrian heresy would be valuable to the Mod.

In addition, the HP Events and additions would supplement your Manichean overhaul, not counter it!

**Comment by loup99** [comment]
The Yazidis will stay as they are for now, once Islam is added we can look into that.

I just want those additions to be added after the overhaul, not before.
