### ISSUE TITLE
Switching to Bureaucratic Government

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#135]
Quoting @Turtleshroom :
> Is it possible for an empire to reform to the Bureaucracy government type, similar to the "Imperial" law decision?

**Comment by TurtleShroom** [comment]
Well, is it?

**Comment by loup99** [comment]
No.

**Comment by loup99** [comment]
If I were to add this, it would probably be through the "Imperial Administration Law" from vanilla.

**Comment by Arcvalons** [comment]
That sounds like a good idea. A sufficently advanced realm could in theory enact such law and become Bureucratic, even if they are not Roman.

**Comment by loup99** [comment]
What I have in mind for this: 

- Allow for players to switch from a feudal to a Bureaucratic government type
- Requires the Imperial Administration law and the Bureaucratic government triggers
- Would add a temporary opinion penalty with feudal vassals because of the change

**Comment by loup99** [comment]
Has now been added, except for the flavour on which I can take suggestions on the forums, on the group or here on a separate issue. Closing this one.
