### ISSUE TITLE
Migrational Invasion of a Steppe Horde Gave Me a Game Over

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#136]
Good afternoon.

I started a game as the Crimean Gothics and decided that I was going to Migrate on top of a Horde, specifically, the horde bordering the Hunnic Empire to the northeast. I was willing to take a gamble to see if that would convert me to a Horde myself because all of my counties land had no holdings.

To my surprise, when I successfully defeated the Horde and Migrated, I lost my ducal title and was given a Game Over. The game told me that I had lost my last County and could no longer continue playing.

What happened, and was there something that I did that was wrong?

-TURTLESHROOM

**Comment by rquinio** [comment]
But... you're going the wrong way, you should migrate southwest ;)
More seriously, sounds like some scripting needs to be added to handle that case, as the migration was developed before nomads were added to the game !

**Comment by rquinio** [comment]
I've fixed it, by creating tribal holdings in nomadic provinces.
But the migration CB is not currently restricted to tribal rulers, though it probably should ?

**Comment by loup99** [comment]
Tribal and nomad, no?

**Comment by TurtleShroom** [comment]
You know, it'd be kind of neat if tribal Migrants overrunning Steppe Hordes could be given the option _to become Hordes themselves_. These people were already nomadic to a degree (or at least semi-nomadic). Going all the way doesn't sound completely impossible.

**Comment by rquinio** [comment]
@loup99 Nomads have specific CBs (nomad_expansion, nomad_invasion, nomad_subjugation), so I think migration CB should be restricted to tribal.

**Comment by loup99** [comment]
I believe those CB's havent been tweaked and tuned as much as the Migration CB, but you do have a point in that.

**Comment by loup99** [comment]
As the original bug is solved, I will close this issue, but re-mention the restriction in the dev group.
