### ISSUE TITLE
Restore Hunnic Empire Decision for All Huns

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#137]
Good afternoon.

I looked at some of the requirements to restore the Hunnic Empire if it is crushed. Alongside the obvious Hunnic culture, for some reason, it requires you hold an obscure county in Dalmatia and five thousand Prestige. It also needs you to be Pagan. Why?

Personally, I think that's way too hard to do. I think that the Hunnic Empire should be restored by a Decision, but only if a Hunnic character meets the standard requirements for founding a custom Empire (one thousand Prestige, six hundred Gold, two hundred Piety, a certain number of Holdings or three Kingdoms under their belt).

That would make it a challenge, but not next to impossible. Also, any Hunnic character should be able to restore the Hunnic Empire, not just Pagans. That's an arbitrary rule.

-TURTLESHROOM

**Comment by loup99** [comment]
There are labels for a reason, so if you are to use this, it would be good if used them.

**Comment by TurtleShroom** [comment]
I don't know how to add Labels. I would if I could, but I don't know how. I thought the moderators added them.

**Comment by loup99** [comment]
Oh, Ok, might be the case.

**Comment by loup99** [comment]
I believe that the restriction is in place because in case the Huns convert to a non-Pagan faith, there would no longer be the same will for conquest. But perhaps it could require you to be of the nomad government instead?

**Comment by TurtleShroom** [comment]
Nomad-only restrictions might work.

Personally, I think anyone with Hunnic culture should be able to restore it. I don't think religion would fully change the Huns, who are a natural warrior race. The Mongols were under a Nestorian Khagan for a short period of time, but they still conquered. All it'd really do is change how they govern and what values they emphasize.

I suggest this:
- Nomadic and Tribal Huns need four thousand Prestige, six hundred Gold, and no vassal should have a negative opinion of them. (In RL, Atilla the Hun only won the Khagan's crown by assent of his peers, whom he unified.)
- Feudal Huns need five thousand Prestige, one thousand Gold, and at least two Kingdom.
- Merchant Huns need six thousand Prestige, two thousand Gold, at least two Kingdoms, and no negative opinion from their vassals. (This represents the idea that Republics are weak and inglorious. A Merchant Prince would have to work VERY hard to claim Atilla's crown.)
