### ISSUE TITLE
How Do I Break a Bureaucracy?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#138]
Good afternoon.

I've played this Mod several times (I am addicted), and I've yet to see any means for which a Bureaucratic government will collapse. The Localization description states that if the realm becomes "unstable", everything implodes, but from what I've seen, instability is a Law and not a flag or state. How exactly does one go about destabilizing a Bureaucratic blob?

I'd love to figure this out, just to watch the world burn and pick up its pieces.

-TURTLESHROOM

**Comment by loup99** [comment]
There isn't anything special.
