### ISSUE TITLE
Culture questions

### ISSUE THREAD

**Issue by ghost** [loup99/WtWSMS#141]
So, now that I finally have some free time to do some serious work on making use of the large amount of cultures in WtWSMS' file, I would like to know what exactly they are, so that I don't end up having something goofy like a latin german culture ending up in persia or something.

So, the cultures I'd like to know what they are suppose to be are:
Bucinobantian
Gothi
Berjuldi
Thurins
Alamanici
romansh
geruly
tyuringii
tracki
sklav
antae
alzzecio

**Comment by loup99** [comment]
_Gothi_ = Melting-pot/transition culture

**Comment by loup99** [comment]
- _Gothi_ - Melting-pot/transition culture in Iberia, which shifts to Castillian, Leonese, Catalan, Portugese or Andalusian
- _Thurins_ - Melting-pot culture for Thuringians which are in contact with Latin influence
- _Geruly_ - Melting-pot culture for Slavic and Herulians
- _Tyuringii_ - Melting-pot culture for Thuringians and Herulians
- _Tracki_ - Melting-pot culture for Slavic and Thracians
- _Sklav_ - Slavic culture that was merged with Russian, Venedi, and Antae cultures into a more general culture
- _Antae_ - Slavic culture that was merged with Russian, Venedi, and Sklav cultures into a more general culture
- _Berjuldi_ - Unknown left-over that ought to be removed
- _Alzzecio_ - Melting-pot culture for Italians and Bulgyar
