### ISSUE TITLE
Rouran Khaganate Game Crashes When Settling As Tribal

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#145]
Good afternoon.

I am dealing with a strange glitch as the Reformed Root West Khagan of Rouran. In one of my holdings, which is Nomadic-Blank, I have a Tribal Barony that is owned by someone else. When I try to settle as that Tribe, the game immediately freezes and crashes a short few minutes later. Why am I unable to properly settle?

Should I move my capitol to the same location, so that I can make that Tribal Barony into my capital?

-TURTLESHROOM

**Comment by TurtleShroom** [comment]
Would you like me to upload the save file for your viewing, or something? If you need any help assessing my issue, I'd be glad to give it to you.

**Comment by loup99** [comment]
Uploading the save file would help, although I don't understad exactly what you are trying to do in a province without holdings and how you would settle in the holding of another tribe.

**Comment by TurtleShroom** [comment]
Okay, it worked like this.

I own a County that has no official capital-holding because it is a Blank Nomadic Holding. It, however, had a barony that was owned by one of my direct vassals. I right clicked that barony and used "Settle as Tribe". The game immediately crashed.

I have not yet tried revoking the Tribal Barony and making it the capital; I'll do that next, but I'll get the saved file uploaded right now/.
[Iron_Man_Rouran_Khaganate.zip](https://github.com/loup99/WtWSMS/files/232751/Iron_Man_Rouran_Khaganate.zip)

**Comment by TurtleShroom** [comment]
Is there any update on this issue?

**Comment by loup99** [comment]
There will be, eventually.

**Comment by TurtleShroom** [comment]
That's all I wanted to know. I am fine with waiting. Thank you.

**Comment by loup99** [comment]
I have looked into this, and I can't use your savegame as I don't have Conclave. I think you shouldn't be able to settle as a tribe on one of your vassal's holdings.

**Comment by loup99** [comment]
OK, I was able to reproduce the crash.
