### ISSUE TITLE
Could I Create a Branch to Expand On Root West and Some Other Provisions?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#147]
Good afternoon.

I have wanted to further my participation in this project by editing the files myself, directly. Supposedly, you can edit files without damaging the master Mod if you create a "Branch" and editing files there.

Unfortunately, I have no idea how to do this, nor do I know how to use Github.

Could I formally join your project and make changes, subject to your approval and review? I can deliver the same quality information I gave for Root West. (-and actually, I made a few mistakes in Root West's code, namely, that I didn't put the Crane in the lower-god section, causing almost everything to say nothing but "Founding Monkeys".)

-TYLER JONES

**Comment by loup99** [comment]
Of course! Create a fork of the mod out of the master branch with GitHub for Windows, and then you should be able to do pull requests.

**Comment by TurtleShroom** [comment]
How do I create a Fork, and with what do I do it? I have no idea what any of that terminology means. What is a pull request? How do I prevent myself from accidently editing the Mastrer files?

**Comment by loup99** [comment]
Fork: https://help.github.com/articles/fork-a-repo/
Pull requests: https://help.github.com/articles/using-pull-requests/

**Comment by TurtleShroom** [comment]
Okay, I downloaded it and I think I'm doing it right. I created a "TSP" Branch. The problem is that I can only set one Pull Request per commit of changes. So, for example, the Root West and religious tweaks can only be committed once, and then I'd have to create a New Pull Request for the next batch of changes.

**Comment by TurtleShroom** [comment]
"IT SEEMS YOU DO NOT HAVE PERMISSION TO PUSH YOUR CHANGES TO THIS REPOSITORY"

![i have no idea what i am doing](https://cloud.githubusercontent.com/assets/17663470/15226605/6947e5d6-1851-11e6-862a-d882bb522f82.png)

**Comment by TurtleShroom** [comment]
Why isn't my Branch and my Pull Request showing up?

**Comment by loup99** [comment]
You don't need to create a branch one you have a fork. You are also confusing commit with pull requests. And no, you can't push directly, because then there is no purpose of doing a pull requests.

**Comment by TurtleShroom** [comment]
@loup99 

How do I create a Pull Request? When I click the big "CREATE PULL REQUEST" button, all it asks me is to "compare" the existing Pull Requests to the Master. I have absolutely NO IDEA what I am doing.

**Comment by TurtleShroom** [comment]
How do I upload my Branch to Git Hub? Do I manually upload each file, one by one, at https://github.com/TurtleShroom/WtWSMS/upload/master ?

**Comment by loup99** [comment]
No, Dropbox is not easier than GitHub, it is only a file sharing-program that doesn't have the same functionalities. But do you know what? I think it will be easier for you to understand by looking at a video: https://www.youtube.com/watch?v=LufnCoPShZE&index=1&list=PLHzZNM2AcKx4aKIv-CyzipEGu944AIJQu&ab_channel=DonnieSantos

**Comment by TurtleShroom** [comment]
@loup99 

I figured it out! Thank you so much!

**Comment by TurtleShroom** [comment]
You can mark this Issue as closed. I've started up the Branch and Pull Request.

You can find the branch at https://github.com/TurtleShroom/WtWSMS .
You can find the Pull Request at https://github.com/loup99/WtWSMS/pull/148 .
