### ISSUE TITLE
Building question

### ISSUE THREAD

**Issue by LeGrandiSlayer** [loup99/WtWSMS#153]
So, I had to take a break from developing the buildings and cultural bonuses when I completely lost the files for them, but that's a story for another time. For now, I am back, and am redoing the buildings from scratch.

I do have a few questions about them however;
1. What is the mod's timeline focus? Last time I played, it was possible(and discussed) that you could play from 475 to CK2's vanilla end date, is this still true?
2. How to handle Roman infrastructure. Much of Rome's infrastructure wasn't really destroyed, so I was thinking that Roman buildings are tied to the province's culture, instead of the holder's culture.
3. Should certain cultures have different levy compositions?

**Comment by loup99** [comment]
Great! That will really help and add to the flavour of the mod. Could you integrate something like this: http://forum.paradoxplaza.com/forum/index.php?threads/building-system-thread.831996/#post-18795307 ?

1. Yes, but our main interest will be 395 - 800 (now it is more 476 - 600). But you are right on 476 - 1453.
2. Makes sense, but even if the culture did switch it would only be a gradual transition as time went on. 
3. I think that would be good. I'm not too much of an expert on levy compositions though, so you probably know more than I do.

**Comment by LeGrandiSlayer** [comment]
While I like the idea, the destruction of buildings should really only happen if the province is either looted or holds Roman buildings, and while I do like the idea, I am not a great event coder myself, which could make the progress painful and slow, but if it must be done, I'll give it a shot.

**Comment by loup99** [comment]
I think the idea that buildings need to be actively maintained depending on the situation is a good idea. Even if the province is not directly touched by the war, it needs to be maintained, and constant warfare did cause the desurbanisation that happened. As for event coding, you can always try it if you want to, and I could try to help you if you encounter any issues.
