### ISSUE TITLE
Some Suggestions and Problems

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#154]
Good evening.

I am writing to propose several tweaks and improvements to make the Mod more dynamic and to reduce blobbing, as well as to stop several oddities.
- The Event that changes your children's religion to Hellenic Paganism should prefer to fire on children that are not the heir. Right now, Hellenic Paganism spreads so easily, especially among Christians. I have seen the rulers in the Gaul region (the kingdom with that fox's head) go from Nicene to Hellenic and convert their entire vassalage over in one generation. For some reason, Roman and Byzantine characters randomly and frequently switch to Hellenism, even if it doesn't make sense.
- For some reason, Independence Factions _never_ form in the Byzantine Empire. In the game I am playing right now, the Byzantine Empire has used the Pagan Subjugation CB to gobble up most of modern Germany, most of Scotland, and most of Finland, and are still growing. They suffer revolts every few years, but they _never_ seek independence. I've watched centuries go by, and centuries' worth of revolts, and there was _never_ an Independence Revolt of any kind.
- We need more Migrations, and Migrations should happen more in the late-game stages. According to the code, Migrations end in the 800s AD, but I never see them happen very often in the 700s AD. I only saw one in two hundred years, and, of course, it failed due to the blobbing Byzantines and Visigoths.
- At the start of the game, the Iceland duchy should be a Theocracy, not Tribal or Feudal. Iceland was supposedly settled by Irish Insular monks, so it would make sense for it to be maintained by Theocracies! Perhaps a Duke-tier Theocracy controls one half of the island's provinces, and a Count-tier vassal of said Theocracy controls the other half?
- To my knowledge, the Lucifarian, Ebionite, Insular, and Pelaginian heresies do not have a Convert to This option for pagans. I'm willing to create it myself.
- Is there some way to cause a little pyramid to appear in a random owned province when an Egyptian Pagan character elects to construct a pyramid? I'd love to see a pyramid rise up in Crimea if I converted to Egyptian Paganism.
- Although the tooltip says they can, Egyptian Pagans cannot currently send missionaries to unreformed pagans. Is this a bug or an oversight?
- Mastimani pagans cannot commit human sacrifice, even though the tooltip says they can and do.
- The Scholarch is the [PLATONIAN head of religion](http://www.iep.utm.edu/neoplato/), not the Promethean one. You have those mixed up.
- Monatists are described as ultra-chaste and sexually conservative even by ancient standards. They have significantly lower Fertility. As a result, Monatists should not be able to ever take the Seduction Focus! Also, Monatists should not be able to take the Carousing Focus unless they are Lustful or hold decadent traits like Hedonist and Drunkard. Likewise, you shouldn't be able to seduce a Montanist unless they are Lustful or otherwise decadent.
- The Monarcism heresy of Miaphysites does not have a description. That needs fixing.
- The Luciferian heresy of Nicenes does not have designated deity names. (I'll fix this.)
- There are several mercenary bands run by Muslims in the 400s AD. That needs fixing.
- Assyrian Pagans cannot loot and plunder! What's up with that?
- Assyrian Pagans cannot Subjugate or Invade! What's up with that?
- The Assyrian Empire head of religion cannot grant Invasions! What's up with that?

[Also, I found some more information about the various Christian heresies.](http://www.patristics.co/heresy/)

I tried writing some Events in my personal folder (which you can find under my name), but I failed so humiliatingly that I don't know where to begin. I can't write Events worth crap.

Enjoy
-TURTLESHROOM

**Comment by loup99** [comment]
- We should significantly limit that event yes. It fires often because of a low moral authority. 
- That is not my experience. I have seen the ERE frequently fight with independence factions. But one thing that could be tested is to double unreformed pagan's desire to form those factions, to make it harsh to have large realms with many unreformed pagans. 
- The issue for that is probably more blobs than the Migration itself. 
- I think the point is to have it playable
- Luciferan can be ignored for now, until Enlil is back. For the others, do a search through the files, and if they do not, you can add them based on vanilla examples. 
- You'd have to build it first. :wink: We also don't have any pyramid models available. 
- We will have to bring it up with ACR
- Known issue
- I believe that is WAD
- Maybe they could take it, but with some event maluses? We could let the player choose it, but face the consequences... 
- OK
- OK
- Indeed
- No idea, ask Zusk
- No idea, ask Zusk
- No idea, ask Zusk
- Good, but be aware of any potential bias

I tried to give you some advice.

**Comment by TurtleShroom** [comment]
Okay. I'll try and open another Fork/Pull/Branch section and you can see what I propose.

**Comment by TurtleShroom** [comment]
@loup99 

I've recreated my Branch at https://github.com/loup99/WtWSMS/pull/156 .

I am starting simple, with Localization and religion modifiers, as I listed above. You should be able to commit these immediately, if you so wish.

Also, is there any way I can learn how to write Events? Sadly, I am banned from the Paradox Forums.

I want to create a Decision where you can crown yourself High Priest of the Order of Melchesidec as a Melchesidician and crown yourself Most High Priest of Hypistarianism. It would give you something to do as those bland heresies. Adding in heads of religion is extremely difficult (I tried last time with the Mimamsas), so could you help me with it.

**Comment by loup99** [comment]
You are not banned, you are on probation. Look at the wiki: http://www.ckiiwiki.com/Event_modding There is also a page on decisions. If you start by trying, I can check the code.

**Comment by TurtleShroom** [comment]
@loup99 

No Loup, I am _banned_ until 2017 AD. I've tried logging in before. When I am logged in, I can't even view the Forums due to a programming oversight on the forum's part.

**Comment by loup99** [comment]
Fair enough, we aren't going to discuss that here (will remove this part).

**Comment by xirsoi** [comment]
There is no separate Neoplatonist religion in ACR, Prometheanism serves the purpose and incorporates Neoplatonist themes and ideas. 

Also, I'm not surprised there are an unusual number of conversions happening in WtWSMS. ACR and it's conversion events are designed with Vanilla in mind, which in all it's start dates has far fewer characters eligible for conversion than in this mod. You should definitely tweak things to suit the setting.

**Comment by loup99** [comment]
Given that Romulien worked on the integrations and historical research isn't my domain (Enlil), I haven't paid attention to this. 

The conversion events have been disabled in WtWSMS, we will have to see if some of them come back or not.

**Comment by xirsoi** [comment]
No problem, happy to help. If you have any issues or questions about ACR content, let me know.
