### ISSUE TITLE
Joemit's Legions

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#16]
This is the issue dedicated to the legions and everything related to them. Balancing, tweaking and etc goes into this. It is integrated but not fully complete in the 0.9.3.1 version.

**Comment by loup99** [comment]
For the record, Erik W worked a bit with this: https://github.com/rickinator9/WTWSMS/commit/f9a4d28625db2cb61888a1e9cfcc7f70f96707dd and https://github.com/rickinator9/WTWSMS/commit/b9b9273ba15a7b6fd73f2064fa4b72b6b64cd2c4 . Would be good if you referenced them with a #16, Erik.

**Comment by EWattman** [comment]
Okay, so I was asked by Romulien to summarize what the problems with the Legions are and here it is:

1. If Nepos decides to restore the Dalmatian Legions, they are vassilized by the East. This is because of this line of code: set_defacto_liege = e_byzantium. Now, I don't know what I should replace Byzantium with if I want it to be either the West, East or Soissons.

2. Nepos can restore a Legion in the East that the ERE controls the land for. It is proabably a result of a sloppy potential structure, which is this:

		potential = {
			OR = {
				has_landed_title = e_byzantium
				has_landed_title = e_wre
				has_landed_title = k_soissons
			}
			is_female = no
			prisoner = no
			age = 16
			completely_controls = k_annonaria
			NOT = { has_global_flag = legio_i_annonaria_founded }

**Comment by rquinio** [comment]
Ok !
1. You can replace `set_defacto_liege = e_byzantium` by `set_defacto_liege = ROOT`, so that it is the one taking the decision (ROOT) who vassalizes.

2. This is strange because `completely_controls = k_annonaria` should prevent that.

**Comment by rquinio** [comment]
Actually k_annonaria is in e_italy, so ERE shouldn't control any land for this ?!
I don't reproduce the issue as Nepos in 480, he can only restore:
- Mesopotamian legion: it's a bug in the decision, as d_oshroene isn't a valid duchy, so `completely_controls = d_oshroene` doesn't actually check anything.
- Dalmatian legions: that's normal, it's WRE territory
Hope that helps !

**Comment by EWattman** [comment]
Annonaria was an example

**Comment by rquinio** [comment]
Gathering feedbacks here (in particular https://forum.paradoxplaza.com/forum/index.php?threads/wtwsms-development-version-testing-feedback.847502/page-9#post-19781130):

- Killing of legion owner can be problematic if player or important characters is the owner (not supposed to happen, but...). Safer might be to grant title to a random character and kill that one instead.
- No legions in Britannia (k_england, etc.)
- Legio I Subarrica and Legio I Sicilia potential bugs on decision/events triggers.
- Maybe tweak dissolve conditions (ideally with a generic event rather than 1 per legion)

**Comment by rquinio** [comment]
There's an issue with Emperor Zenon: as Isaurian is not a culture allowed for commanding legions, they dissolve automatically when starting the game.

**Comment by loup99** [comment]
Should Isaurian be? Or should some cultures not disband the legions?

**Comment by EWattman** [comment]
Quote from Wikipedia: "In the 4th century they were still described by Ammianus Marcellinus as the scourge of the neighbouring provinces of Asia Minor, with a major series of raids occurring from AD 404 to 409, including one campaign to eradicate them led by the Eastern Roman general Arbazacius, but they were said to have been effectually subdued in the reign of Justinian I."

Could this be any clearer? The Isaurians are barbarians, its just that they are living inside the Empire. And if it takes almost 600 years just to "subdue them", they aren't perticularly Romanized either.

**Comment by loup99** [comment]
Yes, but should all legions disband on day one?

**Comment by EWattman** [comment]
Think of it as a means to remove the Isaurians from the throne... Otherwise, if he must have them, perhaps we could tie them directly to his character number?

**Comment by loup99** [comment]
I think it is a good way of representing it, BUT, the issue is that if they disband on day one, it will be problematic. So I would prefer them to not be hired by him, but not disbanded, if you see what I mean.

**Comment by EWattman** [comment]
Is there a way of keeping them active without him being able to use them?

**Comment by loup99** [comment]
Yes, should be. Would it be OK if we did that? Do you recommend any specific conditions?

**Comment by rquinio** [comment]
I believe vassalized mercenary companies are hardcoded to be always hire-able by their liege (the allow block in the title is not taken into account at all)

**Comment by loup99** [comment]
Couldn't we make it non-hireable at all, but not disbanded?

**Comment by EWattman** [comment]
But then Zeno would be free to use them at will. And does it really matter if he is Emperor? He is still a member of the most resistant and vicious of Barbarians.

**Comment by ajjr1996** [comment]
rquinio, this is ajjr1996 from the "Witcher Kings" mod. Sorry this is how I must contact you, but it is the only way I could find you! I was wondering if you would be so kind as to contact me on Moddb possibly, or however possible.

- ajjr1996

**Comment by loup99** [comment]
@ajjr1996 Send a PM

**Comment by ajjr1996** [comment]
@loup99 Not sure how to do that, my bad man I didn't mean to jumble stuff up, but he worked on my mod and I need to get a grip on what's all been worked on/ needs worked on.

**Comment by loup99** [comment]
You can do so on the forums, by clicking on the conversation. There is even a forum tutorial thread. Or you just leave a visitor message.

**Comment by ajjr1996** [comment]
I'm trying to figure it out man I've heard of this can you possibly give me some help on how to do so? I sound dumb right now because I've never used Github. I'm just trying to contact this person.

**Comment by loup99** [comment]
Not here, only on the Paradox Plaza Forums

**Comment by ajjr1996** [comment]
is he under the same name?

**Comment by loup99** [comment]
No, he is called "Romulien"

**Comment by ajjr1996** [comment]
Thank you @loup99

**Comment by IhateTrains** [comment]
I think we should improve the potential in legion formation decisions. Right now there is a condition to hold some title in the potential block, e.g. `has_landed_title = k_annonaria`
Replacing it with `any_realm_title = { de_jure_liege_or_above = k_annonaria }` would make the decision visible when you are present in the area and still wouldn't litter the decision screen.

**Comment by loup99** [comment]
Doesn't work in most cases to only do that, since it would change the requirements to create the title. But once the update is done we could consider doing that and adding the title in the allow block.

**Comment by IhateTrains** [comment]
Yes, `has_landed_title = k_annonaria` would go to the allow block.

**Comment by loup99** [comment]
All the planned legions have now been added.
