### ISSUE TITLE
Unused Religions?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#163]
Good afternoon.

I am looking through the files of the Mod and have discovered some very interesting heresies and things that have yet to be implemented in the game.

Namely, I am interested in the Imperator Hellenic Heresy, where the Roman Emperors themselves  are worshipped. That is some darn impressive potential right there. The same goes for the heresies for Reformed Pagans and other features.

Is there are reason they have not yet been implemented? I mean, obviously, the joke religions ("The Great Lie", etc.) are not supposed to be there, but what of the rest?

I'd like to try and install some of the Hellenic and other heresies. Do I have permission to do so?

-TURTLESHROOM

P.S.: @loup99

**Comment by loup99** [comment]
Yes, unused religions are mostly leftovers and remnants from other mod projets/versions.

**Comment by TurtleShroom** [comment]
I want to look into implementing some of the best ones that existed within the proper timeframe into the game itself. For example, I would like to see the Cult of the Roman Emperor itself be instated, and allow a CRE Emperor of a Restored Rome to have flavor events where he worships himself (etc.).

**Comment by loup99** [comment]
The mod already has many unused heresies. Focusing in disabled religions is better done in a submod.
