### ISSUE TITLE
Newest Partch Update

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#167]
Good evening.

I am curious as to the status of the Mod in terms of updating to the newest Reaper's Due (RD) Patch. When should we expect the Mod to be compatible and playable with the new Patch in effect?

More importantly, is there anything I can do to help you make the Mod ready for the newest Patch? I would love to help in any way I can.

-TURTLESHROOM

**Comment by loup99** [comment]
During this week. Nothing you can do at the moment, but if I need help I can tell you.
