### ISSUE TITLE
Hunnic Humor (or, "WE WUZ HUNGZ")

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#168]
![attila castle](https://cloud.githubusercontent.com/assets/17663470/18372283/661bfd0a-7609-11e6-8e18-a7d1febf7e1d.jpg)

Good evening.

I am still attempting to learn how to code Events, and I don't trust myself with this project, but I wanted to get this written down before I forget what I read. Make sure you read the whole thing to understand why I am posting it here of all places.

Apparently, in the 1990s AD, [a cult leader claimed he was Hunnic](http://wayback.archive.org/web/20051029102416/http://www.pestiside.hu/archives/were_here_were_huns_get_used_to_it000102.php) (despite the Hunnic peoples dying out after the Hunnic Empire broke up), that Huns knew how to build pyramids on par with Egypt, and that Hunnic shamans could see into the past. He wasn't the first. Read on.

http://cometogetherarticles.yolasite.com/resources/MapMu.gif

Among their sensational claims:
1. Huns originated in Hawaii, on an Atlantis-style sunken land called Ataisz.
2. Huns, like the RL Polynesians, mastered longboats and sailed west, where they arrived in China and scourged the steppes as in RL.
3. They headed west as in RL and somehow remained in Hungary _after_ the Hunnic Empire collapsed, because the Gepids, Bolghars, and the like didn't assimilate them.
4. There are two hundred thousand "pure" Huns left today.
5. The confederation of tribes that became the Hunnic Empire began in Hawaii, sort of like Israel did.

[There's even a plan for an Attila amusement park.](http://wayback.archive.org/web/20051029101415/http://www.pestiside.hu/archives/attila_scourge_of_god_offered_puny_halfassed_tribute000380.php)

Honestly, it's the best thing I've read on that subject since I was introduced to the American black's Afrocentric "WE WUZ KANGS" (the "Hoteps") movement to defraud Egypt of its culture. Get a load of it [here](http://cometogetherarticles.yolasite.com/the-arvisuras.php). 

The entire cult was spawned by a man named Paál Zoltán and his occultist friend, "Shaman" Szalaváré Tura. The guy in the first article simply picked up on it.

---

So here's my idea.

The Lunatic Events are hilarious. From inscribing stories about fighting crime on runes to looking for love in all the wrong rose bushes, we always get laughs time after time when you have the Lunatic Trait.

So I was thinking: there needs to be more lunacy in this world.

I imagined that a pagan Lunatic, of Hunnic culture, that controls the Hunnic Empire, should get insane visions based on the lines of these. He fantasizes building [THIS](http://wayback.archive.org/web/20051029101415im_/http://www.pestiside.hu/archives/attila%20castle.jpg) and doing all sorts of whacky things to prove he is a worthy successor to the one and only Scourge of God.

The Event would be a a major Event pop-up akin to the military advances or the immortality quest (the one with the fancy letters at the start). It explains how your insane character has had bizzare dreams and "visions" that his gods showed him. He now "knows" the "origins" of his people and claim that they came from beyond the coasts of Cathay, and so on and so forth as I mentioned.

Once the Event fires, you get a special Decision to build a crazy palace based on that image at great cost. Doing it gives a permanent boost to your current capital (that stays even if you migrate or leave it) and adds a new Holding with a custom Building. 

Now, I don't except some OP change to come to this, but I still think that would be pretty darn cool and rather hilarious. After all, I can already convert my Hunnic Empire to Egyptian Paganism and build a pyramid. Wouldn't it be fun to have a crazed Hun create the myths I reiterated in my post?

In the name of humor,
-TURTLESHROOM

P.S.: Glob, I want a copy of that book in English.

**Comment by loup99** [comment]
Yes, sounds good. But I wouldn't include a decision, simply an event.

**Comment by TurtleShroom** [comment]
@EmperorEnlil 

All right. Let us begin. Here is the outline I came up with.

--------------

![hungz](https://cloud.githubusercontent.com/assets/17663470/18449187/43288ad4-78fc-11e6-893e-65bac2cb6001.png)

![hungz](https://cloud.githubusercontent.com/assets/17663470/18453956/b269d264-790f-11e6-9613-ef6de16e83c6.png)

**Comment by MaelgwnGwynedd** [comment]
Wow so productive

**Comment by EmperorEnlil** [comment]
This is a rather exciting event chain. And do you know the best part? A lot of this can also be used to make "realer" events. To be quite honest I'm rather excited to see what the person who finds it first will post about.  I'd also like to discuss on whatever appropriate thread about your thoughts on Vandal flavor though.

**Comment by TurtleShroom** [comment]
Remember, this event chain is _pure conjecture_. NONE of this has ANY basis in reality, except in the delusions of a man and his "shaman" buddy tripping dope behind a Magyar barracks in the 1940s AD. That's what makes it so fun, but I'd reccomend we set it so that if Fantasy Events are disabled

**Comment by TurtleShroom** [comment]
@EmperorEnlil 

I had a different epiphany concerning actual Hunnish customes, however. The Huns famously **distorted their skulls at birth** . Surprisingly, so did the Gepids and Alans!

Check this out: http://pre13.deviantart.net/bb53/th/pre/f/2011/030/c/f/hunnic_man_by_el_lagarto-d383ads.jpg

-and see here at "[What Did the Huns Look Like](http://theminiaturespage.com/boards/msg.mv?id=295611)"!

What I propose is a flavor Event that fires for Gepid, Alan, and Hunnish kids.

Basically, something like this:
(Picture shown}
"KID'S NAME has been born to FULL TITLE FULL NAME and his wife FIRST/LAST NAME.
Per the traditions of CULTURE, we can bind HIS/HER skull to enlongate it while HIS/HER bones are not formed.
This practice is considered to be the pinnacle of beauty amongst our people, but other nations may not like it so much..."

OPTION 1: You're going to look so good!
OPTION 2: On second though, HIGH GOD created him just fine.

This activates a Modifier called "Artificial Cranial Deformation", reading "this infant is undergoing a ritual elongation of his skull". (It'd use the "Out of Patience" modifer image.)

Several years later, the event concludes saying:
"KID'S NAME's skull has finally hardened, and the cloth can be unbound from his head."

OPTION 1: You look incredible, KID'S NAME!

------

We could even have a reaction for playing a kid if the parent or guardian did it to him.

"My RELATION brought me before a mirror this morning. He told me it was finally time to remove that strange hat I'd been wearing since I was born. He says I'll look so much better without it.
He takes off the cloth and I stare at my reflection. My forehead must be a hand's length long!

I... I..."

OPTION 1: I LOOK _**SO AWESOME**_! (chance of gaining Proud or Haughty trait)

OPTION 2: I LOOK **_HIDEOUS_**! Why did you do this to me?! (adds Stressed, chance of Humble and slight chance of Depressed)

OPTION 3: I look just like you, RELATION! (increases opinion of the person that did the binding, chance of becoming Friends with person)

------

Then you get the Trait "ENLONGATED SKULL".
"This character's skull is unnaturally tall, a product of HIS/HER culture's binding of infant heads. It is a mark of beauty amongst those who did it"

It decreases Sex Appeal for everyone that is not Alan, Gepid, or Hunnish cultured and greatly increases it for those three cultures. It also grants monthly Prestige.

Unlike foot binding, there are no health drawbacks to this, interestingly enough.

-----

I may be able to code this one myself after studying the Zoroastrian Event chain. All I need to do is figure out how to get it to fire about three days after birth.

**Comment by EmperorEnlil** [comment]
I'm very aware of this! Earlier I was petitioning on the dev forum that we should try to get Hepthalite portraits. Khingila is the best example, but they took skull elongation to a whole new level. It's definitely a good way to model hunnish flavor. Thuringians should also be able to do it, just much rarely.

**Comment by TurtleShroom** [comment]
I'll take on the skull binding Events once someone implements my current batch of changes.

**Comment by IhateTrains** [comment]
@loup99 can we close this?

**Comment by loup99** [comment]
Yes, closing it
