### ISSUE TITLE
Undo my edits

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#170]
Please revert all my edits. I'm not interested in being associated with this mod, or my work being used.

**Comment by loup99** [comment]
OK, that will be done as you request. All characters you added will be removed, and history modified.

**Comment by MaelgwnGwynedd** [comment]
Thank you.

**Comment by loup99** [comment]
You are welcome.

**Comment by MaelgwnGwynedd** [comment]
Good luck, you'll need it if this is how you treat people who try and help you. Goodbye, I hope we don't meet again.

**Comment by loup99** [comment]
Good luck to yourself, and thank you for the help you did provide once again. By tomorrow your work will be undone.

**Comment by MaelgwnGwynedd** [comment]
I can only suggest you practice what the game says.

http://i.imgur.com/O6zbiJ7.jpg

**Comment by loup99** [comment]
Done as of commit 233a3860c3560a9cc5dc35bfb6721d57c54a2017

**Comment by TurtleShroom** [comment]
This is a selfish and disgusting request by @MaelgwnGwynedd and it should not have been honored.
