### ISSUE TITLE
Why did you betray me?

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#171]
What was the point of reporting me on the forum? I don't see much, do some idiotic online words transcend empathy?

**Comment by MaelgwnGwynedd** [comment]
This is a genuine question.

**Comment by loup99** [comment]
I believe this matter has already been extensively discussed and treated. But just to clarify: WtWSMS is released on the Paradox Interactive forums and thus the forum rules apply. We are not going to go over them, given that it isn't the WtWSMS team that decides them.
