### ISSUE TITLE
You didn't answer my question.

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#172]
Would you rather I help you or uphold some forum's dumb rules?

**Comment by MaelgwnGwynedd** [comment]
And don't close this saying YOU think it's been discussed enough. I certainly don't.

**Comment by TurtleShroom** [comment]
WE'VE GONE THROUGH THIS ALREADY.

YOU ARE _NOT_ BANNED FROM HELPING ON THIS MOD ON THE GITHUB. YOU _ARE_ BANNED FROM HELPING ON THIS MOD AT THE PARADOX FORUMS.

YOU ARE FREE TO HELP HERE, BUT SHUT YOUR TRAP ABOUT LOUP'S REPORT ON THE FORUMS.

WHY CAN'T YOU GET THIS THROUGH YOUR DENSE SKULL?

**Comment by MaelgwnGwynedd** [comment]
Wow, calm down. 

Well, I find it very, very odd behaviour to report someone like that. It's like the annoying kid at school who tells on his friends and then is surprised he gets beat up afterwards.

**Comment by loup99** [comment]
Maelgwyn, I have explained that I think it is unfortunate that you disagree on the way the rules of the Paradox Forums are written and the mod being on the forums. But I have already explained that isn't going to change. No threats or repeated questions will change that either.
