### ISSUE TITLE
Help Files/Manuals for Mod!

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#175]
![untitled](https://butt.githubusercontent.com/assets/17663470/18896916/aff8a5ba-84f3-11e6-90db-41fc95738659.png)

Good evening.

Tonight, I am going to unveil my biggest project yet.

This Mod is a fully comprehensive, immersive work that changes the game across the board. It has massive amounts of new features.

-but do you know what it's missing?
It is missing a help file and manual. A Readme file alone is not good enough for a Mod of this quality.

Everyone knows what a Readme file is. It's a basic text document explaining the installation procedures of the program and content in question. -but not everyone is old enough to remember Help Files.

For over twenty years, programs and content have come with a Help File to illustrate the usage of the program, the installation procedure, and the features of the program. Help Files allow for pictures, tooltips, links, new windows, and searchable indicies to fully immerse oneself in an easy to use tutorial.

What I want to do for this Mod is simple. I want to create a formal manual using the classic Winhelp standard. I want to compile a detailed Help File, with chapters on all the features and easy instruction guidelines.

This will take weeks, if not months to complete, but it will be worth it in the end.

Let me note one last thing: Windows Seven and Windows Ten do not come with Winhelp installed by default. You must download an OFFICIAL MICROSOFT FILE _that is less than one megabyte_ to view Winhelp programs. Microsoft allows their patches to be freely distributed on "Genuine" Windows systems, so for the purposes of the manual, the two MSI Update Installers from Microsoft should be added into the Mod's support/documentation folder. The two files add the Microsoft Winhelp feature to a computer. One is for thirty two bit computers, and the other is for sixty four bit computers.

I announced all of this because I wanted to explain what you will be seeing in the commitments I make in the future. A new folder called "winhelp" will be committed with several folders containing two files. Each folder contains the two official Microsoft Update Installers (end users choose one based on their bit-architecture) for their OS. The other is a Readme to explain what is to be done.

The end result is a flashy, impressive, detailed catalog of everything that makes the Mod special and every feature that players can anticipate.

The total space that everything here combined will take up is less than ten, and perhaps less than five, megabytes.

I look forward to writing the ultimate manual and documentation for the ultimate CK2 Mod. Not even the "Game of Thrones" Mod has this level of a manual!!

-TURTLESHROOM

---

@loup99 / @EmperorEnlil

**Comment by loup99** [comment]
While it is great to hear that you are interested in making the mod more accesible, we can't distribute some of the files you mention for copyright reasons and it does sound a bit complicated to have to install additional files. My advice is therefore to continue building on our wiki page, so that it can be the catalogue you refer to. Furthermore, I do think that it is better to not start on any project of this size while being on a beta version.

**Comment by TurtleShroom** [comment]
That's okay, we don't have to distribute the installers! I already planned for that scenario and can adjust for it accordingly. All of the installers are present in one place online, so it's no problem.

**Comment by loup99** [comment]
So what are we going to do then? As we aren't going to distribute the installers, it is fairly likely that not many will do the additional effort of installing a third party application, when our wiki with more information that anyone can edit is going to be as integrated as possible.

**Comment by TurtleShroom** [comment]
It's not a third-party installer. It is a _**first party**_ installer officially given by _Microsoft_. You can't get more official than that. Installation of the Help system requires no technical know-how because Microsoft does it all automatically. It's effortless.

As for Windows Ten, I understand that those people may not get to see it, but there are still hundreds of millions of people who did not upgrade from Windows Seven.
There _is_ a way to install it on Windows Ten, but it takes a LOT of effort. I included it for the few people who would be interested in it.

This is the way I see it: including the help file requires no effort on your part. It's a personal, pet project of mine that I have always dreamed of contributing to. I adored Help Files as a kid and always wanted to make my own.  If you would include it in your Mod, it would mean the world to me. It's not about getting the world to see it and praise me. It's about me doing something I always wanted to do for the best CK2 Mod out there.

Besides, it does have a major purpose: for those who play the Mod offline, they can access this whereever they go. Sicne they need to be online to get the Mod, they can get the Help File system at the same time.

More importantly, there are literally hundreds of thousands of programs of all stripes that use the Winhelp system. Many old/legacy programs have help files. Winhelp allows them to view it. It'd save them time if they ever need an older program.

Diversifying the manuals only benefits everyone. The Help File is my personal project, so you only need to implement it for me.

**Comment by loup99** [comment]
No, it a third-party installer for those using WtWSMS. 

I'm absolutely not opposed to including it, I just wanted to warn you about this maybe not being the most productive alternative.  And I won't be able to help you as I'm only using Windows 10.

**Comment by TurtleShroom** [comment]
@loup99 

That's quite all right. You won't need to help me compile the Help File. I'm doing that myself. When the Mod is taken out of beta and hits Version 1.0, I will have many questions and request lists and summaries of the greatest features. All you need to do is give me information I request or point me to where I can find it. I will take care of everything else.

**Comment by Moopli** [comment]
Pray tell, what could you do for us linux users?
Moreover, you can do much more with some static HTML/CSS pages. It would be even easier to update the manual files, by using github pages so anyone with github access can update the manual by editing markdown files and seeing the changes once they push.

Local copies can be built using Jekyll, for a workflow that doesn't require a push to see the result, and for a local set of static files for a manual that can be provided with/alongside the mod.

**Comment by TurtleShroom** [comment]
@Moopli 

This manual is my pet project and one of my oldest computer-related dreams. All I ask is that the WTWSMS team allow it and the "WINHELP" folder and its small files to exist.

The Help File will not be developed until WTWSMS formally reaches V1.0 . On that day, I will begin my research and will ask many questions to gather a comprehensive manual.

After the Help File is completed, THEN I will entertain further manuals for the Linux and Macintosh systems.

Until then, see if Help Files can be opened by putting Winhelp on Wine or a Virtual Machine.
Heck, there may be a third-party console (or even freeware!) that can read those files.

The extension you'll need to look for is ".HLP". 

The ".HLP" icon can't be missed: it's an adorable purple book with a yellow question mark.

**Comment by loup99** [comment]
Turtleshroom, I won't be able to give you all answers before the WtWSMS wiki page is considered completed, so that everyone can access it. So it will not be after 1.0.0, it will be later.

**Comment by TurtleShroom** [comment]
That's fine. You can answer the questions you know, and I can research the ones I don't!
