### ISSUE TITLE
Localisation encoding issue

### ISSUE THREAD

**Issue by NicolasGrosjean** [loup99/WtWSMS#177]
The localisation files are usually encoded in ANSI.
But some of the localisation files have an UTF-8 w/o BOM encoding, and with this, all the accents are broken. It is a problem for the French translation.
Is there any reason why some files are in UTF-8 w/o BOM?
If no, can I convert all the localisation files in ANSI?
In Git, it will change only the accent (and other special) characters not the entire files. So this change will be less problematic for merging than the French translation.

For information, the following list is the exhaustive list of the localisation files with UTF-8 w/o BOM encoding.
- 00_CK2Plus_override.csv
- ACR_epic_blood.csv
- ACR_promethean_events.csv
- ACR_titan_events.csv
- CK2Plus_tributary_events.csv
- LI_decisions.csv
- LI_relf_localisation.csv
- MZ.csv
- MZ_Zhayedan.csv
- patrons_cel_localisation.csv
- VIET_bitter.csv
- VIET_death.csv
- VIET_hints.csv
- VIET_historical.csv
- VIET_jordarkelf.csv
- VIET_marriage.csv
- VIET_meltingpot_events.csv
- VIET_modifiers.csv
- VIET_narrative.csv
- VIET_nicknames.csv
- VIET_ordepchains.csv
- VIET_Regency_localisations.csv
- VIET_Special_Events.csv
- WikipediaLinks.csv
- **WtWSMS_events.csv**
- **WtWSMS_traits.csv**
- zz_want_to_be_sure_im_the_last_file_the_bloody_thing_reads_exclamationmark_LI.csv

**Comment by loup99** [comment]
Absolutely! There is no reason behind it, and it shouldn't be in that encoding.
