### ISSUE TITLE
Make Religious Conversion Overhaul Optional

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#178]
Good morning.

The decision to remove the "demand religious conversion" decisions and weaken the conversion rates of others was a horrible idea to me. What's worse, I can't even use the Demand Religious Conversion button!

I'm not even sure how to use these decisions any more. In a recent play through, I wasn't even sure if the button to order a vassal to convert was there.

What I propose is that this facet of the Mod, like the don't changes, should be optional. It's a controversial decision by far.

-TURTLESHROOM

**Comment by loup99** [comment]
Good afternoon,
The decision is still present, you can look into the files for conditions and effects. The conversion rates are based upon religious mentality. I will probably update the wiki to have more information.

Concerning the suggestion to make it optional, I won't personally do it as it requires a lot of effort to maintain.

**Comment by TurtleShroom** [comment]
What if it was programmed through the Rules system?

Like, you could set a "Religious System" Rule, where "Dynamic" implements the current system you added, while "Traditional" uses the Vanilla system and the "Convert to X" Decision. That way, everyone goes away happy.

If I could figure out how Rules modding works, I'd do it myself.

**Comment by loup99** [comment]
The rules do not ease the amount of maintenance though. Unless an experienced modder in the team had an urge to make them optional (rather than improving the existing system or discussing the issue with it), I would argue against it and recommend making a sub-mod.

**Comment by TurtleShroom** [comment]
Okay.

-but one thing that bugs me is how restricted the Convert to Spouse Decision (for example) is. What if I am a pagan and I capture a bride to convert, but the game doesn't let me? The code looks as if certain religions deny that outright. Why can't I convert to the religious beliefs of my non-pagan spouse? How is her pillow talk less effective? Even if the religion does not traditionally prolestyze, why wouldn't she talk about the faith to her husband?

Likewise, why can't I, as a player, send my Court Chaplain to spread my religion if the religion is traditionally not one to prolestyze? I, as a player ,should be allowed to do that. Your religious categories should govern the AI's choices, not the player.

**Comment by loup99** [comment]
- Yes, non-proselyte can not convert non-ancestral characters. I noticed that some things were not working as intended and some changes are planned so I will modify them.
- That is the same restriction as vanilla on unreformed pagans, and a question of historical plausibility. Non-reformed pagan religions shouldn't convert others.

**Comment by TurtleShroom** [comment]
Okay, that's good to hear. I knew that unreformed pagans couldn't (and would not) convert, as it should be. I was just afraid that this would hamper the player of a reformed pagan.

Under this new system, where are the buttons to demand vassal conversion and for unreformed pagans to convert to your spouse's religion? Likewise, why isn't that feature available for all religions that are not pagan?

**Comment by loup99** [comment]
All the buttons are available as targeted decisions.

**Comment by TurtleShroom** [comment]
Is that on the right click menu of a character?

**Comment by loup99** [comment]
Yes.
