### ISSUE TITLE
Why Are Promeathean and Titanic Pagans Gone?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#179]
Good afternoon.

I do not understand the basis or justfication for removing Promeatheanism or Titanic Paganism. The only issue I had with their presence was that the Neoplatonist was incorrectly named the Philosophos (which is incorrect, Neoplatonism used Scholarch and Prometheans used Philosophos).

The religions gave more dynamics to the Hellenic group and should not have been taken out. This is especially true because the Prometheans, while similar to Neoplatonism, embodied unique and exciting features that should belong in the Mod. Prometheans, for example, get the bonus to intelligence that Neoplatonists get, but they also get a pro-woman stance. Titanic Pagans, likewise, get a boost to aggression, making their presence more interesting.

There was no good reason to remove these religions unless they were ahistorical.'

That said, we could just integrate Prometheanism wholly into Neoplatonism, combining the religions' features into one. [Plato himself believed that women were equals and should be given a chance to govern.](http://schoolworkhelper.net/plato%E2%80%99s-views-of-gender-equality/) Perhaps Neoplatonism could incorporate and worship Prometheus, since he was a giver of knowledge?

-TURTLESHROOM

**Comment by loup99** [comment]
As you guessed, they were ahistorical.

**Comment by TurtleShroom** [comment]
Why do you believe that those religions were ahistorical in this time period? Is there anything you can point me to in order for me to understand it?

If so, then okay. I will do everything I can to help. We should start by incorporating the Promethean Events and flavor into Neoplatonism, a well as the gender equality I showed you in those links.

**Comment by loup99** [comment]
It is not about believing, it is knowing that they are are ahistorical because the ACR creator said it.

**Comment by TurtleShroom** [comment]
What did the ACR creator base this on?
