### ISSUE TITLE
Briton High Poets Are Broken

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#180]
Good evening.

The High Poet Minor Title and Events are broken. Every time I appoint a High Poet, he disappears from the Minor Title list the next day. Clicking the decision to spawn a new High Poet brought me a GRIOT instead. I have absolutely no idea what's going on. I haven't changed any of those Events or modded anything concerning the High Poets.

Are you experiencing an issue like this, too?

-TURTLESHROOM

**Comment by loup99** [comment]
I will see if I can reproduce it.

**Comment by TurtleShroom** [comment]
Here, I'll upload the saved game.

[Iron_Man_Guent.zip](https://github.com/loup99/WtWSMS/files/571938/Iron_Man_Guent.zip)

**Comment by TurtleShroom** [comment]
Okay, so I tried it a second time, this time as a Skiirian King of Italy. The exact same issue happened. This bug is game-wide.

**Comment by loup99** [comment]
What? You shouldn't have access to them at all?

**Comment by TurtleShroom** [comment]
My point exactly: I have a High Poet slot open as a Central African Priscillian governing the Republic of Mauri. 
(I also have a Court Griot slot for some reason, but I cannot take the Decision to spawn a Griot like a Garamantes character can.)

**Comment by loup99** [comment]
Issue solved as of commit  a2d3f70
