### ISSUE TITLE
Deity Names not Showing as Priscillian

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#185]
Good afternoon.

I am currently experiencing an odd glitch in which all "Reapers' Due" Events that mention a deity's name is simply not showing up. It occasionally happens the same in As the RD files are the biggest uses of deity names, it's really a pain to see them not showing up. I have reproduced this error consistently in the game by playing as a Priscillian, which is odd, because its deity names are in the exact same format as everything else.

As we use the Vanilla Events for RD and Physician operations (with a few variations), I'm not sure what has gone wrong.

It goes like this:
![glitch](https://cloud.githubusercontent.com/assets/17663470/20726216/84cbfef2-b642-11e6-96d2-21d5fcb386ba.png)

I have absolutely no idea why it's happening, but I can't seem to fix it. Are any of you dealing with this, too?

-TURTLESHROOM

**Comment by loup99** [comment]
Must be an issue with the Priscillian deities specifically.
