### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#186]
I'd still really like to help with this. Would it not be possible to create a forum specifically for the mod? Or perhaps a Discord server, which is like a chat room but would allow us to do some pretty amazing things. I'd like to make this work, but I really can't help properly without the forum. Hope you understand and hope we can discuss this.

Cheers,
Maelgwn

**Comment by loup99** [comment]
I can say that there is not going to be any forum specifically for the mod, as it is discouraged by Paradox, and we already have both GitHub and our forum, with it being hard enough to assemble everyone in one place. Steam was one alternative, but the group is better. Suggestions and issues here are welcome though, as long as it remains in relation to the mod.

**Comment by MaelgwnGwynedd** [comment]
I can't help if I can't use the forum. Discord is better than steam and allows filesharing.

**Comment by MaelgwnGwynedd** [comment]
Why would it be discouraged by Paradox?

**Comment by loup99** [comment]
If you want to contribute with suggestions and discuss the mod, it can be done here on GitHub. I know Discord is something other mod teams have used, however given that everyone was present on Paradox at the moment it is more convenient to use that. We also have a lot of ressources and material on the forum. If it is discouraged it is because Paradox prefers the activity to be on the forums.

**Comment by loup99** [comment]
Concerning the mod being hosted here, it is allowed by Paradox, as long as this is not the place for downloads, isn't linked, isn't used as a forum and is only for developers.

**Comment by MaelgwnGwynedd** [comment]
I'm not interested in suggesting, I'm interested in adding characters and kingdoms.

**Comment by loup99** [comment]
Concerning people not being on the forums, Turtleshroom isn't because of reasons and Enlil isn't always because of being busy. However it is precisely so that Enlil and others can be a part of the discussion that we use the forum, as all developers use it outside the mod too. That said I'm not opposed to privately or separately discussing on Discord if necessary, but it won't be the forum of development.

As for adding characters and kingdoms, if you wanted to continue on the work you did previously it unfortunately can't be modified as it was reverted upon your request. Files have changed since then, and there were some issues, which I solved but then removed everything as it was your wish.

**Comment by MaelgwnGwynedd** [comment]
In any case the files were a bit odd, and I didn't get too far. I've restarted adding characters.

**Comment by loup99** [comment]
Also, I want to make it clear, as you may understand, the previous conflicts do impose some guidelines. No stance has changed since last time we discussed, and it isn't something that will be discussed. And as I don't want to end up distributing work which you don't want to be distributed, it is important that there is an understanding on that matter.

**Comment by MaelgwnGwynedd** [comment]
BRITONS TO ADD:
120000001 = {
	name="Iestyn" 
	# Iestyn ap Geraint Llyngesoc 
	dynasty=1042292
	religion="insular"
	culture="romano_british"
	father=159440
	mother= 159753
	464.1.15={
		birth="464.1.15"
	}
	514.1.1={
		death="514.1.1"
		give_nickname=nick_the_saint
	}
}
120000002 = {
	name="Breaca" 
	# Breaca ferch Geraint Llyngesoc 
	dynasty=1042292
	female=yes
	religion="insular"
	culture="romano_british"
	father=159440
	mother= 159753
	466.1.15={
		birth="466.1.15"
	}
	514.1.1={
		death="514.1.1"
		give_nickname=nick_the_saint

	}
}
120000003 = {
	name="Cyngar" 
	# Cyngar ap Geraint Llyngesoc 
	dynasty=1042292
	religion="insular"
	culture="romano_british"
	father=159440
	mother= 159753
	468.1.15={
		birth="468.1.15"
	}
	550.11.7={
		death="550.11.7"
		give_nickname=nick_the_saint
	}
}
120000004 = {
	name="Selyfan" 
	# Selyfan ap Geraint Llyngesoc 
	dynasty=1042292
	religion="insular"
	culture="romano_british"
	father=159440
	mother= 159753
	472.1.15={
		birth="472.1.15"
	}
	514.1.1={
		death="514.1.1"
		give_nickname=nick_the_saint
	}
}
120000009 = {
	name="Rhywyrch" 
	# Rhywyrch 
	dynasty=
	religion="insular"
	culture="romano_british"
	father=
	.1.15={
		birth=".1.15"
	}
	.1.1={
		death=".1.1"
	}
}

SAXONS TO ADD (It would be best to move Aelle to the Saxons.txt, he's in Britons.txt right now. I also suggest making him much older (here you have him invading Britain as a young teenager) and die in 514 which is the more likely dating based on the Saxon texts)
5 = {
	name="Ælle" # Ælle of Sussex
	dynasty=1042370
	martial=9
	diplomacy=6
	intrigue=5
	stewardship=5
	religion="germanic_pagan"
	culture="old_saxon"
	trait="brave"
	trait="ambitious"
	trait="proud"
	trait="tough_soldier"
	453.1.15={
		birth="453.1.15"
	}
	467.1.1 = {
		# The Coming of the Saxons
		effect = {
			spawn_unit = {
				province = 25 # Sussex
				owner = ROOT
				leader = ROOT
				match_character = ROOT
				match_mult = 0.5
				attrition = 0.5
			}
			create_character = {
				random_traits = yes
				dynasty = random
				religion = ROOT
				culture = ROOT
				female = no
				age = 23
				attributes = {
					martial = 6
				}
				trait = skilled_tactician
			}
			new_character = {
				spawn_unit = {
					province = 25 # Sussex
					owner = ROOT
					leader = THIS
					match_character = ROOT
					match_mult = 0.5
					attrition = 0.5
				}
			}
			create_character = {
				random_traits = yes
				dynasty = random
				religion = ROOT
				culture = ROOT
				female = no
				age = 27
				attributes = {
					martial = 6
				}
				trait = skilled_tactician
			}
			new_character = {
				spawn_unit = {
					province = 25 # Sussex
					owner = ROOT
					leader = THIS
					match_character = ROOT
					match_mult = 0.5
					attrition = 0.5
				}
			}
		}
	}
	512.1.1={
		death="512.1.1"
	}
}
120000005 = {
	name="Cissa" 
	# Cissa Ælling 
	dynasty=1042370
	religion="germanic_pagan"
	culture="old_saxon"
	father=5
	467.1.15={
		birth="467.1.15"
	}
	514.1.1={
		death="514.1.1"
	}
}
120000006 = {
	name="Wlencing" 
	# Wlencing Ælling 
	dynasty=1042370
	religion="germanic_pagan"
	culture="old_saxon"
	father=5
	469.1.15={
		birth="469.1.15"
	}
	514.1.1={
		death="514.1.1"
	}
}
120000007 = {
	name="Cymen" 
	# Cymen Ælling 
	dynasty=1042370
	religion="germanic_pagan"
	culture="old_saxon"
	father=5
	471.1.15={
		birth="471.1.15"
	}
	514.1.1={
		death="514.1.1"
	}
}
120000008 = {
	name="Aelhilda" 
	# Aelhilda Cissing 
	dynasty=1042370
        female=yes
	religion="germanic_pagan"
	culture="old_saxon"
	father=120000005
	508.1.15={
		birth="508.1.15"
	}
	560.1.1={
		death="560.1.1"
	}
}
120000010 = {
	name="Ricwulf" 
	# Ricwulf Rhywyrching 
	dynasty=1042370
	religion="germanic_pagan"
	culture="old_saxon"
	father=120000009
        mother=120000008
	508.1.15={
		birth="508.1.15"
	}
	514.1.1={
		death="514.1.1"
	}
}
120000011 = {
	name="Ricceol" 
	# Ricceol Rhywyrching
	dynasty=1042370
	religion="germanic_pagan"
	culture="old_saxon"
	father=120000009
        mother=120000008
	.1.15={
		birth=".1.15"
	}
	.1.1={
		death=".1.1"
	}
}


Rhywyrch, Ricwulf and Ricceol's dates need to be discussed, as does Rhywyrch's identity (whether we make him his own person or, as some historians have proposed, identify him as one of the Llywarchs).

**Comment by MaelgwnGwynedd** [comment]
"Also, I want to make it clear, as you may understand, the previous conflicts do impose some guidelines. No stance has changed since last time we discussed, and it isn't something that will be discussed. And as I don't want to end up distributing work which you don't want to be distributed, it is important that there is an understanding on that matter."

I don't even know what you're talking about. If you don't want to talk about something, don't talk about it.

**Comment by MaelgwnGwynedd** [comment]
Also, I'm not allowed to add to the project.

**Comment by loup99** [comment]
That is because we use the issue/pull request structure which allows for better reviewing and communication.

**Comment by MaelgwnGwynedd** [comment]
No, I can't do that. That's what I meant.

**Comment by loup99** [comment]
You can, you just need to have your own fork and open a pull request.

**Comment by MaelgwnGwynedd** [comment]
I can assure you that I cannot.

**Comment by loup99** [comment]
If you can't then I advice you to either give me more information on what you can't do (is any option greyed out, does it tell you anything when you try?) or to look around if others have similar issues with GitHub.

**Comment by MaelgwnGwynedd** [comment]
It tells me that I can't push my changes. I can't see any new changes
either, they're all three months old.

**Comment by loup99** [comment]
https://help.github.com/articles/fork-a-repo/

**Comment by MaelgwnGwynedd** [comment]
Still can't.

**Comment by loup99** [comment]
After following the instructions? No idea then. Never happened before, and given the little I know I can't help you.

**Comment by MaelgwnGwynedd** [comment]
Well, you've not understood the problem in the first place. I didn't follow the instructions since that's not the problem.

**Comment by MaelgwnGwynedd** [comment]
![image](https://cloud.githubusercontent.com/assets/21295761/21074898/0de7c87c-bf05-11e6-98a8-a67eb54bd736.png)

**Comment by loup99** [comment]
Your screenshot proves me right: you are on the master branch. You should fork the master here on the web, so that you can have your branch on your client.

**Comment by MaelgwnGwynedd** [comment]
It is an issue, I don't have the latest files.

**Comment by MaelgwnGwynedd** [comment]
I have "forked" it now. How do I "suggest" changes to the master branch?

**Comment by MaelgwnGwynedd** [comment]
I can't even sync my own fork.

**Comment by loup99** [comment]
How so?

**Comment by MaelgwnGwynedd** [comment]
If I knew I wouldn't be having any issues. This is such an idiotically complex system.

**Comment by loup99** [comment]
To be fair, I don't see the complexity in it now that I'm familiar with it. But could you provide another screenshot?

**Comment by MaelgwnGwynedd** [comment]
I've changed several things. And please try and see it from my point of view, rather than posting just to say you're right when you hadn't told me to fork it...

![image](https://cloud.githubusercontent.com/assets/21295761/21075532/d7617a7c-bf14-11e6-8e52-c3432eeb9312.png)

**Comment by MaelgwnGwynedd** [comment]
Nevermind, at this point, since I'm working with a fork, I'll just add things to the git folder directly and copy them into my local mod folder whenever I need to test them out.
