### ISSUE TITLE
Hengest

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#188]
Do we accept that Hengest is the same Hengest mentioned in the Finnsburg fragment and in Beowulf? If we do, that would make him a great friend of the Hocing Danes. I'll try and explain it briefly:

He was a man-at-arms of the Danish King Hnaef Hocing, who died at the battle of Finnsburg. Hengest signed a peace treaty since they were going to lose the battle, but later Rains of Castamere'd every single Frisian at Finnsburg. He was clearly a great friend of the Danes.

I think that, because of this likely link with the Danes and Frisians, people playing as the Saxons under Hengest or Hengest himself should be given some sort of option to recruit people from the Continent to come and help them, as an intrigue event. Hengest did not have to do this in real life, but as we all know the game can "mutate" quite rapidly. In my own games trying out the Britons and Saxons, the Saxons almost always lose. And taking into account that a lot of the kingdoms in the current game's version shouldn't really exist yet (Mercians, Bernicians, etc...), the Saxons will be even weaker. 

So, basically, what I'm proposing is that we should give some more options to the Early Saxons. Keep in mind it took them 70 years to ramp up enough power to challenge the Britons (Mount Badon), where they lost catastrophically, lost the Sussex royal family (leaving only an infant daughter behind) and nursed their wounds for another 70 years. Gaulish and Byzantine **contemporary historians** noted a heavy, HEAVY influx of Saxons fleeing England after Badon, coming back to Saxony. It would be very boring to have that happen in a normal Saxon game. 70 years of nothing, a terrible loss, 70 years to recover again...

What are your thoughts? I also think some sort of alternate history where the Romans listen to the Britons' plea and come over could be very interesting, perhaps through enough +++'s with Odoacer or the Byzantine Emperor. Perhaps you could even strike a scripted bargain with them, "Kill the Britons and we defeat Theudariks for you" and "Kill the Britons and we'll take back Italy for you" respectively.

**Comment by loup99** [comment]
Not sure on having a specific event of recruiting people from the continent. Isn't it already covered by the mercenaries and then if they loose, courtiers moving over?  As for helping out between Romano-British and Romans, would an alliance and opinion bonuses for being in the same culture group represent it?

Concerning the map related balance concerns, given that the map is being completely overhauled I wouldn't base any option upon that.

**Comment by MaelgwnGwynedd** [comment]
Yes, that could represent it. But historically, in real life, they were downright enemies since the Romans "abandoned" them to their fate.

And ok.

**Comment by loup99** [comment]
I think it could be a part of a general look at religion and relations between realms.

**Comment by TurtleShroom** [comment]
If we're talking Romano-Britons and such, there needs to be a means where they (like the Visigoths) convert to other cultures. For example, I have seen Romano-Hispanics last for centuries after the WRE collapses.

**Comment by loup99** [comment]
> If we're talking Romano-Britons and such, there needs to be a means where they (like the Visigoths) convert to other cultures. For example, I have seen Romano-Hispanics last for centuries after the WRE collapses.

Melting-pots are being worked upon.
