### ISSUE TITLE
Welsh and Saxon Nicknames

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#189]
**WELSH:**
Cadomedd: Abandon an ally in a battle that leads to their death while an ally of their's in a war [Battle Shirker]
Ddoeth: Age at least 20, has traits quick or genius or just or patient or scholar (having two or more of those increases the chances)  [the Wise]
Ddyrnllug: Have more than 2000 gold (Rich enough to own a sword with a "gleaming hilt") [Gleaming Hilt]
Eurfron: ? [Golden Breast]
Fendigaid: Age at least 20, Piety of at least 1000. Chance increases at 2000, 4000, and 6000 piety. [the Blessed]
Farfog: ? [the Bearded]
Fawr: Win a war with the 'Tribal Invasion' or 'Crusade' casus belli, either as the attacker or defender OR rule 10 years, 2000 Prestige, higher tier than count. Chance increases at 4000, 8000, and 15000 prestige. [the Great]
Felyn: Have the DNA code for strawberry blonde or ginger hair [the Tawny]
Finddu: ? [Black Lips]
Frych: Have a DNA code for freckles [the Freckled]
Garanhir: ? [Longshanks]
Glinfawr: Have more than ten children [Great Knee]
Glodrydd: Have over 2000 prestige [the Renowned]
Goch: ? [the Red]
Gorlassar: ? [Steel Armour]
Gosgorddfawr: Field an army of more than 2000 men [Great Army]
Gul: ? [the Lean]
Gwrtheneu: ? [the Thin]
Hael: ? [the Generous]
Hen: Age at least 55, ruled 20 years. Chance increases at age 65 and 75, and at 30 and 40 years as a ruler. [the Old]
Hir: ? [the Tall]
Lawhir: ? [Long Arm]
Lew:  Win a war with the 'Tribal Invasion' casus belli as the defender [the Brave]
Llaw Ereint: Have a prosthetic hand [Silver Hand]
Lledlwm: Have a treasury with 0 or less gold for over five months [the Ragged]
Luyddog: Construct a bishopric [of the Host]
Penarddun: Have the attractive trait [the Beautiful(est)]
Pendronn: Win more than ten battles [Warlord]
Penuchel: ? [the Arrogant]
Penisel: ? [the Humble]
Post Prydein: Defeat an invasion or tribal invasion cassus belli war against a British kingdom  [the Pillar of Britain]
Wledig: ? [the Imperator]
Wyllt: Have the lunatic trait [the Mad]
Yrth: ? [the Impetuous]
Ysgithrog: Execute or assassin more than five people [the Fanged]

**SAXON:**
_Male_
se Ēadiga: Age at least 20, Piety of at least 1000. Chance increases at 2000, 4000, and 6000 piety. [the Blessed]
se Fægera: Age 15 to 59, has attractive trait [the Fair]
se Gegafa: Seducer with Seduction focus [the Lewd]
se Gōda: Age at least 20, has traits charitable and just [the Good]
Healfdan: Be born to a Danish parent and another culture parent [Half Dane]
se Māda: Have the lunatic trait [the Mad]
Swica: Break a treaty [the Traitor]
Wīcing: Have a successful prepared invasion or while raiding [the Pirate]
se Wynsuma: Age at least 20, has traits gregarious and kind [the Merry]
_Female_
sēo Ēadige: Age at least 20, Piety of at least 1000. Chance increases at 2000, 4000, and 6000 piety. [the Blessed]
sēo Fægere: Age 15 to 59, has attractive trait [the Fair]
se Gegafe: Seducer with Seduction focus [the Lewd]
se Gōde: Age at least 20, has traits charitable and just [the Good]
Healfdan: Be born to a Danish parent and another culture parent [Half Dane]
se Māde: Have the lunatic trait [the Mad]
Swica: Break a treaty [the Traitoress]
Wīcing: Have a successful prepared invasion or while raiding [the Pirate]
sēo Wynsume: Age at least 20, has traits gregarious and kind [the Merry]

**Comment by MaelgwnGwynedd** [comment]
? indicates I'm not sure what conditions should be met for this nickname. I'm open to suggestions on those and the ones that _do_ have conditions!

**Comment by TurtleShroom** [comment]
Dude, these are amazing. I'll set to work implementing them next week.

Specifically, what Saxon culture are these names for? Old Saxon? Anglo-Saxxon? Jute?

**Comment by loup99** [comment]
Thank you! Will implement them when I have time.

**Comment by MaelgwnGwynedd** [comment]
Old Saxon = Anglo-Saxon to be honest, I don't see why we should differentiate them. So both.

I'd be happy to implement them now, do I just add them to WTWSMS_nicknames?

**Comment by loup99** [comment]
Yes, you can add them to that file.

**Comment by MaelgwnGwynedd** [comment]
It seems the game overwrote them?

**Comment by loup99** [comment]
What do you mean?
