### ISSUE TITLE
Overhauled Northern Britain and Pictland

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#190]
In my fork I've overhauled Northern Britain and Pictland. How do I add my changes to the official repository now?

**Comment by loup99** [comment]
You first need to commit your changes to your fork. Then you can create a pull request to master.

**Comment by MaelgwnGwynedd** [comment]
It won't allow me to do the pull request. I've already committed the changes.

**Comment by loup99** [comment]
I can't see the changes: https://github.com/MaelgwnGwynedd/WtWSMS

**Comment by MaelgwnGwynedd** [comment]
![image](https://cloud.githubusercontent.com/assets/21295761/21079840/b077508c-bf9e-11e6-9261-156fa919057a.png)

**Comment by loup99** [comment]
You need to sync. Then click on "Pull request".

**Comment by MaelgwnGwynedd** [comment]
I can't sync, it says I don't have the permission.

**Comment by loup99** [comment]
That is because you are on the master branch rather than being on your fork.

**Comment by MaelgwnGwynedd** [comment]
I am on my fork.

**Comment by loup99** [comment]
Then I don't know. Do I research "sync changes on fork"

**Comment by MaelgwnGwynedd** [comment]
I have been doing so for the past three hours.

**Comment by MaelgwnGwynedd** [comment]
It seems to work, I have issued a pull request.

**Comment by MaelgwnGwynedd** [comment]
How long do pull requests typically take to go through?

Can I start editing again despite it not having gone through?

**Comment by loup99** [comment]
It takes as long as needed for me to review it and it to be ready for merge. You can continue commiting stuff.
