### ISSUE TITLE
Kingdoms are randomly theocracies

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#192]
Several of the British kingdoms in my fork are randomly theocracies, despite there being no reason for them to be one. Gododdin is a theocracy from 470-600 but the code is this:

http://pastebin.com/raw/xFgJNvXX

**Comment by loup99** [comment]
No idea why.

**Comment by TurtleShroom** [comment]
Yeah, Sarir (in Armenia) is a theocracy, too!

**Comment by loup99** [comment]
No, the two are unrelated.
