### ISSUE TITLE
A note on British Dynasties

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#193]
Should we "make up" houses for the Saxons, Britons, Irish and Picts? There were not actually any (workable) noble houses, and they were as far as we know unnamed. There was importance in who you were descended from (the ap Ceneu's were descended from Ceneu ap Coel).

I suggest these:

Saxons (Angles, Jutes, Frisians):
The name of the ancestor they had of the Saxon king Woden (not the God Woden, the Saxon King of the same name):
Bældæges Folc (Baeldaeg's folk)
Benoces Folc (Benoc's folk)
Caseres Folc (Caser's folk)
Wegdæges Folc (Wegdaeg's folk)
Wehtan Folc (Wehta's folk)

British:
No idea, suggestions welcome.

Pictish:
Because of how scant information is, make them up using reconstructed pictish words (the House is only in this list and would not be included in-game):
House Yorqo (Roebuck)
House Arto (Bear)
House Broqqo (Badger) 
House Iqoqaiqo (the Blind Ones)
And so on...

**Comment by MaelgwnGwynedd** [comment]
For the reconstructions I used the only two sound changes we can be sure of:
k and kw becoming q (Proto-Celtic makkwos > Pictish maqqo as per Pictish stones)
os > o (Every noun on the Pictish stones drop the s)

So Yorkos becomes Yorqo.

**Comment by loup99** [comment]
For the Saxons, OK, but is "folk" necessary? Same for Pictish, no need to have "House" in my opinion.

By "British", do you mean Briton?

**Comment by MaelgwnGwynedd** [comment]
Yes, the folk part is necessary. You wouldn't tell someone. "Fear me! I am Wehta!" since you're not. You're tribe is "Wehta's Folk", his descendants.

**Comment by loup99** [comment]
But given that they are a tribe, isn't that included in the landed title rather than dynasty?

I missed that, sorry. 

Fair enough. Although I have read "Britons", which is easier to differentiate in my opinion.

**Comment by MaelgwnGwynedd** [comment]
Not at all, the tribe is long gone. Hengest is a descendant of Wehta, so it's either Wehtan Folc or Wehting.

**Comment by MaelgwnGwynedd** [comment]
Wehting being "son/descendant of Wehta"

**Comment by loup99** [comment]
I think the "ting" addition would be better than "folc", given how the naming is used for other cultures.

**Comment by MaelgwnGwynedd** [comment]
True.
