### ISSUE TITLE
The problem of Pictish names

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#194]
A lot (if not all?) of the Pictish names in the mod right now are from Age of Charlemagne, making them all Irish (read: Anachronistic).

Here is all we known about Pictish names:

-Some of them can be inferred (Drust, Talorc, Uuirp, Nehhton). It's hard to infer them, since these are later "Gaelicised" into Drest, Talorgan, Erp and Nechtan.
-Female names ALWAYS took the male form + icc. Drusticc, Talorcicc, Uuirpicc, Nehhtonicc. Anything else is a female, Gaelic name.

How should we proceed? We can use anachronistic and/or Gaelic names or "make them up" based on cognates. For example, the name Elpin from later centuries can be traced back to Proto-Celtic Alpinos, which would probably be something like either Alpino or Elpino in our period's Pictish.

**Comment by loup99** [comment]
I'd say that we try to stick to what we can find in terms of making up based upon what we know and other sources and then if we are in need of filling use anachronistic names as a last resort.

**Comment by MaelgwnGwynedd** [comment]
We have a list of about twenty names we know for sure are Pictish, and the female equivalents by adding icc. That should be enough I think?

**Comment by loup99** [comment]
In general 50 seems to be a good standard. Do you think it would be feasible to find ten or so more names, just to make sure there is some variation? Otherwise 40 will do.
