### ISSUE TITLE
I Broke Everything, Please Check and Implement the Closed "TurtleShroom Productions VII" So I Can Move On

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#195]
Good evening.

I am in dire straits. Through a series of extremely unfortunate and confusing cirucmstnaces, I have completely broken everything I have made since the last commit you made.

When I was synchronizing your changes with mine, I ran into dozens of Conflicts, and the Github Console would not let me sync them. I discarded the Conflicts and merged the rest. The problem is that I did not write down what the conflicted items were, so I now had dozens of files that were out of synch with yours. I had no idea what they were, so I tried to Revert the merger commit I used.

The retarded Github Console wouldn't let me, and it forced me into the Shell. I was unable to revert through the Shell because the folder tree's path had spaces (which Github Shell did not recognize). I had the idea to download and copy an old version onto the new version, but that would destroy your changes.

Instead, I closed my Pull Request and then opened another. The problem is that I STILL cannot identify what I conflicted with, and now all I have left to go on is at https://github.com/loup99/WtWSMS/pull/184/files . I don't know how to locate and download each of these files into the new version I had to clone. With absolutely everything torn up, https://github.com/loup99/WtWSMS/pull/184/files is all I have left to go from.

As such, the only way forward from here is that you need to Implement the closed "TurtleShroom Productions VII" at https://github.com/loup99/WtWSMS/pull/184/files , including my Holy Orders and Borborite (etc.) stuff, because I cannot recover it myself.

Although I made a lot of changes, this was fairly minor, especially because the sheer complexity of the Borborites implementation neccesitated several independent files.

I cannot recover my own files because of the issues I described above. Please help me and implement https://github.com/loup99/WtWSMS/pull/184/files so that I can start again.

Thank you.
-TURTLESHROOM

**Comment by TurtleShroom** [comment]
Note: I did not break the code in https://github.com/loup99/WtWSMS/pull/184/files . I broke it on my end and lost all my Commits. The code at https://github.com/loup99/WtWSMS/pull/184/files works and is all tested, so it's ready for implementation.

**Comment by loup99** [comment]
Answered on the pull
