### ISSUE TITLE
Ireland

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#196]
I'm going to be fixing Ireland soon, adding the appropriate missing Kingdoms since right now they're just the Charlemagne ones which is pretty grossly innacurate.

## A few points:

-Should they also be considered Celtic Pagans? And the Christians Insular Christians?
-What language will we be using for them? There were two languages being spoken during the Migration Period(1). The older, more official and more formal Primitive Irish, and the simpler, commoner, lower-class Old Irish. Should the names be in Primitive Irish or Old Irish?
-In terms of clothing, richer people and famous poets wore feathers on their brats (cloaks). A king (or very famous poet) would have a brat fully covered in Drake feathers, whereas your average normal would probably have a few heron feathers around his collar and at the bottom edge. We should include this somehow, since it will give them a historically accurate and (correctly) exotic look.
-How are we going to organise the tuatha system?  There's been mentions that we have some sort of system but I've never seen it detailed.
-What should we call the High Kingdom title? In Old Irish it's called Eire, but in Primitive Irish it's called Iweriu. So either High King of Eire or High King of Iweriu, which one?

### -High Kingship of Ireland
>Kingdom of Tara
>Kingdom of Maigh Seola
>Kingdom of Ui Maine 
>Kingdom of Aidhne 
>Kingdom of Maenmaige
>Kingdom of Laigin 
>Kingdom of Mide 
>Kingdom of Munster 
>Kingdom of Ulaid
>Kingdom of Cashel
>Kingdom of Iarmuman
>Kingdom of Osraige

## Pagan Irish Gods:
Abarta
Abcán
Abean
Abgatiacus
Aed
Aengus
Aibell
Ailill
Aimend
Áine
Airmed
Alastir
Anand
Aí
Aífe
Badb
Balor
Banba
Bec
Beira
Biróg
Boand
Bodb Dearg
Brea
Bres
Brian
Brigit
Buarainech
Bé Chuille
Bébinn
Caer
Caillech
Canola
Cessair
Cethlenn
Cian
Cichol
Clídna
Conand
Corb
Credne
Crob Derg
Crom Cruach
Crom Dubh
Dagda
Danand
Danu
Delbáeth
Dian Cecht
Donn
Dáire
Ecne
Egobail
Elatha
Elcmar
Ériu
Ernmas
Étaín
Ethniu
Fand
Finnguala
Flidais
Fódla
Goibniu
Lir
Luchtaine
Lug
Lén
Lí Ban
Mac Cuill
Macha
Manannán
Medb
Medb Lethderg
Miach
Midir
Mongfind
Morrígan
Mug Ruith
Mór Muman
Nechtan
Neit
Nemain
Niam
Nic Naomhín
Nuada
Ogma
Plor na mBan
Scathach
Seonaidh
Sheela na Gig
Tailtiu
Tethra
Tuirenn

## Pagan Irish Festivals:
-Samhain: End of the Harvest and start of Winter. Corn and milk is sacrificed.
-Calan Gaeaf: First day of winter. People avoided churchyards, stiles, and crossroads, since spirits are thought to gather there. They each danced around a fire and threw a stone into it. If, the next day, when they woke up, their stone was missing, they were sure to die within a year. (Atheist explanation: someone can steal a stone on purpose, giving one of their enemies the stressed attribute or even make them go into hiding)
-Imbolc : The holiday was a festival of the hearth and home, and a celebration of the lengthening days and the early signs of spring. Celebrations often involved hearthfires, special foods, divination or watching for omens, candles or a bonfire if the weather permitted. Fire and purification were an important part of the festival. The lighting of candles and fires represented the return of warmth and the increasing power of the Sun over the coming months. A spring cleaning was also customary.
Holy wells were visited at Imbolc, and at the other Gaelic festivals of Beltane and Lughnasa. Visitors to holy wells would pray for health while walking 'sunwise' around the well. They would then leave offerings; typically coins or clooties (see clootie well). Water from the well was used to bless the home, family members, livestock and fields.
Donald Alexander Mackenzie also recorded that offerings were made "to earth and sea". The offering could be milk poured into the ground or porridge poured into the water, as a libation. (Both a Christian and Pagan festival, though Christians also offered up Brigit crosses and paraded a doll effigy of Saint Brigid)
-Gŵyl Fair
-Beltane 
-Calan Mai 
-Lughnasadh 
-Calan Awst 
-Feis Temro (Unique to Tara)

## Holy Artifacts (Monks & Mystics update):
CELTIC
Swords
-Caladbolg 
-Ceard-nan Gallan 
-Claimoh Solais 
-Cruadh-Chosgarach
Stones
-Lia Fáil 
Jewellery
-Dragonstone amulet
ALL RELIGIONS
-King Stone (All Kings have one)

## Religions:
Celtic Paganism: Traditional Celtic Paganism
Belinism: Belief that Jesus is the Sun God Beli (CHRISTIAN HERESY)
Insular Christianity: Traditional Insular Christianity
Pelagianism: Followers of the teachings of Pelagius (CHRISTIAN HERESY)

Should we include fictional characters (Cu Chulainn) as their probable real-life counterparts?

I will implement the above myself, don't worry, I just need answers and discussion regarding the questions.

(1) John T. Koch, "The conversion and the transition from Primitive to Old Irish", Emania 13, 1995

**Comment by MaelgwnGwynedd** [comment]
We can definitely use existing borders though:

the region that encompasses the 'TH' in MEATH would be TARA
the region that encompasses the 'LEINST' in LEINSTER would be OSRAIGE
the region that encompasses 'ER' in Leinster would be LAIGIN (LEINSTER)
the southern portion of Munster would be IARMUMAN
the western portion of Connacht would be MAIGH SEOLA
the eastern portion of Connacht would be UI MAINE
the region that encompasses the 'MEA' in MEATH would be MIDE
The northern portion of Munster would be AIDHNE
The eastern portion of Munster would be MUNSTER (/Cashel)
The R in Ulster and the region beneath it would be ULAID
"ul" and "st" in ULSTER would be UI NEILL
the "cht" in connacht would be BREIFNE

The three strongest Kingdoms would be the Laigin (of whom the King is High King, probably) and then the Ui Neill and Ulaid. 

![image](https://cloud.githubusercontent.com/assets/21295761/21294123/51cc6bb0-c536-11e6-9945-33c1b37dc494.png)

**Comment by loup99** [comment]
> -Should they also be considered Celtic Pagans? And the Christians Insular Christians?

Yes and yes.

> -What language will we be using for them? There were two languages being spoken during the Migration Period(1). The older, more official and more formal Primitive Irish, and the simpler, commoner, lower-class Old Irish. Should the names be in Primitive Irish or Old Irish?

Primitive Irish given that it is the nobility we represent.

> -In terms of clothing, richer people and famous poets wore feathers on their brats (cloaks). A king (or very famous poet) would have a brat fully covered in Drake feathers, whereas your average normal would probably have a few heron feathers around his collar and at the bottom edge. We should include this somehow, since it will give them a historically accurate and (correctly) exotic look.

Not opposed to adding clothing, but it requires graphic expertise.

> -How are we going to organise the tuatha system? There's been mentions that we have some sort of system but I've never seen it detailed.

Enlil worked on it and didn't find a good way of implementing it.

> -What should we call the High Kingdom title? In Old Irish it's called Eire, but in Primitive Irish it's called Iweriu. So either High King of Eire or High King of Iweriu, which one?

Eire is what we use currently, but maybe Iweriu could be a better alternative?

> Should we include fictional characters (Cu Chulainn) as their probable real-life counterparts?

Yes, but exclude characters that are solely fictional. 

> Belinism: Belief that Jesus is the Sun God Beli (CHRISTIAN HERESY)

So you want a new heresy? We will have to discuss that.

**Comment by MaelgwnGwynedd** [comment]
I don't really "want" it, it's objectively mentioned by the Christians that some Picts and Irish had started worshipping Jesus as a Sun god.

**Comment by loup99** [comment]
Poor wording on my part, "suggest the inclusion of" is more adequate.

**Comment by MaelgwnGwynedd** [comment]
Sure, no problem, I just wanted to make it clear I see these things objectively, I'm 100% in favour of scrapping historical things (tuatha) for the gameplay. Same goes for unecessary (though accurate) additional heresies.

Some examples of Primitive vs Old Irish:

Vergosus Mori vs Fergus Mor
Cunavalas vs Conall
Rodagnas vs Ruadan

Titles:
tovisacas vs toisech

Patronyms:
maqqas vs mac(c)

**Comment by MaelgwnGwynedd** [comment]
An example of a Primitive Irish stone inscription:
"ANAVLAMATTIAS MUCOI [N]OELURI AVI AKERAS"

Anavlamattias: Male name
Mucoi: of the tribe of the
Noeluri: tribe name
Avi: descendant of
Akeras: Male name

So the inscriber was called Anavlamattias, part of the Noeluri (Neill) kingdom and a descendant of a man named Akeras (later Aicher).

**Comment by loup99** [comment]
> Primitive Irish stopped being used after the 700's, so we should have some sort of transition at that point if possible.

The only possible option would be a separate culture and events.

> Same goes for unecessary (though accurate) additional heresies.

Do you have any internet source for Belinism?

**Comment by MaelgwnGwynedd** [comment]
English > Old Irish > Primitive Irish
Tara 
Osraige 
Laigin 
Iarmuman 
Maigh Seola 
Ui-Maine 
Meath > Mide > 
Aidhne 
Munster > Mumu > 
Ulaid 
Ui Neill > Ui Neill > Avi Noeluras

> Do you have any internet source for Belinism?

Yes. It was written by a zealot so you can ignore the overly christian narrative, but what he says is verifiably true.

The introduction of Christianity was the most significant force of change during the early historic period. The druids were particularly receptive to Christianity, for druidism bore certain uncanny resembles to Christianity among which was the belief of a messiah-figure or culture-hero. The druids erected an altar which they dedicated to The Virgin and Christ-Child and inscribed on it: “hinc druidae statuam in itimis penetralibus erexerunt, isidi seu virgini dedicantes, ex qua filius proditurus erat nempe generis humani remptor”. Legend says that the converted druid Dadera preached the gospel throughout the British Isles. He was a disciple of Joseph of Arimathea. Christianity in Britain early mixed with native pagan druidism as the heathen Picts carried many of their pagan beliefs and practices into their new religion, and attempts were made to harmonize druidism with Christianity in which Jesus became the British sun-god Eisu (Esus; Iesu) and was identified with the “dero” [culture-hero] of British Mythology, therefore, almost immediately the Picts relapsed back into paganism. Esus appears in a first century AD relief dated circa AD 75 that was dedicated to Jupiter. The Romans reported that human-sacrifices were made to the British sun-god Esus (Iesu; Eisu) and that the victims were suspended from trees and ritually wounded and slain, probably in imitation of Jesus’ crucifixion. If the British god Esus pre-dates Christianity which some historians argue then when Christianity preached Jesus as God in Britain it thus preached to the Britons the name of one of their own deities, which if true would indeed be a curious coincidence, however, it is more probable that the druidic trinity, Belus (Beli, Balor, Bile), Taranis, and Hesus/Jesus (Eisu; Esus; Iesu) developed after the introduction of Christianity during the later regression of the Picts back into paganism. Christianity was re-introduced to the Picts in the fifth century by St. Ninian, and again in the sixth century by St. Columba before finally taking root, and by the ninth century druidism had finally accepted the fuller revelation of Christianity, and, thus, fulfilled, druidism passed away. There is evidence that a sect of druids survived until the mid-tenth century, by which time they completely disappear. The druidic priesthood dissolved with the conversion to Christianity and pagan druids became Christian bishops, and the vestal-virgins ["daughters of Britannia"] became the nuns of the order of St. Briget’s [the pagan goddess turned into a Christian saint]. The modern revival of druidism in recent times has few similarities with the ancient druidic religion, and appears to incorporate several wholly foreign cults. The concept of monarchy changed with the conversion to Christianity whereby the king ceased to be a god himself and instead became the representative of God as the "Lord’s Anointed". The sacrifices of the sacral-kings ceased as early as the first century AD then interpreted as typifying Christ’s Sacrifice, however, the animal-sacrifices continued to be made as memorials of Christ’s Sacrifice until as late as the sixth century when they were replaced with the Christian rite of the "bread and wine", that is, the "eucharist", or "Lord’s Supper", which also commemorates Christ’s Sacrifice.

More info:
https://www.google.fr/search?q=ish+god+esus&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=5atWWKHFDIbBaM-UkbgN#safe=off&q=pictish+god+esus

Jesus became "Esus" who was part of the trinity with Beli (earlier Belinos) and Taranis. Beli was the chief aspect, so thus "Belinism", though in truth it was not named.

**Comment by TurtleShroom** [comment]
I will assume responsibility for Belanism! I live for making religions better!

**Comment by MaelgwnGwynedd** [comment]
I'd like to try my hand at coding a religion, if you don't mind.

**Comment by TurtleShroom** [comment]
I do mind (it and flags are my favorite tasks on here), but it's your idea and thus your credit. I will not make it, per your request, so make sure you get on it, because if you take too long (say, next year), I'm doing it.

I wish you nothing but success. Make me proud, you've done nothing but that this entire time. You are such a good researcher.

**Comment by TurtleShroom** [comment]
@MaelgwnGwynedd 

There is no such thing as an "unnecesary" heresy or "unnecesary religion" in this Mod. As long as the religion _actually and accurately exists in this time period_, we can and should add it. In fact, I feel that we have a _duty_ to add it.

Do you still want to make Belinism, or do you want me to do it?

**Comment by MaelgwnGwynedd** [comment]
I'm having trouble dividing the map up. I'll wait for our overhaul to be done.

There's also the problem of not many kings being named, leaving big gaps in some of our king-lists. We'll have to make up characters.

**Comment by MaelgwnGwynedd** [comment]
The ones I know of are the Osraige Kings, which include, in our time period:

King Conall (???-500's)
Ruamanduach (Father outlives him, doesn't rule) (466-490)
Laignech Fealad (???-???) (Ruamanduach's son)
Eochad Bicne Faelad (???-???)
Colman Mor (???-574)
His son ??? until our end date of 600 for the characters file.
