### ISSUE TITLE
Can a name be randomised?

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#197]
Can a character's name be randomised? One female character who we know existed (Fergus Mor's wife) was a daughter of a Danish nobleman named Graym, but we don't know her name. Would it be possible to randomise her name from the set name of female Danish names?

**Comment by loup99** [comment]
Not sure if it possible through the history files. With an event it is though.

**Comment by MaelgwnGwynedd** [comment]
I'll just give her a random name then, no problem.
