### ISSUE TITLE
Likely Alternate Histories

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#199]
While some things are very unlikely in the game (turn the Picts into a Jewish Sultanate), they're still possible. And I think it would be nice to add special flavour to some things that are likely to happen:

-Spain remains Gothic and is never invaded by the Moors
-Rome forms an alliance with [China](http://www.timemaps.com/store/timemaps/2012/5/china500ad.jpg) against the Huns
-The Rouran Khaganate invades Europe
-Someone other than an Ostrogothic King takes over Italy from Odoacer, changing the future of the country forever

**Comment by TurtleShroom** [comment]
I agree. There also needs to be some Events announcing where Zeno is defeated by the Miaphysite emperor and where the Western Roman Empire holds off Odoacer.

**Comment by MaelgwnGwynedd** [comment]
Thanks. Could you help me in the most recent thread? I'd like to know what to do next regarding the last kingdoms I need to include whom we don't know the leaders of.

**Comment by TurtleShroom** [comment]
I'd suggest generating your own characters and giving them Traits and coding that would cause them to replicate what they would do in RL.

**Comment by TurtleShroom** [comment]
Not only that, I also think Narrative Events that announce the arrival of new hordes (Turks and so on) could really contribute to the storyline.

**Comment by MaelgwnGwynedd** [comment]
"My own characters" though? We could always use real people who existed but who we don't know the acts of.

**Comment by loup99** [comment]
Please avoid discussing other issues here. 

We already have events announcing hordes. By Rome, do you mean the ERE? For countries remaining as they are we don't need specific events announcing it, even though we can have events relating to it.
