### ISSUE TITLE
Counties included in several different de jure things?

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#201]
I have a problem.
Leicester and Derby formed the Kingdom of Elmet, but one is in d_york and the other in d_lancaster. How do I create a k_elmet or d_elmet which encompasses Leicester and Derby?

**Comment by MaelgwnGwynedd** [comment]
That example apparently already exists, but could someone still guide me through it (to whoever created d_elmet, props on getting the geography exactly right)

**Comment by loup99** [comment]
It is not possible for a county to be in multiple duchies at the same time. However as the entire map is getting overhauled, so we are not prioritising to fix inaccuracies on the British Isles.
