### ISSUE TITLE
Countries we simply don't know the rulers of.

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#202]
We know of the Kingdoms of Lundein, Went, Colun... But we have no idea WHO ruled over them. What do we do about such kingdoms?

Right now those have been replaced with Norfolk, Eastanglia and Suffolk, but those are anachronistic and only established themselves later on.

**Comment by MaelgwnGwynedd** [comment]
Right, I propose:

Lundein: Since we know the Lundinians tried to take back Ceint, and we know Ceint's ruler who was deplaced by Hengest **Gwrangon** had a son **Gwyamad** whose son **Lleu** ruled in Manau Gododdin, we can rule that line out. So I propose "making up" a second son for Gwrangon, whose three heirs split the South-East of England between themselves, and we can add more fictitious heirs until 600 AD.

**Comment by MaelgwnGwynedd** [comment]
Right, 

Norfolk & Suffolk:
`420.1.8={
	holder = 1210171 # Gworangon
}
460.1.1={
	holder = 1210173 # Ermid
}
480.1.1={
	holder = 1210174 # Coel
}
510.1.1={
	holder = 1210176 # Hryþ 
}
530.1.1={
	holder = 1210175 # Wilhelm
}
560.1.1={
	holder = 168361 # Wehha
}
571.1.1={
	holder = 168362 # Wuffa
}
578.1.1={
	holder = 168363 # Tyttla
}
593.1.1={
	holder = 168580 # Rædwald
}`
Essex:
`
420.1.8={
	holder = 1210171 # Gworangon
}
460.1.1={
	holder = 1210173 # Ermid
}
480.1.1={
	holder = 1210174 # Coel
}
510.1.1={
	holder = 1210182 # Celynin
}
540.1.1={
	holder = 100507 # Eormenric
}
560.1.1={
	holder = 168357 # Æscwine Gesecging
}
587.1.1={
	holder = 168358 # Sledd Gesecging
}
604.1.1={
	holder = 168360 # Sæberht Gesecging
}
616.1.1={
	holder = 106643 # Sexræd Gesecging
}
617.1.1={
	holder = 1202 # Sigeberht I Gesecging
}
653.1.1={
	holder = 202960 # Sigeberht II Gesecging
}
660.1.1={
	holder = 205520 # Swithhelm Gesecging
}
664.1.1={
	holder = 205529 # Sighere Gesecging
	liege="k_mercia"
}
683.1.1={
	holder = 206800 # Sæbbi Gesecging
}
694.1.1={
	holder = 206801 # Sigeheard Gesecging
}
`
Northampton and Bedford and Middlesex:
`420.1.8={
	holder = 1210171 # Gworangon
}
460.1.1={
	holder = 1210173 # Ermid
}
480.1.1={
	holder = 1210174 # Coel
}
510.1.1={
	holder = 1210182 # Celynin
}
540.1.1={
	holder = 1210185 # Cnebba
}
560.1.1={
	holder = 1210186 # Cynewald
}
580.1.1={
	holder = 1210187 # Creoda
}
593.1.1={
	holder = 1210188 # Pybba
}
610.1.1={
	holder = 170115 # Cearl Iclingas
}
626.1.1={
	holder = 144635 # Peada Iclingas
	liege="k_mercia"
}
656.1.1={
	holder=170120 # Oswig Ingving
}
658.1.1={
	holder=206802 # Wulfhere Iclingas
}
675.1.1={
	holder=206803 # Æthelred Iclingas
}`


INVADERS
Hryth: Takes over Norfolk and Sussex, forms the Eastengle. (510 AD though they arrived in 495 AD)
Eormenric: King of Kent. Snatches Essex from the Britons (Coel's son Celynin). (540 AD)
Eomaer: Arrives in Eastanglia but is pushed out by the Wuffingas (Hryth). His grandson Cnebba invades Northampton and Bedford (and Warwick)? (540 AD). Probably also the sovereign of the Middleseaxe, so he can have Middlesex in 540 AD too.

There! And only had to make up three people, who likely existed and did exactly what I've made them do (cling on to the remnants of South-Eastern Britain)

**Comment by loup99** [comment]
Sounds good.
