### ISSUE TITLE
Portraits

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#204]
We really need to get our portraits looking a bit better, lol.

[Woden looks like Old Spock](http://image.noelshack.com/fichiers/2016/51/1482278907-ck2-557.png), and Cerdic of Wessex always ends up as a fat seedy-looking italian mobster.

**Comment by loup99** [comment]
We would have to find someone talented at making graphics.

**Comment by MaelgwnGwynedd** [comment]
I'm working on that.

**Comment by loup99** [comment]
Closing this as an artist has been found.
