### ISSUE TITLE
Clothing and Appearance 

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#205]
Found someone who is willing to help design some portraits for us!

While I feel comfortable advising them on Irish, Pictish, Scandinavian, Germanic and Celtic clothing, I have no idea what was going on in places like the Byzantine Empire, Italy, or the Slavic tribes around this time... So could everyone pitch in to this thread? The idea would be to post facts and reference pictures for a given country (or culture) that you would research whenever you have time or want to, and post from time to time. Does that sound good?

ROMANO-BRITONS:
Hats: The pillbox or conical hat. For women, a hood or cowl or a sheer cloak.
Tunics: Coptic tunics, more or less patterned depending on wealth. Wool for the poor, linen for the richer.
Dresses:
Hair colours and styles: Vanilla ones except for "spiked hair" which some Britons used. They dyed their hair white (or bleached it very light blonde sometimes) and spiked it back using lime.
Dyes in use: Most. Black very rare, Purple extremely rare, red quite rare. Most popular colour blue (because of the plentiful amount of woad). Linen dyes less readily than wool so led to lighter colours. Dyes were very bright during this period.
Fabrics in use: Wool, linen
Weaves: Twill, 

IRISH
Fabrics in use: Wool, linen, nettle
Tunics: Léine, often worn long, usually by nobles. Usually undyed.
Dresses: An ankle-length léine as well.
Cloaks: The brat, often decorated with feathers, heron for poorer peoples and drake feathers for kings or famous poets. Usually only used at the bottom hem or around the collar, kings and poets usually had the entire brat covered in feathers.
Dyes in use: Same as Romano-Britons
Weaves: Twill, [flokati](http://ii.worldmarket.com/fcgi-bin/iipsrv.fcgi?FIF=/images/worldmarket/source/6321_XXX_v1.tif&wid=2000&cvt=jpeg&Area%20Rugs_Ivory%20Flokati%20Wool%20Rug) (brats) [shaggily woven wool made to look like fur]

SAXONS
Tunics:
Dress: Peplos gown, undertunic
Hair colours and styles: Sometimes dyed orange, green, red or blue.
Fabrics in use: Wool, linen, silk
Weaves: Twill

SCANDINAVIANS
Tunic: Often the wrap-around warrior tunic was worn.

TEMPLATE
Hats:
Tunics:
Dresses:
Cloaks:
Hair colours and styles:
Dyes in use:
Fabrics in use:
Weaves:

**Comment by TurtleShroom** [comment]
I don't know how to edit clothing files. If I try my hand at it, do you think one of you will implement it?

I discussed way back in the Root West Issue that I could add the clothes by basing them off of the Buddhist robes. The problem is that I don't know how to do it.

Also, I'm going to have to create a master list of things I want to do and add, but do not have the tools or the skill to add them (such as religion icons and religion clothes).

**Comment by TurtleShroom** [comment]
I'd like to see a Trait-bound feature for skull elongation for Hephatalites and Huns as discussed in https://github.com/loup99/WtWSMS/issues/168 .

**Comment by MaelgwnGwynedd** [comment]
I know how to edit and compile the clothing files in the correct filetype, don't worry.

Here's their first contribution, a stylish Romano-British tunic

http://image.noelshack.com/fichiers/2016/51/1482361229-668dd2f47846265200d4e1177d8a134e6939009c382f4edab5-pimgpsh-fullsize-distr.png

**Comment by TurtleShroom** [comment]
Okay, so here are the Root West clothes I edited.

![root_west_headgear](https://cloud.githubusercontent.com/assets/17663470/21412576/3ed26efc-c7bf-11e6-9e44-f03ca32c26a9.png)
![root_west_headgear_behind](https://cloud.githubusercontent.com/assets/17663470/21412577/436534cc-c7bf-11e6-9b2d-c4b206919dcb.png)


![root_west_clothes](https://cloud.githubusercontent.com/assets/17663470/21412578/4823da40-c7bf-11e6-9b5a-db0643cd2db8.png)
![root_west_clothes_behind](https://cloud.githubusercontent.com/assets/17663470/21412591/53481f80-c7bf-11e6-8a6f-1174188ed1a6.png)

In order, these are: headgear, headgear behind, clothes, clothes behind.

See the original thread: https://github.com/loup99/WtWSMS/issues/132

See the original image: https://cloud.githubusercontent.com/assets/17663470/13551942/484801e4-e319-11e5-9503-86b652b84763.png

**Comment by MaelgwnGwynedd** [comment]
That looks EXTREMELY odd in the portrait builder. And what is the
historical basis for it?

**Comment by TurtleShroom** [comment]
See in the original thread. I did a LOT of research on Root West. 

Unfortunately, few clergy descriptions exist, other than that 1) they wore all black, 2) their robes were somewhat similar to the Buddhists, and 3) their caps were made of black felt. The rest, namely the dangly things (_pendilia_) and sash, are my own ideas based on the Tengri shaman's hat and the eighth clothing type in the Vanilla religious clothes string.

**Comment by TurtleShroom** [comment]
As for Dark Age Byzantine clothes, I actually found [a Halloweenie costume site that did some research on Byzantine Empress Theodora](http://takebackhalloween.org/empress-theodora/), who reigned in this time period. Granted, it only covers female clothes, but still. I know the crown is likely inaccurate, but the rest is impressively researched.

**Comment by MaelgwnGwynedd** [comment]
And wrong, unfortunately.

**Comment by TurtleShroom** [comment]
Which one, my items, or Theodora?

**Comment by MaelgwnGwynedd** [comment]
That blogpost about Theodora.

**Comment by TurtleShroom** [comment]
Ah. What did they get wrong? For example, they used those plastic "Egyptian collars" because they're a few dollars at Wal-Mart. Remember, that site was trying to cobble together a costume resembling a Byzantine empress, not actually make exact replicas of a Byzantine empress' clothes.

**Comment by MaelgwnGwynedd** [comment]
No, not the images. The statements themselves.

**Comment by TurtleShroom** [comment]
AH, that makes sense. 

Well, I was talking about what she was wearing, not what they said she did and did not do. I linked the article because I thought it was an interesting insight to Dark Age fashion for Byzantine empresses.

**Comment by MaelgwnGwynedd** [comment]
I own books on the subject, I'd be happy to link them. They have analyses
of surviving fragments of actual tunica dalmaticae, the weave, fabric, dyes
used, shape...

**Comment by MaelgwnGwynedd** [comment]
Also, she was empress during the biggest time of prosperity. The San Vitale
and Hagia Sophia portraits are propaganda and should be taken with a grain
of salt, just like Roman Emperor's busts.

**Comment by TurtleShroom** [comment]
I thought the picture shown at the top was her in her most formal court dress, similar to how the Queen of England only wears the great crown we usually think of when we think of the UK at her coronation.

I always thought those busts were accurate represenations, but the blemishes, scars, acne, etc. were not present.

As for the books, that is really impressive. We're still talking Byzantine clothes right?

**Comment by MaelgwnGwynedd** [comment]
Yes.

**Comment by MaelgwnGwynedd** [comment]
Saint Edward's Crown? That's only worn once per monarch.
And the Imperial State Crown is worn several times a month.

**Comment by loup99** [comment]
On the matter of this, good that you found someone. Is it someone you knew? If not, how do you always manage to find all of these skilled people in no time? 

To @TurtleShroom based on your post, I think what you linked won't work ingame and would have to be done from scratch in an artistic way as the other clothing Mael showed.

**Comment by MaelgwnGwynedd** [comment]
As I said, it looks odd in Romulien's portrait builder, but it could just be mine.

And no, I didn't know them. The mod has quite a few fans, I just asked if anyone would be interested in contributing a few assets!

**Comment by loup99** [comment]
Where did you ask this? Usually we discuss before making those kind of announcements.

**Comment by MaelgwnGwynedd** [comment]
I asked around on reddit.

**Comment by loup99** [comment]
For reference we tend to avoid using reddit to make announces, just so that you can keep it in mind in the future.

**Comment by MaelgwnGwynedd** [comment]
I can't use anything else.

**Comment by loup99** [comment]
See: https://github.com/loup99/WtWSMS/issues/21
