### ISSUE TITLE
Adding new ethnicity

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#206]
AS per the wikia guide I added the new romano_british_male sprites and a gfx file for the portraits with this code. But it doesn't work. What am I missing?

spriteTypes = {
  spriteType = {
    name = "GFX_romano_briton_male_clothes"
    texturefile = "gfx\\characters\\romano_british_male\\romano_briton_male_clothes.dds"
    noOfFrames = 12
    norefcount = yes
    can_be_lowres = yes
  }
  spriteType = {
    name = "GFX_romano_briton_male_clothes_behind"
    texturefile = "gfx\\characters\\romano_british_male\\romano_briton_male_clothes_behind.dds"
    noOfFrames = 12
    norefcount = yes
    can_be_lowres = yes
  }
  spriteType = {
    name = "GFX_romano_briton_male_clothes_infront"
    texturefile = "gfx\\characters\\romano_british_male\\romano_briton_male_clothes_infront.dds"
    noOfFrames = 12
    norefcount = yes
    can_be_lowres = yes
  }
  spriteType = {
    name = "GFX_romano_briton_male_headgear"
    texturefile = "gfx\\characters\\romano_british_male\\romano_briton_male_headgear.dds"
    noOfFrames = 12
    norefcount = yes
    can_be_lowres = yes
  }
  spriteType = {
    name = "GFX_romano_briton_male_headgear_behind"
    texturefile = "gfx\\characters\\romano_british_male\\romano_briton_male_headgear_behind.dds"
    noOfFrames = 12
    norefcount = yes
    can_be_lowres = yes
  }
  spriteType = {
    name = "GFX_romano_briton_male_headgear_mid"
    texturefile = "gfx\\characters\\romano_british_male\\romano_briton_male_headgear_mid.dds"
    noOfFrames = 12
    norefcount = yes
    can_be_lowres = yes
  }
}

**Comment by loup99** [comment]
No idea. Did you follow this page?`http://www.ckiiwiki.com/Portrait_modding

**Comment by MaelgwnGwynedd** [comment]
As I said in the OP, yes.

**Comment by loup99** [comment]
You said "wikia" guide, so I thought you had followed a guide on the unofficial wikia,

**Comment by MaelgwnGwynedd** [comment]
The ckii wiki is a wikia site.

**Comment by loup99** [comment]
No, it is a "Wikimedia", not "wikia"

**Comment by MaelgwnGwynedd** [comment]
Trust me, it isn't. The wikimedia websites are wikipedia, wiktionary,
wikisource, etc...
Any fan wiki is a wikia.

**Comment by loup99** [comment]
This discussion is off-topic, but I could create a Wiki based upon Wikimedia if I wanted to. As you can see on the bottom of the main page, the CK2 wiki is "Powered by Wikimedia"

**Comment by MaelgwnGwynedd** [comment]
It says Mediawiki, not Wikimedia.

**Comment by loup99** [comment]
Oh yes, you are right. I worded it to be wrong way around.

**Comment by MaelgwnGwynedd** [comment]
Anyway, it doesn't matter, you understood what I meant. I still haven't figured it out.

**Comment by loup99** [comment]
Have you compared with the existant files we have?

**Comment by MaelgwnGwynedd** [comment]
What do you mean?

**Comment by loup99** [comment]
The mod adds some ethnicities based upon vanilla DLCs. Compare with those.

**Comment by MaelgwnGwynedd** [comment]
I can't, they don't have the correct gfx files. I've added romano_british as a new graphical culture.

**Comment by TurtleShroom** [comment]
Well done, Maelgwn!
