### ISSUE TITLE
Romano-British clothing

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#207]
http://image.noelshack.com/fichiers/2016/51/1482517574-ck2-558.png

**Comment by loup99** [comment]
So it does work?

**Comment by MaelgwnGwynedd** [comment]
I fixed it.

**Comment by MaelgwnGwynedd** [comment]
With the help of the graphic designer.

**Comment by loup99** [comment]
OK. Could you push it? By the way, what is his name? I'd like to discuss with him if possible.

**Comment by MaelgwnGwynedd** [comment]
I've pushed it. What do you need to discuss in private?

**Comment by loup99** [comment]
Nothing in private specifically, just thank him and ask him a few things.

**Comment by MaelgwnGwynedd** [comment]
I can pass the questions on if you want?

**Comment by loup99** [comment]
Sure!
Thank him for contributing and ask if he has an account (if he has username for an invitation to group) on the forums.

**Comment by MaelgwnGwynedd** [comment]
Lord Kee.

**Comment by loup99** [comment]
Thank you for the help!

**Comment by MaelgwnGwynedd** [comment]
No problem.
