### ISSUE TITLE
hellenic pagan bugs

### ISSUE THREAD

**Issue by MoffKadir** [loup99/WtWSMS#208]
if the character (in my case, Julius Nepos) changes in the Nicene religion with Hellenic paganism, the solutions do not work in the Roman intrigues, such as "Circus Maxima rebuild" and organize the legions. With what it can be connected? maybe due to the fact that I put a mod to version 2.6.2? as I recall, version 2.6.3 does not add anything special, but a couple of fixes
 P.S. sorry, my english is wrong

**Comment by loup99** [comment]
Could you please post the bug report on our forums? https://forum.paradoxplaza.com/forum/index.php?forums/when-the-world-stopped-making-sense-mod.876/

**Comment by MoffKadir** [comment]
I don't have access to the Plaza, unfortunately

**Comment by loup99** [comment]
Why? I can help you out with registering.

**Comment by MoffKadir** [comment]
i'm pirate XD sorry me

**Comment by loup99** [comment]
We do not provide support for pirated versions.
