### ISSUE TITLE
Sons of Attila

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#209]
While waiting for the next map update and, I decided to renew my interest in Attila the Hun for the sake of the mod.

So here I will detail my endeavours and ideas for the Sons of Attila project (not an official project, just a bunch of Hunnic pushes and Commits).

-Trace the descendants of Attila and add them. They're not very well documented, but basically the main surviving line was through his son Ernak (Hunnic Hérnäk). His son Gordos from the marriage is mentioned in a few texts as having been the first Christian King of the Huns, though when he tried to impose Christianity on his people by destroying their Tengri idols they slaughtered him. He was quite friendly with Justinian and the Byzantines, and visited Constantinople to be baptised, and Justinian gave him many gifts.
-Make the Tengri Faith more Dark-Ages like to reflect how it was in the 5th century rather than, as in Vanille, a few centuries later.
-Add Hunnic languages names. Attila is Attila, but his sons Ellac, Ernak, Dengitzic were actually Ellak, Hérnäk and Dengičig. His wife Kreka was actually Krekän.
-ROMAN SYMPATHY: While I've already detailed my idea about the Chinese Wei Kingdom intervening against the Huns in Europe, who are harassing them quite a bit, the opposite could well have happened. Had Valentinian III not beaten the Huns, his sister would have married Attila and the Huns would have ruled Rome. A clever Italian King or Byzantine Emperor could easily look back at how easy a solution that would have been and apply it to the modern Huns, wedding a daughter of theirs to a son of theirs (or vice-versa) and linking the two. Special flavour events would allow a Romano-Hunnic alliance.

A NOTE:
While Attila died in very suspicious circumstances, we can't ignore the word of Priscus, _who literally met Attila in person_. Given how intimate they'd gotten, I'd trust his account of Attila choking on his food at his wedding to Ildikó. No foul play. It's a very stupid death, but there are worse ones (William the Conqueror died from bumping into the saddle of his horse, which ruptured his stomach which eventually exploded).

**Comment by loup99** [comment]
Ernak is already in the mod, as you probably noticed.

**Comment by MaelgwnGwynedd** [comment]
Not properly.

**Comment by MaelgwnGwynedd** [comment]
Right, I couldn't find any ancestors to Houdbaad and Organa, but they were related through their grandson Kubrat who was a Hunno-Bulgarian king of Great Bulgaria.

I've traced it this way:

20.1.1={
	historical_nomad = yes
}
100.1.1={
	law = succ_turkish_succession 
	law = agnatic_succession
}
360.1.1={
	holder = 76 # Balamür
}
378.1.1={
	holder = 75 # Baltazär
}
390.1.1={
	holder = 74 # Öldin
}
410.1.1={
	holder = 73 # Köridak
}
420.1.1={
	holder = 72 # Öktär
}
432.1.1={
	holder = 71 # Hrögä
}
434.1.1={
	holder = 70 # Blidä
}
437.1.1={
	holder = 66 # Attila
}
453.1.1={
	holder = 67 # Ellak
}
454.1.1={
	holder = 68 # Dengičig
}
469.1.1={
	holder = 69 # Hérnäk
}
476.1.1={
	holder = 1210246 # Quturgür
}
520.1.1={
	holder = 1210249 # Grod
}
528.1.1={
	holder = 1210250 # Muager
}
530.1.1={
	holder = 1210251 # Khinialon
}
540.1.1={
	holder = 1210252 # Sandlikh
}
# The Bulgarians invade
581.1.1={
	liege = k_bulgaria # Bulgars
	holder = 1210253 # Houdbaad
}
617.1.1={
	holder = 1210254 # Organa
}

**Comment by MaelgwnGwynedd** [comment]
I'm unsure how to show the division that happened. While, as far as we know, Attila's first sons Ellak and Dengičig had no offspring (or at least no male offspring), but Hérnäk had two sons Quturgür and Kötrügür. Those two formed tribes named after themselves, which in English is Utigur and Kutrigur. There was a third tribe known as the Altyn Ola, a horde which was a divsion of the Kutrigur. They were ruled by Ellak's third son Djurash Masgut. 

The Utigur are ruled by Hérnäk's son Quturgür. After Quturgür dies, his son Sandlikh is installed as a puppet to the Byzantine Emperor Justinian.
The Kutrigur were ruled by several leaders and eventually Zabergan (Djurash Masgut's grandson) until 582 where a Bulgarian named Gostun of the Ermi Clan took over. Kubrat of the Dulo Clan takes over Gostun's territories.
The Altyn Ola had a fairly standard succession until Boyar Chelbir, a Magyar King, took over in 590. The King of Great Hungary Kubrat later took over Chelbin's territories.

The way I see it the Hunnic Empire should collapse into three different Hunnic Kingdoms, Hérnäk's sons'. These later get taken over by two Bulgarian leaders (Gostun and Chelbir) who are taken over by Kubrat. Great Hungary is formed from these two kingdoms, whose titles are destroyed.
The Utigurs are simply absorbed into the land of the Türks.

The reason they were weak enough to all get invaded was that the Kutigurs (and their Altyn Ola subdivision) and the Utigurs were destroyed by each other and the Byzantine Empire. The remaining Huns were conquered by the Bulgars and Türks respectively.

There is actually a recorded sentence spoken by Sandlikh the Utigur king.
"It is neither fair nor decent to exterminate our tribesmen (the Kutrigurs), who not only speak a language, identical to ours, who are our neighbours and have the same dressing and manners of life, but who are also our relatives, even though subjected to other lords"

**Comment by loup99** [comment]
Two notes:

- Enlil said no on changing the status of the Hunnic empire at start
- Any pre-476 history is subject to conflict with Enlil's future work, which will include a The Scourge of God bookmark

**Comment by MaelgwnGwynedd** [comment]
"Enlil said no on changing the status of the Hunnic empire at start"

But that's how it was organised. It was divided into two territories.

"Any pre-476 history is subject to conflict with Enlil's future work, which will include a The Scourge of God bookmark"

So?

**Comment by loup99** [comment]
- The Kutigurs and Utigurs are separate, with the Hunnic Empire beneath Ernak/Hérnäk
- Just so that you know it

**Comment by MaelgwnGwynedd** [comment]
Then the Hunnic Empire will last an in-game day. It collapsed the same year as the mod starts.

**Comment by MaelgwnGwynedd** [comment]
Note that these were often Fratrilineal. We should probably implement that. (So the kingship passed to each brother before going to the eldest king's son).

**Hunnic Empire**
Balamür (360-378)
Baltazär (378-390)
Öldin (390-412)
Köridak (412-421)
Öktär and Hrögä (421-430) (Brothers of Munčuq, sons of Köridak)
Hrögä (430-435)
Blidä and Attila (435-445) (Sons of Munčuq)
Attila (445-453) (Munčuq)
Ellak (453-454) (Son of Attila)
Dengičig (454-469) (Brother of Ellak) 
Hérnäk (454-476) (Brother of Dengičig)

**Utigur**
Hérnäk (454-490)
Quturgür (490-520)
Sandlikh (540-560)
Anagai and his sister(?) Akagas (560-579) (Children of Sandlikh. Anagai commits suicide but Akagas and her lands remain subjugated to the Türks. The Türk ruler takes over Anagai's lands for himself).
(Subjugated to the Türks)

**Kutrigur**
Hérnäk (454-490) (Son of Attila)
Kötrügür (490-510) (Son of Hérnäk)
Khinialon (510-551) (Kötrügür's Great-Nephew)
Sinnion (551-560) (Random Hun)
Zabergan (560-582) (Cousin of Khinialon through his uncle Alvar)
(Subjugated to the Bulgars)
Gostun (582-584)
Kubrat (584-650)

**Altyn Ola**
Hérnäk (454-481)
Djurash Masgut (481-505) (Eldest son of Hérnäk)
Tatra (505-520) (Son of Djurash)
Grod (520-528) (Son of Tatra. Converts to Christianity and is murdered for melting silver and electrum Tengri idols).
Muager (528-530) (Grod's brother)
Khinialon (530-540) (Muager's brother. "Abdicates" in 540 so the lands go to the rightful heir, which is the eldest brother's son Zelorbes)
Zelorbes (540-582) (Khinialon's nephew)
(Subjugated to the Bulgars)
Boyan Chelbir (582-590)
Kubrat (590-650)

**Comment by loup99** [comment]
We can't touch succession laws, all of it is hardcoded.

**Comment by TurtleShroom** [comment]
THIS is the kind of content I want to work on. This is exciting!

My suggestion is that we split the two or three provinces currently held by the Hunnic Empire into, say, four or five littler provinces. Two will go to the sons as cadet dynasties, as OP mentioned. Each of those two sons will be their own Clan using the Vanilla Clan system. That will look odd, but it is the best possible way to simulate the cadet branches of Attila ruling their own little fiefs under the proper Hunnic Empire.

I have said this in my Branch before, and I will say it again. "The Hun" and "Scourge of God" were contemporary nicknames applied to Attila while he was alive. "Attilid" is pure conjecture, and it doesn't sound nearly as bad-A as "Timmy the Hun", or whatever name you give their sons.
"Attilid" is pure conjecture, and unlike Genghis Khan (whose surname was Borjigin), we do not know the true surname of Attila. Until we find out his true surname, we should stick with "the Hun". It sounds cooler and is far more representative of the time period than the generic name assigned to all illegitimate children who spawn their own dynasty.

**Comment by TurtleShroom** [comment]
![the hun cadets](https://cloud.githubusercontent.com/assets/17663470/21666630/ebf3915e-d2c0-11e6-9519-1ad4afec44a9.png)

Here is my proposed change to the Map. This is a close-up of the Crimea. I have added two provinces for Quturgur and Kotrugur. (If OP has a suggestion on where to divide them, let me know.)

The RGB code of the province on the right is 255-0-128. 

The RGB code of the province on the left is 255-52-128.

**Comment by TurtleShroom** [comment]
You might also find these links of interest: 

- http://archiver.rootsweb.ancestry.com/th/read/GEN-MEDIEVAL/1996-11/0846958781
- http://www.angelfire.com/ego/et_deo/asia2europe.wps.htm (Grod is at the bottom)

Also, I found a full source backing up @MaelgwnGwynedd on Grod becoming Christian: https://books.google.com/books?id=hEuIveNl9kcC&pg=PA10&lpg=PA10&dq=%22Grod%22+Attila+the+Hun&source=bl&ots=DJGwafNfWv&sig=4dEawKR889MOwp8x4iSn82WW5mM&hl=en&sa=X&ved=0ahUKEwjF8YzS-6nRAhWD14MKHaOFBsYQ6AEIJzAC#v=onepage&q=%22Grod%22%20Attila%20the%20Hun&f=false . 

Grod's reference is at the very bottom of the chapter concerning the Huns, right above the chapter header reading "The Western Turkish Empire".

**Comment by loup99** [comment]
The answer to your suggestion is no, it won't be implemented.
