### ISSUE TITLE
Warrior Culture

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#211]
Since the Northern Barbarians were neither feudal nor tribal, may I, like our custom Bureaucracy system, create a Warrior Society system? It would be generalised for the Scandinavians, Germans, Britons, etc...

**Comment by loup99** [comment]
Why? What would the difference with tribal be?

**Comment by MaelgwnGwynedd** [comment]
Tribal just does not represent their society at all. It would take too long to explain.

**Comment by loup99** [comment]
Tribal already covers vast groups though. If you just want to rename "tribal" because it is too long to explain concrete differences, then I don't see the need for change in the immediate, until a larger scope has been determined. There have been many suggestions around this though.

**Comment by MaelgwnGwynedd** [comment]
Specifically for warrior cultures? Where and when?

**Comment by MaelgwnGwynedd** [comment]
And no, it's not renaming tribal, it's changing the way the government works.

**Comment by loup99** [comment]
Not specifically in the same format as you, no.

But what exactly do you want to do in changing how it works which is so tough to explain?

**Comment by MaelgwnGwynedd** [comment]
It's not tough to explain, it's just painstakingly long.

**Comment by loup99** [comment]
I understand that, but if it such a significant change and major system you want to implement, it will have to be reviewed and discussed a lot, especially as we haven't planned to add so deep new government types.

**Comment by MaelgwnGwynedd** [comment]
There's not much to review, really. Tribalism wasn't in use by the northern tribes, nor was feudalism.

**Comment by loup99** [comment]
I have understood that you think that, but without any justification for it or explanation on what you want to replace it with I can't possible answer on whether it would be appropriate or not.

**Comment by MaelgwnGwynedd** [comment]
Well for one you had warriors out of respect. Cripples should not be
allowed to have titles. New villages and such should be bought with
prestige. Oathbreaking should make you lose massive amounts of prestige.
Execution doesn't get you penalties with your vassals since it's seen as
good and honourable. Owning too much land is seen as tyrannical. Being
generous gives you a lot of prestige. Too much peace (no raiding or wars)
makes people dislike you since warrior societies rely on war. Hurting or
offending people gives an opinion to their whole family since they had kins
and weren't very independent. That's naming just a few.

**Comment by TurtleShroom** [comment]
TBH, none of that can be coded through the government menu. What I suggest is that we add "Warrior Hall" as a government type and make all of the things you listed up there scripted conditions, triggers, modifiers, and so on that depend on having Warrior Hall as a government.

However, I do need to restate that the Saxon Pagan/Wodenic heresy has been updated and fixed, and is ready for implementation. I have not flipped any provinces or names, however.

**Comment by TurtleShroom** [comment]
What conditions are needed for a Warrior Hall to spawn? Do certain cultures spawn it if they are tribal-type, like, an automated Event converts a Tribesman who becomes Angle or Saxxon (etc.) to Warrior Hall?

Have you considered using the "HORDE = YES" modifier in the Cultures file to make them more aggressive?

**Comment by MaelgwnGwynedd** [comment]
No, they weren't a horde in any sense of the word or game function.

And why a warrior hall?

**Comment by loup99** [comment]
> Well for one you had warriors out of respect. Cripples should not be
> allowed to have titles. New villages and such should be bought with
> prestige. Oathbreaking should make you lose massive amounts of prestige.
> Execution doesn't get you penalties with your vassals since it's seen as
> good and honourable. Owning too much land is seen as tyrannical. Being
> generous gives you a lot of prestige. Too much peace (no raiding or wars)
> makes people dislike you since warrior societies rely on war. Hurting or
> offending people gives an opinion to their whole family since they had kins
> and weren't very independent. That's naming just a few.
> 
Most of it is not moddable for governments or already in the game. What you list does however not justify a separate government system, more laws and flavour events. As for warrior halls, I don't get it and it sounds strange. I don't see the connection with hordes either, but it indicates that this does indeed need to be clarified. If your intent was to replace tribals with hordes my answer is no.

**Comment by MaelgwnGwynedd** [comment]
It does justify another government type. Using tribal or feudal is
completely wrong.

And most of what I said *is* moddable.

**Comment by loup99** [comment]
- Cripples should not be allowed to have titles.
Can not be done directly as a government AFAIK, would need events which take a heavy load on performance.
- New villages and such should be bought with prestige.
Do you mean buildings or holdings? If it is holdings it would need events which take a heavy load on performance. If it is buildings tribals already have it.
- Oathbreaking should make you lose massive amounts of prestige.
As in truces? That is already the case.
- Execution doesn't get you penalties with your vassals since it's seen as
good and honourable.
This is more a law and already partially in.
- Owning too much land is seen as tyrannical.
There are limits.
- Being generous gives you a lot of prestige.
The trait? Not related with government.
- Too much peace (no raiding or wars) makes people dislike you since warrior societies rely on war. 
Covered by religion.
- Hurting or offending people gives an opinion to their whole family since they had kins and weren't very independent.
I don't see how this is possible unless via event, and again it isn't related to government,

**Comment by MaelgwnGwynedd** [comment]
Religion doesn't matter. Christian Saxons, Britons and Norsemen were just
the same regarding war.

**Comment by MaelgwnGwynedd** [comment]
Whatever. Keep feudal I guess, but it's as ridiculous as India being feudal
in Vanilla. Comical.

**Comment by loup99** [comment]
Not likely to happen as we plan on working on governments.

**Comment by MaelgwnGwynedd** [comment]
But not Warrior Societies, which constitute a quarter of Europe in the
Migration Period.

**Comment by MaelgwnGwynedd** [comment]
Also, false faiths did not exist in the Migration Period. Everyone believed
in every God.

**Comment by loup99** [comment]
Warrior bands is something which has been suggested and provided, as well as associated governments. 

What do you mean by false faiths?

**Comment by MaelgwnGwynedd** [comment]
Not warrior bands, warrior SOCIETIES.

**Comment by MaelgwnGwynedd** [comment]
Faiths that are considered false. False faiths.

**Comment by MaelgwnGwynedd** [comment]
Christians believed in Woden, Saxons believed in Beli, Buddhists believed
in Christ.

**Comment by loup99** [comment]
Warrior bands that tie into government is what has been suggested.

What do you want to say with false faiths? That there is a need for more heresies? How does it concretely tie into what was previously said? I'm afraid I don't get you at all.

**Comment by MaelgwnGwynedd** [comment]
1066: "Fucking Pagans, they believe in fake Gods who don't exist"

500: "The Pagans gods exist but ours is/are better"

**Comment by loup99** [comment]
Yes, and what does that mean concretely in relation to this discussion? Is it something you want to add?

**Comment by MaelgwnGwynedd** [comment]
Yeah, right now we have anachronistic faith penalties, like "false faith",
which shouldn't exist.

**Comment by loup99** [comment]
Oh, the dislike between faiths? That will stay, if only for gameplay reason in that there was serious conflicts between religions.

**Comment by MaelgwnGwynedd** [comment]
At least rename it.
