### ISSUE TITLE
Randomly blank

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#212]
Some places are randomly blank (leaderless, greyed out) for no reason.

**Comment by loup99** [comment]
They don't have any history.

**Comment by MaelgwnGwynedd** [comment]
No.

**Comment by MaelgwnGwynedd** [comment]
Lancaster is blank and yet

470.1.1={
	holder = 1210062 # Gwrast Lledlwm
}
472.1.1={
	holder = 1210063 # Meirchion Gul
}
475.1.1={
	holder = 1210315 # Eliddyr Llydanwyn
}
560.1.1={
	holder = 1210316 # Llywarch Hen
}

**Comment by MaelgwnGwynedd** [comment]
Sussex is blank and yet

# Rhegin
460.1.1={
	holder = 1210334
}
477.1.1={
	holder = 5 # Ælle of Sussex
}
512.1.1={
	holder = 190104 # Cissa of Sussex
}
567.1.1={
	holder = 190105 # Osric of Sussex
}
600.1.1={
	holder = 190106 # Ælle II of Sussex
}
612.1.1={
	holder = 190107 # Noðhelm of Sussex
}
660.1.1={
	holder = 190108 # Æthelwealh of Sussex
}

**Comment by loup99** [comment]
In that case there is some issue with the code.
