### ISSUE TITLE
Odoacer

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#213]
What is our stance on his ancestry? Full german or half-hun?

**Comment by loup99** [comment]
Hunnic descent hasn't been discussed. The debate on Odoacer has been entirely centered around his Germanic or Roman background, and how to represent that.

**Comment by MaelgwnGwynedd** [comment]
I thought he didn't have a Roman background.

**Comment by loup99** [comment]
Background as in descent no, I meant more "influence"

**Comment by MaelgwnGwynedd** [comment]
Oh I see. Well, his background was far more Hunnic. Whatever his ethnicity, he and his brother were definitely raised as wards of Attila in the Hunnic Empire.

The main problems are:
-What ethnicity was his father Edeko? Edeko was a close friend and commander of Attila's, and leader of the Sciriian tribe that was subjugated to the Huns. Was Edeko already commander before Attila came (so a native Sciriian) or was 
-Who is his mother? A safe bet is a Scyrian or Hunnic woman.
-Odoacer has a hunnic name (Ottoghar) with no apparent Germanic etymology. His brothers Hunulf and Harmatius have Germanic names.
-Harmatius may not be their brother. A contemporary account (John of Antioch)'s statement about his death at the hands of Hunulf may be read as "Onoulphus killed his brother Armatus" or "Odoacer was the brother of the Onoulphus who killed Armatus". That said, Harmatius liking Onoulphus so much (making him advance through military ranks, lending him _huge_ sums of money) does suggest they were brothers.
-Edeko may have been a son of Hroga ("Rugila"), Attila's uncle, making the two cousins, and Odoacer a removed cousin of Attila.
