### ISSUE TITLE
Archbishops of London

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#214]
Shall I add the Archbishops of London, both Romano-British and Anglo-Saxon? 

Theanus (186-193)
Elvanus
Cadwr
Obinus
Conanus
Palludius
Stephanus
Illtutus
Dedwinus
Thedredus
Hilarius
Restitutus
Guidelinus
Fastidius
Vodinus (-453): Martyred by the Saxons.
Theanus II (-486): Fled to Wales
(NO ARCHBISHOPS)
Mellitus (604-617)
(NO ARCHBISHOPS)
Cedd (653-664)
(NO ARCHBISHOPS)
Wine (666-672)
(NO ARCHBISHOPS)
Earconwald (675-693)
[...]*

*Not really important to our mod after that.

**Comment by loup99** [comment]
In charge of the church holding? You could, but they may get shuffled around when we overhaul Britain.

**Comment by MaelgwnGwynedd** [comment]
And why would they get shuffled around?

**Comment by loup99** [comment]
The holdings and province shapes may change.

**Comment by MaelgwnGwynedd** [comment]
I've already given Britain the correct provinces in my pull request.

**Comment by loup99** [comment]
What you have altered is history, not provinces or the map.

**Comment by MaelgwnGwynedd** [comment]
I known that. But the provinces are correct.

**Comment by loup99** [comment]
What do you mean? We are going to change the provinces in the map overhaul.

**Comment by MaelgwnGwynedd** [comment]
The ones in Britain are correct, no need to change them.

**Comment by MaelgwnGwynedd** [comment]
There's no need to.

**Comment by loup99** [comment]
I don't know what you mean, because we have already started planning for a complete overhaul.

**Comment by MaelgwnGwynedd** [comment]
What don't you understand? British provinces don't need an overhaul.

**Comment by MaelgwnGwynedd** [comment]
What do you mean all sources indicate the setup is wrong? The vanilla province setup is fine for Britain.

**Comment by MaelgwnGwynedd** [comment]
And no, given the catastrophic state some of the kingdoms were in (or are, since my commits aren't being pulled), I'd rather intervene now.

**Comment by loup99** [comment]
I'm not going to explain why we are doing Operation Ptolemy as it is not up for debate anyway and we post things about it every week. The mod development is mainly on the forum with this as a platform for sharing files, and those who don't want to follow there will have to deal with not being involved in decision-making. 

The entire setup in the British Isles does need a major overhaul. Our setup and borders correspond to no historic map of the area, as names, borders and rulers are less than optimal. That is why it will get an overhaul, and if you dislike the province changes that is unfortunate but not something we will be able to please.

**Comment by MaelgwnGwynedd** [comment]
I want to follow there, son't pretend it's not YOUR fault and decision I'm
not on the forum.

**Comment by MaelgwnGwynedd** [comment]
I HAVE overhauled it, for fuck's sake. The provinces, rulers and names match up exactly. Have you even read my push?

**Comment by loup99** [comment]
I have already answered the topic you mention in your first comment, and not going to play some sort of witch-hunt or blame-game. Swearing or irritation won't change my comment to which you replied. Again, don't feel any obligation to be a part of anything if you disagree with the choice of using the Paradox forums and respecting Paradox.
