### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#215]
Do I have your permission to use what's been made of WTWSMS so far and create my own mod from it? I'm sorry, but I just don't agree with the direction WTWSMS has been taken in.

**Comment by loup99** [comment]
You can create a sub-mod. Taking the entire mod and creating something separate which you release with it included is not something Enlil would agree to.

**Comment by MaelgwnGwynedd** [comment]
Then tough luck to him. Sorry it had to come to this.

**Comment by loup99** [comment]
Come to what? He has been explicit enough with an answer, that I don't think is subject to change. I haven't contributed much myself, nor innovated with anything, but what the others think will be enforced. Do a sub-mod, or create something from scratch if you prefer to not use WtWSMS content.

**Comment by MaelgwnGwynedd** [comment]
That I have to use the files without Enlil's permission. I am creating my
own mod from my WTWSMS branch, not a sub-mod.

**Comment by loup99** [comment]
It won't have to come to anything. I have explained why you are not allowed to use WtWSMS files. Two simple reasons:

- You don't have the consent to use WtWSMS files
- You don't have the consent to use other mods which WtWSMS includes.

**Comment by MaelgwnGwynedd** [comment]
I don't care about consent. I'm using them.

**Comment by loup99** [comment]
It isn't about consent, it concerns modding.
