### ISSUE TITLE
Your innacurate province map

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#217]
Let's see your innacurate province map.

**Comment by loup99** [comment]
It doesn't exist

**Comment by loup99** [comment]
There is no set province map which has been decided.

**Comment by MaelgwnGwynedd** [comment]
Oh good, since there's no need to tpuch anything in Britain.

**Comment by MaelgwnGwynedd** [comment]
The borders and provinces are correct.

**Comment by loup99** [comment]
First of all, I'm not in charge of the map or the history. Secondly, I will repeat that Ptolemy is interactive. Thirdly, I don't know why you are unhappy with those using the mod and the other developers discussing the map on the completely different projection before your changes are reviewed, but that is how it is.

**Comment by MaelgwnGwynedd** [comment]
Because I know about Britain and how it was organised. Ptolemy is not
interactive if you leave people out of it. And I don't give a fuck who is
in charge, bring them here, since you had me banned from the forum and seem
intent on prohibiting me from doing the slightest fucking thing for this
mod.

**Comment by loup99** [comment]
So you do know the map we are using? Good, then explain why it is accurate and the sole area which doesn't need an overhaul, even though we have been discussing and promising it for years? I have already said what I know, and as you seemed to understand, it wasn't subject to change. 

Do I need to link the issues discussing the other matter? Because that discussion has already ended.

**Comment by MaelgwnGwynedd** [comment]
You're a stubborn cunt. The province map in the mod for Britain right now
is correct. What isn't getting through your fucking thick skull?

**Comment by loup99** [comment]
MaelgwnGwynedd, if it is by insulting others that you explain why the map is accurate you know that i think there is no discussion to be had.

**Comment by MaelgwnGwynedd** [comment]
You're not interested in discussion.

**Comment by MaelgwnGwynedd** [comment]
It's accurate, that's all I have to say.

**Comment by loup99** [comment]
I have explained in what I'm interested. If the new map is accurate, you know what you can do in this issue.

**Comment by MaelgwnGwynedd** [comment]
http://www.historyfiles.co.uk/images/Britain/Britain/MapAD450.jpg

My map is accurate you fucking moron.

**Comment by MaelgwnGwynedd** [comment]
Why are you so dumb? The borders in 1066 will be wrong, as well as the 476 ones. It will all be wrong. There are no provinces that need to br changed in Britain!!!!

**Comment by MaelgwnGwynedd** [comment]
Here, maybe if you pull your head out of your arse you'll see. http://image.noelshack.com/fichiers/2016/27/1467925241-cities-of-500-ad-britain-11.png

**Comment by TurtleShroom** [comment]
MAEL, by glob, quit being such an A-hole. I agree that the provinces in the British Isles don't need to be changed, but you are doing yourself ZERO favors by acting this way.

Here is a better idea. When the provinces change, correct them, not by saying the old was better (though it is), but by maling due.

@Loup99 , Mael has demonstrated his expertise in this region for a lomg time. He is almost certainly right.
