### ISSUE TITLE
Random CTD

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#22]
There is, in the current version, a completely random CTD that fires occasionally. It is an important priority to get it fixed ASAP.

**Comment by loup99** [comment]
Is this the old issue since CM and 2.2.1 that was never fuxed (?) or is it a new one?

**Comment by rquinio** [comment]
I don't have much experience in random CTDs, but if it's like the blank event popups, it can be a needle in a haystack ...
My take on this is to use the Validator (http://forum.paradoxplaza.com/forum/showthread.php?597480-The-Validator-Find-errors-quickly-and-with-minimal-pain!) as it will fix other bugs in the process and make the remaining ones more visible.
Problem: currently there is an insane amount of issues raised by validator, so I can only imagine it will be a long process.

**Comment by loup99** [comment]
Yes, it is the same. I know the Validator, but my copy shows 0 issues for some reason. :tongue:

**Comment by loup99** [comment]
I believe we also might have inherited some of the VIET Immersion issues in our integration of the mod. Anyway, that is the most popular flavour in, so we are not removing it.

**Comment by loup99** [comment]
[QUOTE=nogluten;18654802]I have a bit more info on the 'random' crash I get. It happens every 20ish years on February 2nd, and there doesn't seem to be any cause[/QUOTE]
More info on it, seems like it is quiet fix in at what point of time it happens.

**Comment by rquinio** [comment]
Damn those random CTDs.... They're definitely still here, and seem more frequent at highest speed.
At this point I would consider removing VIET and MZ events and decisions until their integration is re-done, see if that improves things...

**Comment by rquinio** [comment]
Seems to be fixed with 0.9.6 / patch 2.4 ?

**Comment by loup99** [comment]
Yes, it does. Not sure if it was the duplicate characters or not or some other issue that was fixed in the validating process.

**Comment by rquinio** [comment]
Solved !
