### ISSUE TITLE
Noreligion bug

### ISSUE THREAD

**Issue by Lietuvis** [loup99/WtWSMS#220]
I wanted to play as Julius Nepos and i wasn't allowed to play and i noticed that it said that he was noreligios.I cheeked every nation and i was allowed to play as only one and the only religious nation

**Comment by loup99** [comment]
Give us more details (version of the mod, version of the game etc)

**Comment by Lietuvis** [comment]
I'm using the newest version of the game and the previous version of the mod.

**Comment by loup99** [comment]
The newest version of the game!? Miraculous that it loaded! I'm astonished.

**Comment by Lietuvis** [comment]
Ok thank you.
