### ISSUE TITLE
EU4 Converter Compatibility

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#222]
As some files were sent to me, I will upload them to a branch here so that they are accessible. 

Here is the thread dedicated to it: https://forum.paradoxplaza.com/forum/index.php?threads/wtwsms-converter-work-thread.833271/

**Comment by IhateTrains** [comment]
Do we have a map with province IDs like [this](http://www.ckiiwiki.com/File:Numbered_province_map.png)?

**Comment by loup99** [comment]
No, we don't. There is a tool by @NicolasGrosjean which is helpful for identifying provinces though: https://github.com/NicolasGrosjean/Province_identifier Maybe that could help you out?

**Comment by IhateTrains** [comment]
Yes, definitely. Thanks :D
