### ISSUE TITLE
What Happened to My Changes That You Implemened?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#223]
Good afternoon.

I was looking through the files of the latest incarnation the Mod, and I am extremely frustrated that the changes made in https://github.com/loup99/WtWSMS/pull/198 . Why did you revert them?

This is outrageous, and the conditions for the Priscillians (and some other Gnostics) are ridicuous. Why did you change it back after you agreed to implement it? I am very disappointed and upset at this. What happened?

-TURTLESHROOM

**Comment by TurtleShroom** [comment]
This was the code you revoked.

[code]
create_priscillian_patriarchy = {
only_playable = yes
is_high_prio = yes
potential = {
religion = priscillianism
NOT = { is_title_active = d_priscillianism }
age = 16
prisoner = no
NOT = { trait = incapable }
}
allow = {
piety = 1000
trait = vegetarian
martial = 8
learning = 8
OR = {
owns = 198
any_realm_lord = {
owns = 198
}
}
}
effect = {
give_nickname = nick_with_immortal_soul
set_global_flag = veggiepriest
activate_title = { title = k_priscillianism status = yes }
hidden_tooltip = {
create_character = {
name = "Priscillian"
dynasty = none
trait = humble
trait = vegetarian
trait = zealous
trait = mystic
race = egyptian_arabic
religion = priscillianism
culture = ROOT
female = no
attributes = {
martial = 8
intrigue = 10
learning = 10
}
historical = yes
}
new_character = {
k_priscillianism = {
grant_title = PREV
}
b_avila = {
grant_title = PREV
make_capital_holding = yes
}
wealth = 0
opinion = {
who = ROOT
modifier = opinion_creator_of_rel_heal
}
}
religion_authority = {
modifier = patriarchy_instituted
years = 20
}
}
piety = 1000
}
revoke_allowed = {
always = no
}
ai_will_do = {
factor = 1
}
}

The current version is abominable.

**Comment by loup99** [comment]
I did as agreed:

> The **minor bugfixes, graphics additions and localisation changes** from this have now been **merged**. **What was left otherwise** either generated Validator complaints, either was unused or had been discussed and were thus **not integrated** as said above.

**Comment by TurtleShroom** [comment]
Understood.

It's now here: https://github.com/loup99/WtWSMS/pull/224

**Comment by TurtleShroom** [comment]
@loup99 

You can close this Issue now. However, I'd appreciate a review of what I have over there thus far.
