### ISSUE TITLE
Crash when clicking on Equites Colonia

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#225]
Good evening.

I will make it short and sweet.

When I click this character:
![glitch](https://cloud.githubusercontent.com/assets/17663470/26022199/62f328ea-376c-11e7-962e-f48086f6c651.png)

That causes the game to crash. I have no idea why, nor do I know what is going wrong. It also crashes when I mouse over it and a tooltip appears.

Thank you for your assistance.
-TURTLESHROOM

**Comment by loup99** [comment]
I will look into it
