### ISSUE TITLE
Where Can I Get a Copy of the Validator Outside the Forums?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#226]
Good evening.

Due to corruption, bad scripting, or general stupidity, Paradox makes it impossible to access its Forums unless you are logged in _and_ registered (AKA you paid them to access the forums). I've been banned since last year. (Apparently, saying "I did Nazi that coming" [IS FROWNED UPON IN THIS ESTABLISHMENT](https://www.youtube.com/watch?v=K3klJvTHGJA)!)

Due to poor scripting, when I log in as my banned account, the _entire_ Forum shuts down and I can not only view anything, but I _cannot even log out_.

This is a serious problem, because I was just informed that the Validator has updated. The only place I can find a link to the Validator is [on the Forums](https://forum.paradoxplaza.com/forum/index.php?threads/the-validator-find-errors-quickly-and-with-minimal-pain.597480/), which means I cannot get my hands on the most up to date copy.

I need that update in order to work on the Mod to the best of my ability.

Does anyone have a copy of the Validator that they are willing to share with me?

Thank you.
-TURTLESHROOM

**Comment by loup99** [comment]
Nowhere.

**Comment by TurtleShroom** [comment]
Well gee, maybe you could share me your copy then? Just because the developer isn't bright enough to put the dang thing outside a pay-wall shouldn't mean that I am screwed!

**Comment by TurtleShroom** [comment]
@loup99 

Please reopen this issue. I need a copy.

**Comment by loup99** [comment]
If my previous reply wasn't clear enough, it is no.

**Comment by TurtleShroom** [comment]
Do you have any justification to deny me an update to a vital tool that is freely distributed to everyone and allows itself to be shared, other than your sudden and unexplained decision to become a collosal A-hole?

**Comment by TurtleShroom** [comment]
Or, have you suddenly come to hate me and are trying to subtly tell me my work is not welcome here by making it harder for me to code?

**Comment by TurtleShroom** [comment]
If the Validator's author forbids third-party distribution, then I understand.

**Comment by loup99** [comment]
Could we please avoid to over-dramatise everything? I thought you had read the Paradox User Modding Rules. I'm not allowed to redistribute the Validator as I'm not the owner of it and it is only to be distributed for those with access to the forums.
