### ISSUE TITLE
Written or oral names?

### ISSUE THREAD

**Issue by AzimuthBlast** [loup99/WtWSMS#228]
Between 600 BC and 800 AD, regardless of how it was _pronounced_, names were written the same.

I wonder if we shouldn't "rectify" that. For example, a Duke "Lupus" in 700 AD Frankia would be pronounced "Lop". Should we maybe call him Lop? Same for other names. Ferreolus at this point was pronounced Fèrrèol, and "Petrus" pièðr. Would it be better to have everyone in the entire West have a Latin name, or reflect cultural pronunciations?

**Comment by TurtleShroom** [comment]
Why not both? Most of the cultures could use more names. 

Obviously, nations that have non-Latin alphabets should use Romanized versions (and Pinyin or a Romanized equivalent for Chinamen, Japanese, and other languages like it), but the other ones could use "Lop" and "Lupus" as part of the random naming list.

**Comment by AzimuthEmp** [comment]
The problem is they would not spell it "Lop", only pronounce it that way. It's a question of whether we'd like Lupus or Lop. I think we should ask Loup what he thinks.

**Comment by loup99** [comment]
The cultures do not only reflect the spoken language, they also reflect customs and local traditions. Many languages did not posses their own written languages at the point of time which the mod covers, so you will indeed find that Latin was used in written sources. That does not mean we will use the Latin for all cultures, so to that regard we use the names as they were spoken, not how they were written down in Latin.
