### ISSUE TITLE
Attilid Dynasty (Attila's Dynasty 1042167) Naming

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#229]
Good evening.

I've said it every time I have contributed to this Mod, and I am still ignored when I bring it up. I said that "Attilid" is a horrible name for Attila the Hun's dynasty, because the "-id" suffix is a default for all Altaic cultures that generate random dynasties by the surname.

No one believed me, but now, I have PROOF!

![20170517154657_1](https://cloud.githubusercontent.com/assets/17663470/26288341/e2e427e6-3e5d-11e7-88e9-cabfac762cd7.jpg)

What you are looking at is a manifestation of the problem. This Hunnic Khanate is _**NOT**_ Attila the Hun's dynasty, but it is still called ATTILID. It confuses the viewer and is not kind to Mod immersion, as it is is historically inaccurate for there to be any other Hunnic family with a name like that of Attila the Hun.

Attila the Hun was too important in history, and far too important in this Mod's time period, to have generic dynasties take his name.

**Attila the Hun's dynasty needs an unique name.** When the Mod was originally designed, "the Hun" (Attila's nickname) was also used as the House name (leading to characters like "Dooley the Hun"), because Attila the Hun was (and is) the greatest and first among all Huns. 

To call him and his family THE Hun makes historical sense: he earned his nickname while he was alive.

However, I am open to alternate names besides "the Hun". "Flagellum-Dei" ("Scourge of God") would be an awesome Dynastic name as well.

Since Loup is too stubborn to consider it in the middle of a Branch, I've decided to post it here for general discussion.

Thank you.
-TURTLESHROOM

**Comment by loup99** [comment]
That is an issue, but I don't have idea on how to solve it as it is a hardcoded behaviour (we can't restrict specific names). The only solution I could see would be to find a variant of "id" which still corresponds to the Huns and contains "Attila" in it.

**Comment by TurtleShroom** [comment]
I still rest my desires on House "the Hun" or House "Flagellum-Dei".

**Comment by loup99** [comment]
None of these cases fit in with the general rules for naming dynasties in the mod, so no. While Latin is better than English for reasons stated previously (you can drop "the Hun", I already explained why that suggestion isn't possible) it still doesn't fit in immersion-wise and we know the name is inaccurate. I'd prefer to try to find something which fits in, because otherwise Attilid remains better.

**Comment by AzimuthEmp** [comment]
For starters, it should be Attilanid, not Attilid (this is the form encountered in modern texts, the latter just doesn't really exist, it's auto-generated by the game). Secondly, in the Hunnic language "son" would be something like kilí, so Attíla Kilí. or Attílakili (alternatively Attilakíli, some compounds did not preserve stress patterns). But historically we know the Huns just called themselves the (ANCESTOR NAME) Huns. They'd just have been known as the Attila Huns. House Attíla would be best, but then he'd just be called Attíla Attíla, which is silly.

I can only reccomend Attílakili.

**Comment by loup99** [comment]
With commit 27a3563fdd15db70cc0c58ac45eba71adb718968 this issue has been resolved.
