### ISSUE TITLE
Mod Integration

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#23]
This is the issue dedicated to the other mods integrated. What we have in WtWSMS is: Mazdayasna Zarathushtrish, Ancient Religions, Patron Deities and VIET. These mod needs to be adapted in order to fit the new setting. Two of them are based on restoration (Ancient Religions and Mazdayasna), while two others is general flavour, inmmersion (Patron Deities and VIET). I will post info about each of them here. If any other mods were to be integrated, explicit permission is needed.

**Comment by loup99** [comment]
For integrating Mazdayasna Zarathushtrish fully into the mod. The events need to be tweaked and adapted to the startdate. The latest version maintained by starwarsfan54 is the one that needs work; link to the thread: http://forum.paradoxplaza.com/forum/showthread.php?622444-MOD-Mazdayasna-Zarathushtrish-Zoroastrianism-expanded

**Comment by loup99** [comment]
For the integration of Ancient Religions: the events need to be adapted/tweaked and certain conditions adjusted/expanded. Celtic are very powerful on the Isles, so perhaps one holy site could be moved towards France. The latest version is the https://github.com/xirsoi/ancientreligions branch, as far as I know. Romullien worked with this, or atleast with reintegrating it so that the events would fire.

**Comment by loup99** [comment]
And then there is VIET. I was the one who pushed Enlil to integrate it, but it contains tons of flavour events and traits (almost all of the new traits in this mod are from VIET) that is really popular. It is a part of HIP and maintained by two authours; Cybrxkhan and OrdepNM. The thing with it is that it is not fully compatible with vanilla at the moment (Immersion being rewritten), so what we use is a version that is only maintained in this mod. 

The thread: http://forum.paradoxplaza.com/forum/showthread.php?652025-MOD-Vanilla-Immersion-Events-and-Traits-A-Modular-Flavor-and-Tweak-Mod.

**Comment by loup99** [comment]
Patron Deities is a mod that was supposed to be integrated, but seems to have gotten lost in the progress, I will try to notify the authour and ask.

**Comment by rquinio** [comment]
Regarding AncientReligions, I noticed that religion keys were different, requiring an error-prone find/replace:
- I'm going to proposed that druidic be renamed celtic_pagan in ACR, as both WtWSMS and CK2+ use this, and I think it's closer to vanilla xxx_pagan convention.
- For ancient Egyptian religion (which I'm retrofitting from CK2+ to ACR), they used egyptian_pagan which I think is better than kemetic_pagan. Would that be ok to rename it in WtWSMS ?

**Comment by loup99** [comment]
For the first, I berlive that superskierpat was in the middle of an overhaul when he stopped developing the mod. Yes, it would be OK, as long as it stays "Kemetic" in game, as we do not have any other good name.

**Comment by rquinio** [comment]
I'll redo ACR integration with v0.36, once it is released.

**Comment by loup99** [comment]
Ok, great! Do we have the exact same holy sites as ACR?

**Comment by rquinio** [comment]
No, but I'll keep the changes done for WtWSMS :)

**Comment by rquinio** [comment]
Ok, I'm starting the retrofit of ACR v0.36.1. Hope that won't be too much of headache !

**Comment by loup99** [comment]
Romulien this event fired in my test-run with the Franks:
[img]http://i.imgur.com/pLQNkxS.png[/img]
In itself it seems OK (you probably know the background information better than me) but the issue with it is the localisation that says "with the conversion of". Would it be sufficient to have this present at start, or just removing the conversion part, starting with "A number of..."?

**Comment by rquinio** [comment]
Ok, fixed it so that Wolftails are present at start, since a number of provinces are celtic_pagan !

**Comment by Arcvalons** [comment]
Hello. I checked the MZ decisions, and the oddest ones are the "Rebuild Ctesiphon Library" [It hasn't been destroyed, plus it's missing localisation], and the "Rebuild Narwhal Canal" [Again, it hasn't been destroyed].

Now, should province modifiers for an existing Ctesiphon Library and for the Narwhal Canal be added, or should these decisions be removed altogether?

**Comment by loup99** [comment]
Yes, those should be added in. Thank you for noting that!

**Comment by loup99** [comment]
Concerning this, do you two @rquinio and @Arcvalons have an idea of why the Bureaucratic Government form does not work together with the Hellenic religion? http://forum.paradoxplaza.com/forum/index.php?threads/wtwsms-bug-reports-technical-issues.827028/page-42#post-20289002 I thought you might have a clue, I haven't been able to figure it out.

**Comment by Arcvalons** [comment]
Hmm, I don't know, it should work regardless of religion so long as it isn't muslim. Government type mechanics aren't very clear, but it may be with the hellenic religion itself, as in, if it's not completely feudal and allows hereditary city/temple holders that may be causing some conflict. But I don't think that is the case, right?

**Comment by loup99** [comment]
I'm unsure actually. I wonder if a reformed Norse can hold the title, or if there is some different adaptation to do.

**Comment by Arcvalons** [comment]
Right now there are several employment decisions scattered through the mod, including the VIET ones. I was thinking about merging them into a single file, as otherwise they are all over the decisions menu. Not nice to look at. Could we use the "Toggle X Decisions" thing that HIP uses? 

There's also a missing decision icon for the "Employ Diplomat" decision. How do I upload non-text files to a repository?

**Comment by loup99** [comment]
We can't use HIP stuff without HIP permitting us to do it.

**Comment by loup99** [comment]
Are we using CK2Plus stuff?

**Comment by rquinio** [comment]
@loup99 No not really, there's just ACR_other_event.txt with the minor "go pagan" thing.

**Comment by loup99** [comment]
OK, that was what I thought. I think will remove that, it is buggy and a bit out of scope.

**Comment by rquinio** [comment]
I propose to close this issue as it is quite big already, and I believe the work stated in original post is now done (feel free to re-open if not !)
Separate issues can be created for each mods that need to be tweaked, or for new versions of the mods.
