### ISSUE TITLE
THIS... IS... SPARTAAAA!!

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#231]
![sparta](https://user-images.githubusercontent.com/17663470/27458643-24eedfea-5778-11e7-9558-59da50c74872.jpg)

Good evening.

As a final part of my current Pull Request, I am adding some flavor for those fortunate enough to restore Sparta. I am posting it here to alert everyone and get it through faster.

The following features will be added:
1. "K_SPARTA" will now be created by a special Decision by Tsakonian Pagans instead of from the "CREATE TITLE" menu
2. When "K_SPARTA" is created, an Event will fire announcing it, with plenty of flavor for different cultures and religions, etc.
4. Spartans and their modern equivalent (Tsakonians) now have access to Cognatic succession (like the Basques), to represent their equality of women in ruling and war
5. The restorer of "K_SPARTA" can convert to the Spartan culture (already in code) if he is prestigious enough and controls enough land
6. Restored Spartans (but not Tsakonians) can now loot and pillage, as they did in RL (especially against Athens)
7. Possibly an Event where Spartan (and possibly Tsakonian) characters of pagan religions can leave deformed/imbecile/etc. babies to die on a hill, as in RL, sadly, I don't know how to write that
8. The restorer of "K_SPARTA" can create a special mercenary group of loyal Spartans under him
9. The Spartan (but not Tsakonian) culture gives a martial boost

It would be another fun thing to try and achieve, and it already fits with the Ancient Religions Reborn parts of this Mod.

-TURTLESHROOM

**Comment by Lietuvis** [comment]
^^^^Do this pls

**Comment by loup99** [comment]
1. Sure, but I will have to hear with Erik W beforehand of course.
2. As you wish.
3. No, that is already handled through the Gender Equality laws.
4. I don't remember why that culture was added, but that would have to be through a difficult event chain, not instantly.
5. Sure.
6. You can kill them through effect.
7. Sure.
8. A (very) small one.
9. Not really, no.

**Comment by TurtleShroom** [comment]
@loup99 

1. Yeah, like he'll get back to us by the end of summer.

2. Great!

3. Not true. Gender Equality requires working up the list. In Vanilla, ALL Basque characters have full access to Absolute Cognatic Succession at the start of the game, as they do in this Mod. The succession rules and Laws you speak of are tied to _religion_, not culture.

4. Not true. Tsakonians _were_ Spartans, and even today, the Tsakonian dialect of Greek is mostly the same dialect Spartans spoke. The main difference between Tsakonians and Spartans were their martial prowess and their societal customs (Hoplites, trained from birth, etc. etc.). The non-martial aspects of Spartan culture survived in the Tsakonians. All they would have to do is re-adapt the Spartan militarism. That is what the Decision to become Spartan (if you restore Sparta) is for.

5. Great!

6. Okay.

7. Great!

8. The Buddhist religion gives a positive four bonus to Learning for everyone. The Gurzil Pagan religion gives a positive four Martial bonus to everyone. Why can't the Spartan culture give a positive four bonus to every Spartan? I even balanced it by having certain Traits and Modifiers offset it if need be.

9. Okay.

**Comment by loup99** [comment]
3. As I believe I told you in private, the Tsakonians weren't renown for any gender equality.
4. No, they weren't at the point of the mod start date. Culture changes over the millenniums, and as time goes on the difference gets more and more important. Going to a neo-Spartan culture shouldn't be an instant click, what is the fun in that? You refer to ACR, well, all of the rebirth movements in that are far more.
8. Because the Spartan culture isn't a Spartan religion.

**Comment by TurtleShroom** [comment]
3. Okay, I'll strike that from the Tsakonians.

4. I don't know how to code it in that way. Until someone else can fix it, the instant conversion will have to do.

5. Indeed, which is why Spartan culture goes with the Basque culture in the Gender Succession section. I'll remove the Tsakonians, though.

**Comment by loup99** [comment]
4. How so? It can be a random event or an ambition.
5. What did you reply to here?

**Comment by TurtleShroom** [comment]
Closed. Rejected by Loup.

**Comment by loup99** [comment]
Reopened. It is a shame that you in your anger missed some of my points. You put work into Sparta, we are not just removing it because you are irritated over some prestige requirements.

**Comment by TurtleShroom** [comment]
It wasn't just the prestige requirements. Your list of objections was VERY long, and you said I couldn't get TSP8 approved for months with Sparta on it.

I reverted it to get back on track. Sparta can always show up on TSP9.

**Comment by loup99** [comment]
OK.

**Comment by TurtleShroom** [comment]
https://github.com/loup99/WtWSMS/pull/292

It's finally back, and about time too.

**Comment by TurtleShroom** [comment]
https://github.com/loup99/WtWSMS/pull/292

It's finally back, and about time too.
