### ISSUE TITLE
Dynasties need fixing

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#242]
Here's the output of Validator, Dynasties option selected. I'm posting it as an issue because I'm not good at dynasties, characters, relatives etc.

> --- Error 1 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [1042276\culture] (Line 28609, column 2):
> "helleno_aramaic" is not a valid Culture.
> --- Error 2 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I380692|L30794|C1]: 10424410 = {   name = "Sambatiolus"  culture = raetoroman }
> 	[I380636|L30790|C1]: 10424410 = {   name = "Sabinianus"  culture = raetoroman }
> --- Error 3 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I365368|L29696|C1]: 10424141 = {   name = "Verinus"  culture = romano_hispanic }
> 	[I365306|L29692|C1]: 10424141 = {   name = "Iustinianus"  culture = romano_hispanic }
> --- Error 4 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I363076|L29525|C1]: 10424074 = {   name = "Geating"  culture = thuringian }
> 	[I363022|L29521|C1]: 10424074 = {   name = "Fisuding"  culture = thuringian }
> --- Error 5 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I362963|L29517|C1]: 10424073 = {   name = "Herminfriding"  culture = thuringian }
> 	[I362904|L29513|C1]: 10424073 = {   name = "Berthacharing"  culture = thuringian }
> --- Error 6 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I361620|L29409|C1]: 10424047 = {   name = "Ingjalding"  culture = swede }
> 	[I361569|L29405|C1]: 10424047 = {   name = "Ingjalding"  culture = swede }
> --- Error 7 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I353171|L28731|C1]: 1042295 = {   name = "Gurthinmoch"  culture = pictish }
> 	[I353122|L28727|C1]: 1042295 = {   name = "Erilich"  culture = pictish }
> --- Error 8 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I347069|L28300|C1]: 1042208 = {   name = "Yueba"  culture = hepthalite }
> 	[I347019|L28296|C1]: 1042208 = {   name = "Xiyu"  culture = hepthalite }
> --- Error 9 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I340337|L27784|C1]: 1042091 = {   name = "Karkota"  culture = panjabi }
> 	[I340181|L27772|C1]: 1042091 = {   name = "Bhatti"  culture = rajput }
> --- Error 10 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I332883|L27205|C1]: 1029176 = {   name = "Chalukya Chola"  culture = tamil }
> 	[I331284|L27054|C1]: 1029176 = {   name = "Chalukya Chola"  culture = tamil }
> --- Error 11 of 23 ---
> At <mod>\common\dynasties\00_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I332826|L27201|C1]: 1029175 = {   name = "Vengi Chalukya"  culture = telugu }
> 	[I331153|L27042|C1]: 1029175 = {   name = "Vengi Chalukya"  culture = telugu  coat_of_arms = {    data = { 0 0 0 15 0 10 10 }   religion = hindu  } }
> --- Error 12 of 23 ---
> At <mod>\common\dynasties\01_dynasties.txt [1042556\culture] (Line 1638, column 2):
> "armadian" is not a valid Culture.
> --- Error 13 of 23 ---
> At <mod>\common\dynasties\01_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I20496|L1552|C1]: 1042535 = {   name = "Constantinus"  culture = illyro_roman }
> 	[I20440|L1548|C1]: 1042535 = {   name = "Areobindus"  culture = ostrogothic }
> --- Error 14 of 23 ---
> At <mod>\common\dynasties\01_dynasties.txt [] (Line 0, column 0):
> There may be no duplications of a NonNegInt clause.
> There were 2 duplicates.
> 	[I9667|L732|C1]: 10424529 = {   name = "Dagtaws"  culture = vidivarii }
> 	[I9609|L728|C1]: 10424529 = {   name = "Thiuderiktaws"  culture = vidivarii }
> --- Error 15 of 23 ---
> GlobalFlag flag analysis completed without warnings
> GlobalFlag flag analysis finished without warnings. Open the file for more details.
> --- Error 16 of 23 ---
> CharFlag flag analysis completed without warnings
> CharFlag flag analysis finished without warnings. Open the file for more details.
> --- Error 17 of 23 ---
> DynastyFlag flag analysis completed without warnings
> DynastyFlag flag analysis finished without warnings. Open the file for more details.
> --- Error 18 of 23 ---
> ProvinceFlag flag analysis completed without warnings
> ProvinceFlag flag analysis finished without warnings. Open the file for more details.
> --- Error 19 of 23 ---
> TitleFlag flag analysis completed without warnings
> TitleFlag flag analysis finished without warnings. Open the file for more details.
> --- Error 20 of 23 ---
> ArtifactFlag flag analysis completed without warnings
> ArtifactFlag flag analysis finished without warnings. Open the file for more details.
> --- Error 21 of 23 ---
> Variable flag analysis completed without warnings
> Variable flag analysis finished without warnings. Open the file for more details.
> --- Error 22 of 23 ---
> Earmarks flag analysis completed without warnings
> Earmarks flag analysis finished without warnings. Open the file for more details.
> --- Error 23 of 23 ---
> CharQuest flag analysis completed without warnings
> CharQuest flag analysis finished without warnings. Open the file for more details.
>

**Comment by loup99** [comment]
The cultures are awaiting @EmperorEnlil . Duplicates need to be removed, but I'm not sure they exist in practice?

**Comment by IhateTrains** [comment]
So Enlil is still developing this mod?

**Comment by loup99** [comment]
Of course Enlil is still developing the mod. He is the lead developer.
