### ISSUE TITLE
Log error "Unexpected token: if"

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#245]
Could you please help me with a log error? I think it's crucial.

error:
> [persistent.cpp:40]: Error: "Unexpected token: if, near line: 345" in file: "events/VIET_culture_west_african_events.txt"
> [persistent.cpp:40]: Error: "Unexpected token: if, near line: 360" in file: "events/VIET_culture_west_african_events.txt"
> [persistent.cpp:40]: Error: "Unexpected token: if, near line: 408" in file: "events/VIET_culture_west_african_events.txt"
> [persistent.cpp:40]: Error: "Unexpected token: if, near line: 427" in file: "events/VIET_culture_west_african_events.txt"
> [persistent.cpp:40]: Error: "Unexpected token: if, near line: 475" in file: "events/VIET_culture_west_african_events.txt"
> [persistent.cpp:40]: Error: "Unexpected token: if, near line: 490" in file: "events/VIET_culture_west_african_events.txt"

**Comment by loup99** [comment]
The log apparently doesn't like the if blocks which test the `VIET_griot_mark` added in the Griot calculator event wafrica.0.

**Comment by IhateTrains** [comment]
Are you able to fix it?

**Comment by loup99** [comment]
No, I don't see the issue. It doesn't like the usage of the special scope created with the event target to execute a command in the if block, but I don't know why.

**Comment by loup99** [comment]
The best is to ask on the forums if we can't find a solution to this. Given that we didn't code it ourselves it more of an attempt to update VIET than solving errors on WtWSMS though, so I believe the question pertains more to that.

**Comment by loup99** [comment]
`Error: "Unexpected token: short_name, near line: 568" in file: "events/WTWSMS_historical_events.txt"`

This error works in practice, I believe.

**Comment by IhateTrains** [comment]
It seems that VIET_griot_mark event target doesn't exist, even in VIET itself.

**Comment by loup99** [comment]
What do you mean? The event target is saved in line 73.

**Comment by IhateTrains** [comment]
It is, strange. I didn't find it via Notepad++. I'm blind again

**Comment by xirsoi** [comment]
I wouldn't be shocked if this was caused by an errant non-breaking space. You may be able to solve it by deleting the line the error is happening on and then re-type it. Don't copy the line then delete and paste, type it out fresh.

**Comment by loup99** [comment]
Unfortunately that doesn't seem to be the issue. For investigation purposes it should be noted that the problem is no longer reported for the same lines, even though it is the same code.
 
```
[persistent.cpp:40]: Error: "Unexpected token: if, near line: 344" in file: "events/VIET_culture_west_african_events.txt"
[persistent.cpp:40]: Error: "Unexpected token: if, near line: 359" in file: "events/VIET_culture_west_african_events.txt"
[persistent.cpp:40]: Error: "Unexpected token: if, near line: 407" in file: "events/VIET_culture_west_african_events.txt"
[persistent.cpp:40]: Error: "Unexpected token: if, near line: 426" in file: "events/VIET_culture_west_african_events.txt"
[persistent.cpp:40]: Error: "Unexpected token: if, near line: 474" in file: "events/VIET_culture_west_african_events.txt"
[persistent.cpp:40]: Error: "Unexpected token: if, near line: 489" in file: "events/VIET_culture_west_african_events.txt"

```

**Comment by loup99** [comment]
--- Error 1 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 369, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 2 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 355, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 3 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 340, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 4 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 439, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 5 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 422, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 6 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 403, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 7 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 499, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 8 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 485, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)
--- Error 9 of 9 ---
At <mod>\events\VIET_culture_west_african_events.txt [character_event\immediate\if\VIET_griot_mark] (Line 470, column 4):
Invalid node "VIET_griot_mark" in scope CharIfClause (value is: <a complex type>)

**Comment by loup99** [comment]
There can't be "if" blocks in effects.

**Comment by loup99** [comment]
I believe I fixed it, will test tomorrow.

**Comment by loup99** [comment]
I think that should be it, don't hesitate to reopen or post if you find anything else.
