### ISSUE TITLE
Julius Nepos tries to assasinate himselft :D

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#246]
![2017-07-04 1](https://user-images.githubusercontent.com/29546927/27828999-902fde6c-60bf-11e7-89f2-490ad4907e3f.png)

**Comment by loup99** [comment]
How did that happen? What did you do?

**Comment by IhateTrains** [comment]
This is a bug in Nepos' bookmark

**Comment by IhateTrains** [comment]
I get this event before beta notification

**Comment by loup99** [comment]
Before? The beta notification fires on startup.

**Comment by loup99** [comment]
It is the assassination by Glycerius:

`	480.5.1 = {
		effect = { e_wre = { holder_scope = { send_assassin = THIS } } }
	}
`

**Comment by IhateTrains** [comment]
Yes, before. Also on starup, but miliseconds earlier.

**Comment by IhateTrains** [comment]
So why is Nepos the plotter?

**Comment by loup99** [comment]
Scripted effects in history are probably loaded before start-up events in the on actions, which is why it appears earlier.

**Comment by loup99** [comment]
I have fixed it through changing things up: when testing it is no longer an attempt by Nepos at assasinating himself.
