### ISSUE TITLE
Missing events (from error.log)

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#247]
This is a part of error.log:

> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.9010", on_action: "on_startup"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.9023", on_action: "on_startup"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.2000", on_action: "on_yearly_pulse"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.2050", on_action: "on_yearly_pulse"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.2001", on_action: "on_yearly_pulse"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.2003", on_action: "on_yearly_pulse"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.2023", on_action: "on_yearly_pulse"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "706", on_action: "on_birth"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "707", on_action: "on_birth"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.3403", on_action: "on_adulthood"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "708", on_action: "on_marriage"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "705", on_action: "on_death"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "722", on_action: "on_death"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "731", on_action: "on_death"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "732", on_action: "on_death"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "734", on_action: "on_death"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "740", on_action: "on_death"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "spirit.33", on_action: "DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ACCEPT_EVENT"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "725", on_action: "SETTLE_ADVENTURER_INTERACTION_ACCEPT_EVENT"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "ancrel.0009", on_action: "on_reform_religion"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "701", on_action: "on_become_doge"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "700", on_action: "on_entering_port"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "704", on_action: "on_rel_head_chosen"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "739", on_action: "on_create_title"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "738", on_action: "on_new_holder"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "738", on_action: "on_new_holder_inheritance"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "738", on_action: "on_new_holder_usurpation"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "729", on_action: "on_war_ended_victory"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "730", on_action: "on_war_ended_defeat"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "717", on_action: "on_divorce"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "733", on_action: "on_hospital_construction_completed"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "727", on_action: "on_enforce_peace_six_vassals"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "726", on_action: "on_law_vote_passed"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "728", on_action: "on_player_mercenary_income"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "735", on_action: "on_character_society_rank_up"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "736", on_action: "on_character_society_rank_up"
> [onaction.cpp:213]: OnAction list is referencing invalid event! event: "737", on_action: "on_character_society_rank_up"

Should I remove these references?

**Comment by loup99** [comment]
Concerning Ancient Religions, I will have to look at what it is. In case it is an actual issue on their end we should forward it, but otherwise it may be a bad integration. As for the others, that is vanilla, no?

**Comment by IhateTrains** [comment]
Yes, I found them in vanilla files (events\achievement_events.txt). This file also exists in the mod but it's empty: 
> #I sleep in my fireplace, 'cause I sleep like a log!

**Comment by loup99** [comment]
No, that causes issues:
@Zusk said in the commit https://github.com/loup99/WtWSMS/commit/b12474d3e13d30e5c55710d0b554b67229ade93d :
`Something was wrong with how the mod was reading the achievements from vanilla, blanking out the file not only fixes this issue but it also improves performance as achievements are pointless for mod play!`
