### ISSUE TITLE
Imperial Regalia

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#250]
We have placeholder icons and artifact files. What we need is an event/decision chain.

**Comment by loup99** [comment]
Reposting what was said previously in #243:

> This is my Imperial Regalia idea
![plan](https://user-images.githubusercontent.com/29546927/27853477-1043287c-6163-11e7-85fe-4a1d9429e572.png)  (Imperial Regalia Question event would fire a day after Fall of Rome)

> Sounds good as a start! For reference, this is what was suggested on the forums:

> Odoacer sent two embassies to Constantinople once he established his rule over Italy. The first was basically telling Emperor Zeno that one Emperor was enough, and the second sent back the imperial regalia of the Western Court. So I was thinking in order to simulate this in game, y'all could make an event where Emperor Zeno chooses to accept this (King Odoacer becomes a tributary or something, Emperor of the East receives some items that normally belong to the WRE) or Zeno could not accept it and put Nepos on the Throne of the West. Also apparently the Senate was comfortable with having a rex because he let the Senate do more? but idk how y'all would simulate that.

> I don't believe the emperor was in Constantinople was actually in a position to do anything about Odoacer so tributary status probably wouldn't be a good idea. However perhaps the ERE emperor could receive the imperial regalia as artifacts that give him a nice boost as sole remaining Roman emperor, while the ERE emperor can officially grant Odoacer a Roman title which gives him legitimacy and some form of trait or bonus.

> We do have already have a decision for the sole remaining Roman emperor, but adding imperial regalia as artifacts could be an interesting additional mechanic.

> I think the ERE emperor could recognise Odoacer in exchange if the option of sending the regalia to him is picked, giving him additional prestige and a boost (like we did for the ERE/WRE restoration).

**Comment by loup99** [comment]
Do you want me to do the event chain?

**Comment by IhateTrains** [comment]
You will probably do it better than I.

**Comment by loup99** [comment]
So I did some work on this during the beginning of this afternoon, and it has at least a skeleton which I haven't tested yet. However I thought this might be a good occasion to seek some help for the localisation which I haven't started with. Here is the list of the entries, with my comments from the code:

```
imperial_legacy.42.desc;;;;;;;;;;;;x # Handling the Western Imperial Regalia after the Fall of Rome
imperial_legacy.42.a;;;;;;;;;;;;x # Keep them
imperial_legacy.42.b;;;;;;;;;;;;x # Send them to the ERE emperor
imperial_legacy.42.c;;;;;;;;;;;;x # Send them to the remaining WRE emperor
imperial_legacy.42.d;;;;;;;;;;;;x # Send them to Soissons
imperial_legacy.43.name;;;;;;;;;;;;x 
imperial_legacy.43.desc;;;;;;;;;;;;x # Receiving the Western Imperial Regalia based upon the choice of the conqueror of Rome
imperial_legacy.43.a;;;;;;;;;;;;x # Recognise conqueror
imperial_legacy.43.b;;;;;;;;;;;;x # Thank vaguely without making any firm commitments
imperial_legacy.43.c;;;;;;;;;;;; # Refuse the Western Imperial Regalia sent by the conqueror
imperial_legacy.44.name;;;;;;;;;;;;x
imperial_legacy.44.desc;;;;;;;;;;;;x # Conqueror having sent the Western Imperial Regalia gets recognition in return
imperial_legacy.44.a;;;;;;;;;;;;x 
imperial_legacy.45.name;;;;;;;;;;;;x
imperial_legacy.45.desc;;;;;;;;;;;;x # Conqueror having sent the Western Imperial Regalia gets it refused
imperial_legacy.45.a;;;;;;;;;;;;x
```

**Comment by IhateTrains** [comment]
Based on my graphic. imperial_legacy.42.b might be too long

```
imperial_legacy.42.name;Imperial Regalia Question;;;;;;;;;;;x
imperial_legacy.42.desc;;;;;;;;;;;;x # Handling the Western Imperial Regalia after the Fall of Rome
imperial_legacy.42.a;They look nice, I think I will keep them;;;;;;;;;;;x # Keep them
imperial_legacy.42.b;Send them to the eastern emperor, maybe he will recognise our rule;;;;;;;;;;;x # Send them to the ERE emperor
imperial_legacy.42.c;;;;;;;;;;;;x # Send them to the remaining WRE emperor
imperial_legacy.42.d;Send them to Soissons;;;;;;;;;;;x # Send them to Soissons
imperial_legacy.43.name;Western Roman Regalia;;;;;;;;;;;x 
imperial_legacy.43.desc;;;;;;;;;;;;x # Receiving the Western Imperial Regalia based upon the choice of the conqueror of Rome
imperial_legacy.43.a;;;;;;;;;;;;x # Recognise conqueror
imperial_legacy.43.b;;;;;;;;;;;;x # Thank vaguely without making any firm commitments
imperial_legacy.43.c;It doesn't change anything. He is just a barbarian usurper;;;;;;;;;;; # Refuse the Western Imperial Regalia sent by the conqueror
imperial_legacy.44.name;;;;;;;;;;;;x
imperial_legacy.44.desc;;;;;;;;;;;;x # Conqueror having sent the Western Imperial Regalia gets recognition in return
imperial_legacy.44.a;;;;;;;;;;;;x 
imperial_legacy.45.name;;;;;;;;;;;;x
imperial_legacy.45.desc;;;;;;;;;;;;x # Conqueror having sent the Western Imperial Regalia gets it refused
imperial_legacy.45.a;Ingrateful bastards!;;;;;;;;;;;x
```

**Comment by loup99** [comment]
There is an unexpected delay in the form of a code issue with one of the events, but this is still ongoing!

**Comment by loup99** [comment]
I have commited the skeleton events with localisation, but as the transfer didn't work (even though the scopes seemed correct when testing the event through console) I had to disable them given that they additionally spawned blank events and were not possible to resolve through Validator or logs. Maybe you have an idea? As I haven't worked on artifacts before, and as it is the issue maybe you could have an idea?

**Comment by IhateTrains** [comment]
I will try but I don't promise anything.

**Comment by IhateTrains** [comment]
I didn't manage to get rid of the blank event popups but I found these errors in error.log:

> [persistent.cpp:40]: Error: "Unexpected token: days, near line: 1523" in file: "events/WtWSMS_imperial_legacy_events.txt"
[id.cpp:83]: Failed to create id 6000043 61. Already exists in game.
[id.cpp:83]: Failed to create id 6000042 61. Already exists in game.
[persistent.cpp:40]: Error: "Unexpected token: days, near line: 671" in file: "events/WtWSMS_story_events.txt"
[id.cpp:83]: Failed to create id 4700026 61. Already exists in game.
[persistent.cpp:40]: Error: "Unexpected token: days, near line: 728" in file: "events/WtWSMS_story_events.txt"

I think the errors are caused by fragments like this:
> ROOT = {
			character_event = { id = imperial_legacy.42 days = 2 } # Delay to ensure that e_wre has been granted beforehand
		}

I will try again tomorrow.

**Comment by loup99** [comment]
Yes, it reports that, but I don't see the problem with that fragment. We use it elsewhere, and when the artifacts are disabled it works (I tested it). I believe the issue lies elsewhere.

**Comment by IhateTrains** [comment]
Since the blank popups appear even with 

> ROOT = {
character_event = { id = imperial_legacy.42 days = 2 } # Delay to ensure that e_wre has been granted beforehand
}

disabled, my suspect is 

```
 		western_regalia = {
			artifact_owner = {
				western_regalia = { 
					transfer_artifact = {
						from = THIS 
						to = ROOT	
					}
				}
			}
		}
```

**Comment by loup99** [comment]
Yes, I had already localised it to that. As I said, everything related to artifacts doesn't work.

**Comment by IhateTrains** [comment]
I still don't know how to fix it, but I will try to use add_artifact as a temporary workaround.

**Comment by loup99** [comment]
Wouldn't that create yet another copy?

**Comment by IhateTrains** [comment]
I mean we could prevent Augustulus from getting the artifacts and only spawn it by giving it to one of the Roman states.

**Comment by loup99** [comment]
He should definitely have the artifact at start.

**Comment by IhateTrains** [comment]
I've solved the issue in story_events file
```
any_character = {
            limit = { has_artifact = western_regalia }
            any_artifact = {
                    transfer_artifact = {
                        from = PREV
                        to = ROOT
                    }
                }
        }
        ROOT = {
            character_event = { id = imperial_legacy.42 days = 2 } # Delay to ensure that e_wre has been granted beforehand
        }
```

I'm now trying to fix the imperial_legacy_events file. Here's what I noticed:
![2017-07-14](https://user-images.githubusercontent.com/29546927/28211344-6818e556-689c-11e7-9c1f-1e97e3593d15.png)
One of the sending options works, but the other ones are hidden and after the option is chosen, two blank popups appear:
![2017-07-14 1](https://user-images.githubusercontent.com/29546927/28211346-6d3d0440-689c-11e7-86b3-e2c1ba62d45c.png)
I don't know why, the three options are very similar.
