### ISSUE TITLE
Fall of Rome Coding: Mistake Discovered?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#256]
Good morning.

I successfully crushed Emperor Zenos in battle as the Miaphysite Byzantine Emperor at the start of the game. I received word that Rome had fallen, as usual, but for some reason, instead of the Nicene religion losing its Moral Authority by thirty, _my_ religion lost it instead! Now, Miaphysitism is down thirty.

Is the Fall of Rome intended to take thirty Moral Authority points from all Christians, or just from Nicenes? If the latter is true, there's a mistake.

In addition, and do to no fault on my own, I have suddenly found myself with negative nine hundred Prestige. I am in similar dire straits with Piety. Is this intended? I am Miaphysite, not Nicene.

-TURTLESHROOM

**Comment by loup99** [comment]
> I successfully crushed Emperor Zenos in battle as the Miaphysite Byzantine Emperor at the start of the game. I received word that Rome had fallen, as usual, but for some reason, instead of the Nicene religion losing its Moral Authority by thirty, my religion lost it instead! Now, Miaphysitism is down thirty.
> 
> Is the Fall of Rome intended to take thirty Moral Authority points from all Christians, or just from Nicenes? If the latter is true, there's a mistake.
> 
It is meant to hurt the remaining Roman imperial power's current religion, as it triggers for the ERE emperor's religion.

> In addition, and do to no fault on my own, I have suddenly found myself with negative nine hundred Prestige. I am in similar dire straits with Piety. Is this intended? I am Miaphysite, not Nicene.

Yes:
```
piety = -1000
prestige = -1000
```
