### ISSUE TITLE
Discussion on Adding Exceptions to Existant Legion Formation Decisions

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#259]
Moved posts from issue #252 

@TurtleShroom 
> The problem is that the ERE does fully control that duchy or kingdom. Legions disbanding while the ERE is still of the Romance culture group makes no sense. 
> 
> Simply put, I believe that the _top liege_ should completely control the duchy or kingdom and be of a Romance culture in order for Legions to be disbanded.
> 
> In actuality, I'd prefer there to be a Rule governing Legions disbanding that addresses this. One keeps the setup as-is, one requires the top liege to be Romance and fully control it, and one allows Legions to always exist.

**Comment by loup99** [comment]
> The problem is that the ERE does fully control that duchy or kingdom.

That isn't a problem here, as I explained. The character which is the liege of the legion needs to hold the associated title where the legion is placed.

> Legions disbanding while the ERE is still of the Romance culture group makes no sense.

It does, in case the title which is associated to the legions no longer exists. What you did should not be possible though, because the legions are not meant to be revocable at all. 

> Simply put, I believe that the top liege should completely control the duchy or kingdom and be of a Romance culture in order for Legions to be disbanded.

❓ I believe this is badly worded, because it makes zero sense. Currently if the liege controls the title he also controls the legion. If not, a vassal does it. In case someone who does not control the title becomes the liege of the legion, it is disbanded. Otherwise it would be possible to loose an area and still keep the legions.

**Comment by TurtleShroom** [comment]
Correct me if I'm wrong, but Legions were loyal to Rome and, therefore, the _Roman Emperor_, not the individual governors and kings appointed by Rome.

I'll give an example.

Let's say I am the Greek ruler of the ERE. I am of Romance culture and all Legions in the game exist under me. Then, the person in charge of Oriens dies. I grant Oriens to my brother, who was educated abroad and is now Hunnic. Under the current code, the Legion disbands.

That doesn't make sense: I am still the "Roman" Emperor and I am still of Romance culture. The fact that my brother isn't doesn't mean the Legions go "oh, yeah this local king isn't Roman, so we'd better stop serving the Roman Empire and our Roman Emperor" and disband.

That's ahistorical. Legions were created, disbanded, and shuffled around across Roman diosceses over the centuries. Some Legions in this time period didn't exist before. They served at the privilege of the Roman Emperor.

So I say again: Legions should not disband as long as their _top liege_ (the _Roman Emperor_) is of Romance culture.

**Comment by TurtleShroom** [comment]
A better title for this would be "_**Better Handling of Legionary Disbandment**_".

**Comment by loup99** [comment]
> Correct me if I'm wrong, but Legions were loyal to Rome and, therefore, the Roman Emperor, not the individual governors and kings appointed by Rome.

You are wrong. The legions were famous for their local loyalties, taking sides in civil wars.

**Comment by TurtleShroom** [comment]
1. Legions taking sides in local wars and disputes is expected.

2. They wouldn't disband, though. The Roman Emperor is still in charge, and Rome is still Rome, so the Legions should accordingly remain.

3. Legionares were appointed by their local governor. However, the Roman Emperor, who appoints kings and governors, put them in the place to do it.

4. By "re-shuffle", I meant that new Legions have been created and others have been disbanded as Rome's borders have changed.

5. Are you telling me that a local governor, or the Roman Emperor, can't dismiss a Legionaire?

**Comment by loup99** [comment]
1. No, they were loyal to the one who paid them, basically, and through the local system we have that local allegiance is represented in game terms.
2. First of all, I'd like to point out that this was a system in evolution. The ERE and WRE both had their legions, and progressively the legions did diminish, although that was a long process. In game terms this is simplified to be a feature for Romance-only rulers. Unfortunately I don't think it is possible to prevent these titles from being transferred given that the action is hardcoded. It would had been good though as doing it will cause them to disband and shouldn't be possible at all. 
3. You are a bit vague. Different factions at court played a big role here, and too few emperors (for the WRE) had the initiative during our period for it to be him to do so. 
4. Yes, more or less, although note it is a simplification.
5. No, the legions didn't work in a way which allowed the emperors to alone dismiss individual soldiers or have a such detailed insight.

**Comment by AzimuthEmp** [comment]
"Yeah, the Legions would never follow a Hunnic ruler."

They would and did. Like Odoacer.

**Comment by AzimuthEmp** [comment]
The ERE famously had Hunnic commanders well into the 7th century.

**Comment by loup99** [comment]
You are speaking about Hunnic commanders. Odoacer doesn't get legions in the mod but gets the Bureaucratic government type.
