### ISSUE TITLE
Game Over After Successful Migration

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#280]
Good afternoon.

Starting in the "Little Augustus" Bookmark, I took a Migration War as the Crimean Goths. I migrated to Frisia (held by the Titular Kingdom of Frisia). When I enforced my demands (with one hundred percent War Score), I became completely unlanded and I got the Game Over screen. The game did not crash, however.

That's not supposed to happen, and as Migration is the biggest feature of the Mod, it's critical that this gets addressed.

-TURTLESHROOM

**Comment by loup99** [comment]
Migration to Frisia? I managed to migrate to an adjacent territory personally, but I'm going to test this.
