### ISSUE TITLE
The Basque

### ISSUE THREAD

**Issue by PoldarktheKing** [loup99/WtWSMS#299]
As it is the Basque are as they are in 1000 AD, which is thoroughly Hispanicised. In 500 AD they were still very independent and different.
The same applies to the Aquitanians.

**Comment by loup99** [comment]
What are you referring to by saying "as it is"? Because the Basque have a separate culture, a distinct religion and are independent politically. Do you mean the name list?

**Comment by loup99** [comment]
In two commits we have tried to remove Hispanicised elements. Please get back to use if there is anything more than that.
