### ISSUE TITLE
ancrel.2220 for Restoring the Roman Empire gives Open Elective succession

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#314]
Creating this issue to compile everything we know about the bug. It's currently fixed by an event workaround and it should be fixed completely.

**Comment by IhateTrains** [comment]
- Occurs for both Ancient Religions (ancrel.2220) and vanilla (LoR.20) event versions
- Doesn't occur in vanilla

**Comment by IhateTrains** [comment]
My suspect is the Bureaucratic government type

**Comment by xirsoi** [comment]
I suspect it has something to do with changing the primary title. Have you reported this bug to Paradox yet?

**Comment by loup99** [comment]
No, we haven't reported it as it only occurs in the WtWSMS version, making @IhateTrains suspect it is an issue with the law and government modifications in the mod that causes this.

**Comment by xirsoi** [comment]
This bug report needs a lot more information then. At the very least we need to know which imperial title was used to restore the empire and what was their government type before it was changed to Open Elective.

**Comment by IhateTrains** [comment]
What I can say is that the bug isn't caused by the ACR event code, as it also happens with the vanilla event.
Both Roman Empires have Bureaucratic government by default. I tried changing the ERE gov to feudal but it  
didn't solve the bug.
I'll try to prove my theory by restoring both government and laws to vanilla setup.

**Comment by xirsoi** [comment]
I believe you, I'm just trying to help.

**Comment by IhateTrains** [comment]
I did some testing today:
* disabled the government and law folders, didn't help
* copied ancrel.2220 from ACR, didn't help
* wrote a history file for e_roman_empire, didn't help

**Comment by IhateTrains** [comment]
I should take a look at succession laws.

**Comment by AMDarkPhoenix** [comment]
I fixed it when i was playing roman campaign. Just added title = e_roman_empire here 

 	succ_primogeniture = {
		oldest_child_opinion = 10
		youngest_child_opinion = -15
		child_opinion = -10
		dynasty_opinion = -5
		potential = {
			holder_scope = {
				NOT = { religion_group = muslim }
				is_merchant_republic = no
				is_patrician = no
			}
			OR = {
				_**title = e_roman_empire**_
				holder_scope = { # Viceroyalties can always have primogeniture if not muslim
					any_demesne_title = {
						is_vice_royalty = yes
					}
				}
				AND = {
					holder_scope = { (...)

and here 

		allow = {
			conditional_tooltip = {
				trigger = {
					has_dlc = "Conclave"
				}
				OR = {
					**_title = e_roman_empire_**

**Comment by loup99** [comment]
Thanks a lot for continuing to provide feedback and insight, we really appreciate that you take the time to do so. Just one thing I wanted to note based upon your post:

> Just added title = e_roman_empire here (cuz its special title like papal state, and ps has this)

The Roman Empire isn't a special title like the Papal States, it doesn't have the role of a religious head and it doesn't have any particular rules regarding succession in the mod. Yet naturally your workaround does address the issue, even though the root of it remains unclear.

**Comment by AMDarkPhoenix** [comment]
Are You sure? I thought its special title like PS, because i had this. 
![Uploading xzzzc.png…]()

**Comment by AMDarkPhoenix** [comment]
I was right. Roman Empire is special title. Here is fixed file. Now everything should work, empire can't has primary = yes. 
https://zapodaj.net/images/e53a0a8845965.png
[landed_titles.txt](https://github.com/loup99/WtWSMS/files/1540911/landed_titles.txt)

**Comment by loup99** [comment]
Ah, then we weren't speaking of the same thing. Because in the code it doesn't say "special title", hence my confusion. Thank you nonetheless, as that explains the issue. primary = yes giving Open Elective/Agnatic  Succession was not something which was documented.
