### ISSUE TITLE
Reformed pagans without pagan_holy_war CB

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#33]
Currently:
- All reformed religions have the pagan_holy_war CB except:
  - scythian_pagan_reformed
  - african_solar_pagan_reformed
  - latin_solar_pagan_reformed
- None of the pre-reformed religions have the pagan_holy_war CB except:
  - mithraic_pagan

Is this WAD ?

**Comment by loup99** [comment]
No idea, you will have to ask Enlil on those or looking it up if it ius in a dev diary.

**Comment by rquinio** [comment]
Note: I've [simplified the pagan_holy_war condition](https://github.com/rickinator9/WTWSMS/blob/e706ad84adfffb21b2345cb2d3020a12e91de9db/WTWSMS/common/cb_types/00_cb_types.txt#L7664) to is_reformed_pagan = yes via https://github.com/rickinator9/WTWSMS/commit/e706ad84adfffb21b2345cb2d3020a12e91de9db

For pre-reformed, that may be too powerful ... ? Maybe it should also be restricted to having restored the religious head for these (i.e. restoration of the Pontifex Maximus for Hellenic, Kemetic priesthood for Kemetic, etc.) ?

**Comment by Zusk** [comment]
I am fine with reformed pagans getting the Holy War CB. Although in the past Enlil had a problem with Hellenics getting it, due to their historical nature.

Really, a seperate CB needs to be made for Hellenics but for now this will do fine. When Ancient Religions Reborn is incorporated I will go ahead and make this CB for Hellens.

**Comment by loup99** [comment]
I would restrict it to having the restored head.

**Comment by Zusk** [comment]
I really do not see why Cybellian's, Hellens, Neoplatonists, Gurzil's and any other pre-reformed pagan religion should be reduced to single county CB.

In time, they will need a invasion CB to make playing them a enjoyable experience. The issues with playing such a small religion are demographic mostly and that everyone hates you at the start. Its not that the religion itself prevented expansion, such as jainism.

I will work on adding the CB's when I finish with the stuff I am working on.

**Comment by loup99** [comment]
No, I think the player should have hard time, until the faith is restored and the head too. And that was the general consensus in the community too. Hellenics & co were not aggresive like, the Norse or Aztecs for instance.

**Comment by Zusk** [comment]
"hellenic_reconquest" Sounds incredibly annoying to port over, as it would have to be adjusted for the WtWSMS dejure setup, additionally, it would somehow have to be able to account for dejure duchies as well.

**Comment by Zusk** [comment]
My point is Loup..

Gurzil, Cybellian, Neoplatonists etc don't have a religious head.

I would be fine with all pagan religions becoming reformable, reforming them could give you the invasion/holy war CB and being unreformed could give you the county conquest CB.

**Comment by Zusk** [comment]
Hellens, under Augustus and Alexander were extremely aggressive, it was just not a 'holy war'.

**Comment by loup99** [comment]
I would also be fine with that, IF those who have the head only get the CB after restoring it.

**Comment by Zusk** [comment]
That was what I had meant by that, yeah.

I am fine with that.

**Comment by loup99** [comment]
With the disabled Holy War changes coming with the next update, this issue has served its purpose too.
