### ISSUE TITLE
Bubonic Plague Triggering Right Away

### ISSUE THREAD

**Issue by OdinMyst** [loup99/WtWSMS#336]
Hey guys, 

First of all, congratulations on one of the most amazing mods I've ever seen. Thank you!

About the bug, it's really simple. I've downloaded your mod from a commit of a few days ago and I have just started a game as a "count" under Odoacer, at the December 480 bookmark. 
The Bubonic Plague – that should happen no sooner than 200 years latter, according to the Game Rules ("Dynamic" default option) – showed up pretty much right away, June 1st 482, in Constantinople.
 
P.S.: I'm new to the mod and to github, so apologies if I'm not doing this the proper way.

**Comment by loup99** [comment]
Hi, thank you for the kind words. This is a known bug in the latest release, the Bubonic Plague has a tendency to fire at any time, disregarding the rules that are defined. Hopefully it will be fixed for the next release.

**Comment by OdinMyst** [comment]
You're welcome. Glad you're on top of it. I'm a big fan of your mod. Best of luck!

In case anyone else suffers from this, an _apparent_ "fix" is to reload a previous save (I have set the auto-saver to "monthly" for such scenarios) immediately after the first plague related message. This lacks confirmation though, as I haven't progressed much further yet.

**Comment by IhateTrains** [comment]
With the latest @loup99's commit, the issue should be solved
