### ISSUE TITLE
[Bug] Non-Roman-Empire getting conquest popups

### ISSUE THREAD

**Issue by pootthedestroyer** [loup99/WtWSMS#365]
Upon my empire (Celtic titular, combined with Britannia underneath) usurping the Regem of Soissons, I suddenly got a string of "[Region] Captured!" popups referencing Roman reconquest. Clearly I am not the Roman Emperor, nor Christian, so this came as a bit of a surprise. The part about filthy natives wasn't wholly inaccurate, but, well. :-P

Apparently there are special *creation* conditions for Soissons that I wouldn't have qualified for, but that didn't prevent me from usurping it under normal conditions. Best guess is that the kingdom holder gets labelled somehow. Since even the creation conditions don't require that you be Roman, or the Roman Emperor, that should probably be changed entirely.

The reward was only 100 Prestige per popup so it's not the end of the world, but whatever's going on underneath might end up affecting even more of the mod.

**Comment by loup99** [comment]
It is because trigger for Soissons and you hold the kingdom. We could change it to depend on the primary title instead.

**Comment by pootthedestroyer** [comment]
Sounds good to me. I imagine there might be other kingdoms for which the same holds true. Might be worth a look.
