### ISSUE TITLE
Reformed Kemetic/heresies not appearing on religion ledger

### ISSUE THREAD

**Issue by pootthedestroyer** [loup99/WtWSMS#366]
With plenty of provinces and a Moral Authority of 47, Reformed Kemetic does not appear on the religion ledger at all, nor do its heresies. As far as I can tell this isn't affecting gameplay, but it is very odd. Other religions with no followers are appearing on the ledger as normal (with 20 Moral Authority, usually, and a province count of zero.)

**Comment by loup99** [comment]
Pre-reformed religions don't, vanilla limitation.

**Comment by pootthedestroyer** [comment]
Every other religion, AFAIK, is on the ledger. Germanic (unreformed,) which
still exists, is on the ledger. Reformed Germanic, which was never created
in my playthrough, is on the ledger. Celtic got reformed and so its
non-reformed version is no longer on there; it was replaced by Reformed and
then "Old Celtic" as a heresy.

Kemetic is reformed, but still isn't showing up. That doesn't sound like a
bad rule. It sounds like a bug. If it's a bug in the vanilla game though,
I'll leave that to your expertise.

**Comment by loup99** [comment]
https://forum.paradoxplaza.com/forum/index.php?threads/make-pre-reformed-pagan-religions-show-in-the-ledger.1031877/
