### ISSUE TITLE
Cannot get past year 600

### ISSUE THREAD

**Issue by Raspootin** [loup99/WtWSMS#368]
I don't know why but it does not let me go past that year, whenever i try the buttons to advance time grey out. But in game i can play normally past year 600.

**Comment by IhateTrains** [comment]
The scrallable history ends in 600, so WAD.

**Comment by Raspootin** [comment]
Didnt know that, thanks for telling me.

2018 kov. 14 19:55 "IhateTrains" <notifications@github.com> rašė:

**Comment by IhateTrains** [comment]
The limit may be moved to ~700 in the future, but after the 1.0 release.
