### ISSUE TITLE
Wrong culture in Isle of Man

### ISSUE THREAD

**Issue by Raspootin** [loup99/WtWSMS#369]
![ck2](https://user-images.githubusercontent.com/37382137/37480550-6ae1ab1a-2877-11e8-868f-7a591fbe08ca.jpg)

Small issue i know but it still is a mistake (i think?)

**Comment by Raspootin** [comment]
![ck2 3](https://user-images.githubusercontent.com/37382137/37480705-d75777ca-2877-11e8-9d7f-e1da30caf630.png)
Sorry, didnt capture culture on isle

**Comment by IhateTrains** [comment]
Yes, it makes sense that Man should be Manx.

**Comment by loup99** [comment]
Yes, we discussed if the culture should be removed.

**Comment by IhateTrains** [comment]
What was the result?
I think if the culture stays and characters use it, the province culture should be changed as well.

**Comment by loup99** [comment]
It was considered to be anachronistic: https://forum.paradoxplaza.com/forum/index.php?threads/manx-culture.941707/#post-21598562
