### ISSUE TITLE
[history.cpp:767]: Error in common/province_setup/00_province_setup.txt: Title for 1408 does not correspond to history.

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#395]
In province setup it's c_kumul, but in history it's c_anxi.

**Comment by rquinio** [comment]
Good news from Holy Fury patch notes:
"- Eliminated the "province_setup" folder. Now based purely on province history instead, meaning you no longer have to duplicate script"

**Comment by loup99** [comment]
I have looked at it 1408 is meant to be Kumul while 1450 is meant to be Kara Khoja/Gaochang. I hope that clears up the confusion.

**Comment by loup99** [comment]
I have looked at it and 1408 is meant to be Kumul while 1450 is meant to be Kara Khoja/Gaochang and 1446 is Jiaohe. I hope that clears up the confusion. @IHateTrains does this resolve it?

**Comment by IhateTrains** [comment]
This still confuses me, maybe because I don't know the region at all. But if you checked that it's OK, then I think we can close it.

**Comment by loup99** [comment]
From what I understand the issue was that province setup did not correspond with the history. That province setup was then removed, but since history was correct in the first place everything should be fine.
