### ISSUE TITLE
Prosperity baronies

### ISSUE THREAD

**Issue by tannerflick4** [loup99/WtWSMS#400]
A place where we can discuss prosperity baronies, where the idea is to give all provinces 7 baronies in landed titles, or else the prosperity system which adds a holding would not work. 

Tsf4 is currently handling this, but we will keep the issue open until we get all counties having 7 baronies, as well as listing the full 7 in province files (even if unbuilt) as a reference.

**Comment by tannerflick4** [comment]
Completed, and checked by @Abian36 .

**Comment by IhateTrains** [comment]
If it is to be merged, it should be open. Haven't you closed by clicking the wrong button?

**Comment by loup99** [comment]
Merged?

**Comment by IhateTrains** [comment]
I realized after posting, IDK why.

**Comment by loup99** [comment]
No problems, everyone can misread.
