### ISSUE TITLE
Some nicknames are broken

### ISSUE THREAD

**Issue by Symmachus** [loup99/WtWSMS#410]
In January i downloaded and played in development WtWSMS version from Github. And i noted that at least one nickname, ''The Elder'' now broken after your changes.

**Comment by loup99** [comment]
The mod is not playable?

**Comment by IhateTrains** [comment]
Broken in what way? It may have been caused by incompatibility with Holy Fury, as @loup99 it has to be updated. Then you can check if the nickname is still broken.

**Comment by Symmachus** [comment]
I just roll back to previous version in Steam and i January development version was still playable in 2.8.3.4. Characters with nickname ''The Elder'' appearing for example is so "Exarch Heraclius nick_the_elder". This is because you deleted localisation of this nickname. Some other nicknames may be also broken on this point.

**Comment by IhateTrains** [comment]
I deleted the localisation because it exists in CK2 3.0 already.

**Comment by loup99** [comment]
Yes, that was the merging process.

**Comment by Symmachus** [comment]
Ok. sorry i thought it was really broken.

**Comment by loup99** [comment]
No problems, but note for the future that everything in a merging processus will be in progress while the merge is ongoing.
