### ISSUE TITLE
Size of loadingscreens

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#42]
I've noticed that the size of gfx\loadingscreens\load_1.dds is 7,91 Mo, while the other screens are 1,75 Mo.
I think it has to do with the dds export compression/minimaps, I'm not sure what format should be used. Also possibly the black bar at the bottom might reduce compression.

**Comment by loup99** [comment]
I can't edit those files, and have no possibility of doing so without downloading some tool (my GIMP refses to open it).

**Comment by rquinio** [comment]
Do you have .dds plugin for GIMP (https://code.google.com/p/gimp-dds/) installed ?

**Comment by loup99** [comment]
Yes, but an error message pops-up.

**Comment by loup99** [comment]
Ok, it is due to me having a "é" in my computername. :stuck_out_tongue:

**Comment by rquinio** [comment]
Same for load_9.dds ;)

**Comment by loup99** [comment]
I think only Joemit knows what is wrong with these.

**Comment by rquinio** [comment]
Solved it, needed to use DTX1 compression - no mimaps (I used Paint.NET, had some pixels with Gimp)
