### ISSUE TITLE
Christian Patriarches

### ISSUE THREAD

**Issue by loup99** [loup99/WtWSMS#43]
This is the issue for the Pope and papal States on the two early startdates. There are two problems, one that he converts to Arianism (weirdly enough as nobody else can do it :stuck_out_tongue: ) and that it disapears due to Theodorics invasion (same if Odoacer invades).

**Comment by rquinio** [comment]
I thought CK2 motto was "Don't mess with the Pope" ! These are really dark ages :)

**Comment by loup99** [comment]
Well, we are not reallly moving/messing him around, but the bugs need to be fixed!

**Comment by loup99** [comment]
Ok, so with the conversion issue it shoul be fixed with the latest commit for conversion. The other issue remains. I will be making him independant, but is ther a way to disable the dejure county thing for the papal states primary holding? Not entirely sure on why it disapeared too, it should stay but without any lands, as in vanilla CK2.

**Comment by loup99** [comment]
I think the issues behind the Papal States are related to it being a duchy instead of the kingdom.

**Comment by rquinio** [comment]
Hmm the Pope does not control Nicene religion and I've tested that controls_religion is actually false for Pentarchs...
So we may need to review vanilla code that is checking controls_religion = no and that can result on a religious conversion :/

**Comment by loup99** [comment]
Oh, yes, in that case that needs to be revewed.

**Comment by rquinio** [comment]
Should we switch the Pope as head of Nicene religion, rather than the Patriarch of Jerusalem, as suggested in the forum ?
This would probably solve this issue ^^

**Comment by loup99** [comment]
Yes, he should be that, Enlil said it too.

**Comment by loup99** [comment]
But how do we make it so that all patriarchs have a papal status and are impossible do usurp or displace in any way or form?

**Comment by EmperorEnlil** [comment]
We could use events to maintain their religion.

**Comment by loup99** [comment]
Wouldn't that afffect performance?

**Comment by EmperorEnlil** [comment]
How so? We just make an event that fires if a Patriarch isn't Nicene. Or we could make it that if a Patriarch embraces a heresy, provinces and characters under his jurisdiction would have a chance of also converting.

**Comment by loup99** [comment]
Yes, but it would require constant checks. If it would not affect it, fair enough.

**Comment by loup99** [comment]
If the second option is used, a new patriarch for the old faith needs to be elected though.

**Comment by rquinio** [comment]
What should happen to d_papal_state, if Rome falls and b_roma is taken by an Arian bishop, he will become the new Pentarch of Rome, no ?
Any schism would be between d_arian and d_orthodox, rather than d_papal_state and d_orthodox ?

**Comment by loup99** [comment]
That would be wrong and bad. The pope converting should not really be possible, and if he does so (with good balance around it), it should only give a hit and have a new pope in exile elected.

**Comment by rquinio** [comment]
Also according to http://www.ckiiwiki.com/Autocephaly#Pentarchs, the game will auto-usurp Pentarch seats to fit a religious head, if controlled by a liege of a religion that also has autocephaly.
Though, in case above it doesn't really apply because d_arian religious head has Jerusalem as capital, not Rome.

**Comment by loup99** [comment]
OK, so this still needs a fix, because at start I can easily convert the Pope. Is it sufficient to change the vanilla code around "controls_religion"?

**Comment by loup99** [comment]
Changed the title, the addition of those events discussed in this issue might be a future thing.

**Comment by rquinio** [comment]
I've noticed there's a specific character flag "ai_flag_refuse_conversion" used in vanilla (soa_jewish_events.txt) for characters that should not convert 
Flag is used via create_character, but it might also work in character history for patriarchs

**Comment by loup99** [comment]
That might be something to consider for the historical patriarches.
