### ISSUE TITLE
Cannot switch to imperial laws; pre-feudal cannot become feudal/sub-roman/tribal

### ISSUE THREAD

**Issue by drakondrachma** [loup99/WtWSMS#433]
Hello! I'm not using the github version of the release, only the steam ver, but feel it's probably more helpful to file a report here. Here are the itemised problems:

I. Imperial/Bureaucratic realm law cannot be selected, even after feudal law is adapted. The law reads 'never,' and looking at the code reveals that you need to have title revocation 2, that being religious revocation mandate. Given that seems to have been superceded by religious intolerance laws, I feel this is a holdover? Either way:

- Religious revocation cannot be selected, ever.
- Therefore, Imperial administration cannot be adopted, save through event (restoring WRE, for example);
- Therefore, consider re-examining how the administration/revocation laws interact.

II. Pre-feudal realms seem permanently stuck as pre-feudal society; there are no corresponding events to model their adoption of feudal governance, at least not in my experiences. To wit I've only played two campaigns as pre-feudals, so this one could easily be user error. c:   
Nevertheless...

- Pre-feudal societies cannot become feudal, limiting their options and law.
- Technology, events, or decisions, do not let them become a more 'central' or advanced form of government;
- Consider a note if this is WAD or otherwise consider fleshing out pre-feudal areas... When time permits.

Lastly, whether these are problems or WAD, thank you so much for all the hard work on this mod. This is easily my favourite mod since LI, and though LI will remain so long as there is light in the hearts of all good folk, knowing this neato mod exists just made my day. Funnily enough, I would never have had heard about it except I was looking for a completely unrelated novel! 

All the best, take your time, I'm sure you've plenty of things to work on. Stay safe, stay hydrated, and best wishes!!

**Comment by loup99** [comment]
> I. Imperial/Bureaucratic realm law cannot be selected, even after feudal law is adapted. The law reads 'never,' and looking at the code reveals that you need to have title revocation 2, that being religious revocation mandate. Given that seems to have been superceded by religious intolerance laws, I feel this is a holdover? Either way:
> 
> * Religious revocation cannot be selected, ever.
> * Therefore, Imperial administration cannot be adopted, save through event (restoring WRE, for example);
> * Therefore, consider re-examining how the administration/revocation laws interact.

This has already been fixed for the next version.

> II. Pre-feudal realms seem permanently stuck as pre-feudal society; there are no corresponding events to model their adoption of feudal governance, at least not in my experiences. To wit I've only played two campaigns as pre-feudals, so this one could easily be user error. c:
> Nevertheless...
> 
> * Pre-feudal societies cannot become feudal, limiting their options and law.
> * Technology, events, or decisions, do not let them become a more 'central' or advanced form of government;
> * Consider a note if this is WAD or otherwise consider fleshing out pre-feudal areas... When time permits.

The idea is to flesh out pre-feudal, at the moment it is sort of work in progress.

> Lastly, whether these are problems or WAD, thank you so much for all the hard work on this mod. This is easily my favourite mod since LI, and though LI will remain so long as there is light in the hearts of all good folk, knowing this neato mod exists just made my day. Funnily enough, I would never have had heard about it except I was looking for a completely unrelated novel!
> 
> All the best, take your time, I'm sure you've plenty of things to work on. Stay safe, stay hydrated, and best wishes!!

Thank you!

**Comment by drakondrachma** [comment]
Thank you so much; I'm not re-opening this, but one last thing; I notice that only christian_group characters can rebuild the circus maximus, which means that only christians can restore rome. This also might be WAD, as I'm not really sure a hellenic would have had enough legitimacy to restore the WRE at the time..?

Either way, thanks again! Please take your time with everything, and of course I'll keep playing!

**Comment by loup99** [comment]
I didn't write that particular decision, but it was indeed done for Christians only. In the future we might change this.
