### ISSUE TITLE
Galliya

### ISSUE THREAD

**Issue by MordredDerby** [loup99/WtWSMS#435]
I propose to rename this slavic culture because it doesn't even sound like an adjective. It's just slightly "slavicized" Gaul/Gallia. I'd say it should be named Hallska intead. Using "H" ingstead of "G" represents characteristic fricative ɣ and -ska adjective suffix as in Polska, Slovenska or Ukrainska.

P.S. Some other slavic melting pot cultures sound pretty alien too, but I don't have any good ideas on how to fix them for now.

**Comment by loup99** [comment]
OK, thank you for the suggestion.
