### ISSUE TITLE
Duplicate decrease_prosperity_effect

### ISSUE THREAD

**Issue by tannerflick4** [loup99/WtWSMS#443]
Hello Loup and team,

There is a duplicate effect, in use in regular scripted effects file and the ACR scripted effect file as well

decrease_prosperity_effect

I would just fix it myself, but the ACR version is different and more involved, so I wanted to give a heads up for you all to check this.

**Comment by loup99** [comment]
This problem stems from ACR itself, it is present in the integrated mod
