### ISSUE TITLE
Reduce syntax errors raised by The Validator

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#46]
Issue to track the progress in reducing the number of syntax errors, especially in events/decisions, via The Validator (http://forum.paradoxplaza.com/forum/showthread.php?597480-The-Validator-Find-errors-quickly-and-with-minimal-pain!)

Using invalid types in conditions/commands is frequent cause of (random) CTDs like #22.
For instance: graphical_culture = bedouin_arabic will CTD, correct syntax being graphical_culture = arabicgfx.

**Comment by loup99** [comment]
A question, is the unit issue fixed or is still a problem for those having that specific DLC? Is it an issue that the Validator mentions?

**Comment by rquinio** [comment]
I don't think so and I'm not sure how to reproduce the issue (maybe that's because I don't take too much attention to unit models ^^). You can open a separate bug on this, if there are more infos. :)

**Comment by loup99** [comment]
I will do so, even if we have little info.

**Comment by rquinio** [comment]
There are a few files that were unused and that I moved in sub-directories:
- \history\provinces\~temp
- \history\provinces\unused
- \history\titles\unused
- \gfx\flags\unused
They will need to be reviewed/deleted depending whether this is WIP or useless stuff.
