### ISSUE TITLE
Backwater non-reformed pagan balance

### ISSUE THREAD

**Issue by Ironmaggot** [loup99/WtWSMS#67]
This issue is about the pagans in the far and dark reaches of the world of whom we know very little about(Most of north-eastern Europe and west Siberia). Currently they are 2-5 province tribes. After starting the game, they usually start subjugating left and right and within less than a decade there are vast powerhouses in places where large polities should arise centuries in future. As I see it, this kind of behavior should not be a "normal" behavior, but rather a rarity - sorta like ambitious rulers doing their thing rather than normal one's.

**Comment by Zusk** [comment]
Finnic pagans could get a aggression reduction kind of like Jains do

**Comment by Ironmaggot** [comment]
Neutering Finnic pagan agressiveness would only really solve one part of the problem. What about the Slavic pagans or the Germanic pagans? All - Finnic, Slavic and Germanic dudes should not really conquering and subjugating left and right, except when we are dealing with exceptional polities or characters that should be big shots and should be conquering.

One possible solution would be to restrict non-reformed pagans to demesne size 1, which would be lifted after reformation. This solution still permits conquests for those, who want, but there wouldn't be a situation where one ruler holds two duchy worth of counties alone. 

Another possible solution would be to actually make most of the pagans start out with 1 province. Although, those who are closer, should have progressively more, the closer they are. And also the famous conquerors should posses the lands they did.

**Comment by Zusk** [comment]
Germanic pagans should be subjugating, see the Norse expansion into England.

Slavic pagans should also expand as well, see the Slavic Migration
http://www.andrzejb.net/slavic/images/map2.jpg

**Comment by loup99** [comment]
Germanic should sty agresive, as long as their CB's are tweaked so they don't blobb boderlessly, but Slavs can migrate, but do they really need more than that? Tengri can unify and split within a decade. The problem isthat there should be a difference between "norse"-pacific before viking age, and germanic who pillages Europe.

**Comment by Ironmaggot** [comment]
That's not what I mean, guys. I mean that a lot of the realms are way too stable and strong and their strength can snowball very easily. Slav expansion took a few centuries, currently it takes them 20 years to do that same thing.

I have noticed that a lot of the pagan realms have one dude controlling 2-5 realms. And those 4+ realms are the one's that usually start blobbing since they have 4000+ troops at hand thanks to their provinces being the demesne. Perhaps a better alternative would be to limit demesne to 1 for the unreformed low-tech pagans, so that they cannot form monstrous demesnes and instead create vassals. This would reduce their warring frequency naturally, since liege must keep in mind when the vassals would join the wars. Vassals again, bring their own factioning and plotting to equation so that the big pagan realms are not so stable internally and can break up trough rebellions or inheritance.

What do you think? Severly limit demesne limit to force AI make vassals?

**Comment by rquinio** [comment]
Maybe it's worth waiting after the effects of technology nerf (0 Legalism will now only allow Low centralization) https://github.com/rickinator9/WTWSMS/issues/60, and Migration CB bugfix/tweaks https://github.com/rickinator9/WTWSMS/issues/19, as these will have major impacts ?

**Comment by Ironmaggot** [comment]
Okay, lets see.

**Comment by loup99** [comment]
With the additional limitations on subjugation and AI limitations of CB, this is resolved.
