### ISSUE TITLE
Kemetic Pagans need a nerf

### ISSUE THREAD

**Issue by Zusk** [loup99/WtWSMS#69]
Simply put, its far too common to see massive, sprawling Neo-Egyptian empires. This is partially because its too easy for the Garamantes to convert their provinces.

We could use them being given Central African Pagan Vassals and the Kemetic religion itself becoming unreformed.

**Comment by loup99** [comment]
Before tweaking this in any way, you should wait upon https://github.com/rickinator9/WTWSMS/issues/23 and Romullien's integration.

**Comment by rquinio** [comment]
The huge number of holdings they own makes them quite powerful compared to their tribal neighbours. Religion can be tweaked, but it won't change the root cause !
Maybe a levy/tax penalty on all their provinces ?

**Comment by Zusk** [comment]
If they had disgruntled vassals it would cause more interesting things to happen to all that land they own, rather then it becoming one gigantic garamantes, egyptian blob.

**Comment by rquinio** [comment]
https://github.com/loup99/WtWSMS/pull/125 is also a step in the right direction.

**Comment by loup99** [comment]
This has been largely resolved as of the latest release.
