### ISSUE TITLE
A settings menu has been made? What do we do with it?

### ISSUE THREAD

**Issue by Zusk** [loup99/WtWSMS#74]
![settingsmenu2](https://cloud.githubusercontent.com/assets/10676712/6520116/d0c2a892-c373-11e4-9366-fb988aa9f5a8.gif)

So, you know that settings menu I talked about implementing a few months back? Well, I finally got around to it!

I plan on, for myself letting it adjust settings for Islam and Migration, do you guys have any other systems you feel should be attached to this menu and become adjustable? I feel like Ancient Religions Reborn "Paganify World" decision could be moved to it for example.

**Comment by loup99** [comment]
Yes, some custmization could be good. And even if it is not "historical", it can be used by those who want a bit of a different experience. Church councils or melting-pots might be tweaked with it?

**Comment by loup99** [comment]
This will instead be handled by the game rules, as they allow for more easy tuning within the game interface.
