### ISSUE TITLE
Pagan vassals converting to monotheist faiths

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#88]
Extracted issue reported by @ortogate from https://github.com/rickinator9/WTWSMS/issues/87

>Hello guys! Sorry for the obtrusion, but perhaps you can help me a bit.

>Long story short, I've been rocking the hell out of your awesome mod for quite a while now and I've been playing as a Hellenic WREmperor, with a lot of reconquered territory, and having a blast. I'm also pontifex maximus and all my vassals (and their vassals) are Hellenic as well.

>So, to the problem: ever since updating the game and your mod to the latest version, for no apparent reason, plenty of my vassals just keep converting back to whatever religion was there before I conquered (Nicene, Arian, etc.) and the Hellenic authority just keeps bleeding out from 100% towards 0% as all my vassals progressively transform into infidel scum, effectively making my current save "unplayable". I've been compulsively updating to every new commit but to no avail.

>Are you aware of this issue? Is it just some weird bug that just happened to me, due to some file corruption or something like it? Is there anyway I can fix it?

>Thanks in advance for your time, and for the best CKII mod I've ever played.

loup99:
> First of all, hi ortogate! Secondly, I recommend you to create a new issue the next time.

> Concerning the update, did you continue on an old game? There might be some savegame compatibility issues between version, so I would recommend you to start a clean new save, especially with this development branch.

ortogate:
> Hi Loup99, thank you very much for your answer! Sorry, I only started using github because of your mod and I'm still learning my way around. I will start a new issue next time then.

> Yes, indeed it was a continuation of an old save. In an ordinary situation I would've just avoided upgrading at all and kept playing my save. But at some point it became buggy and it got to the point of getting a CTD every time . The upgrade fixed the CTD but introduced the aforementioned bug. Is there any way (using the console or file editing for instance) of simply locking every vassal to the current religion, preventing them from converting to another? If not I'll come to terms with letting my resurrected empire go :(

loup99:

> The best place for posting would actually be: https://forum.paradoxplaza.com/forum/index.php?forums/when-the-world-stopped-making-sense-mod.876/

> Locking people to a specific religion? I'm afraid that it is not possible in that way, no, or at leasst not as far as I know. There are ways of doing it, but they require coding and wouldn't be optimal either.

**Comment by loup99** [comment]
Anyone who can confirm that is an issue in freshly started games? I currently do not have acess to a device where I can test if that is the case.

**Comment by rquinio** [comment]
I've added some logging, and this seem to come from the convert_to_spouse_xxx decisions.
The have ai_will_do = { factor = 0.1 }, while vanilla has ai =no.

**Comment by rquinio** [comment]
Fixed.
