### ISSUE TITLE
Justinian plague

### ISSUE THREAD

**Issue by rquinio** [loup99/WtWSMS#96]
I open this issue to track anything related to the [Justinian Plague](https://en.wikipedia.org/wiki/Plague_of_Justinian).
Initial setup was done via PR #94 
More flavor events ?
- Plague doctors may have appeared for the first time ?
- One time recurrences of the plague in 7th and 8th century (but less contagious / shorter outbreaks) ?
- Ways to reduce the effect of the plague in some cultures ? (there's a reduce_disease command, not sure how it works)
- ...

Note: scripting of epidemics is a bit limited (there seem to be no way to test a province for a specific epidemic disease), and testing traits require low MTTH given the deadliness of the plague, which might be heavy on performance.

**Comment by IhateTrains** [comment]
Is it going to be redone using the mechanics of The Reaper's Due?

**Comment by loup99** [comment]
Has already been done.

**Comment by loup99** [comment]
With the Reaper's Due and later content I consider this to be fully implemented and tested as of writing this post.
