### ISSUE TITLE
Bloody hell, I just added a file I shouldn't have.

### ISSUE THREAD

**Issue by CaudilloFranco** [loup99/WtWSMS#98]
Any suggestions or help with be appreciated a lot. I made WtWSMS_caudillo_franco_events.txt but I don't know how to add it from my Desktop to the repository.

**Comment by loup99** [comment]
I just changed the name. :wink:

**Comment by CaudilloFranco** [comment]
Thanks for the help. I feel like an idiot, but all is well at the least 😀
